(function(g){var window=this;'use strict';var Np=function(r){r.publish("cardstatechange",r.mf()&&r.ai()?1:0)},jB=function(r,l){var U=g.k$(l),F=U?l:arguments;
for(U=U?0:1;U<F.length;U++){if(r==null)return;r=r[F[U]]}return r},ba8=function(r){var l=g.ji(r);
r=g.uD(r);return new g.Qg(l.x,l.y,r.width,r.height)},ND8=function(r,l,U){var F=F===void 0?{}:F;
var Y;return Y=g.NO(r,l,function(){g.jX(Y);U.apply(r,arguments)},F)},uL=function(r){r=g.lC(r);
delete qp[r];g.aY(qp)&&TB&&TB.stop()},q6C=function(){TB||(TB=new g.F1(function(){jlr()},20));
var r=TB;r.isActive()||r.start()},jlr=function(){var r=g.Y0();
g.gR(qp,function(l){TDG(l,r)});
g.aY(qp)||q6C()},yj=function(r,l,U,F){g.Wl.call(this);
if(!Array.isArray(r)||!Array.isArray(l))throw Error("Start and end parameters must be arrays");if(r.length!=l.length)throw Error("Start and end points must be the same length");this.X=r;this.j=l;this.duration=U;this.U=F;this.coords=[];this.progress=this.D=0;this.K=null},TDG=function(r,l){l<r.startTime&&(r.endTime=l+r.endTime-r.startTime,r.startTime=l);
r.progress=(l-r.startTime)/(r.endTime-r.startTime);r.progress>1&&(r.progress=1);r.D=1E3/(l-r.K);r.K=l;uF0(r,r.progress);r.progress==1?(r.W=0,uL(r),r.onFinish(),r.RJ()):r.isPlaying()&&r.m8()},uF0=function(r,l){typeof r.U==="function"&&(l=r.U(l));
r.coords=Array(r.X.length);for(var U=0;U<r.X.length;U++)r.coords[U]=(r.j[U]-r.X[U])*l+r.X[U]},yE0=function(r,l){g.lM.call(this,r);
this.coords=l.coords;this.x=l.coords[0];this.y=l.coords[1];this.z=l.coords[2];this.duration=l.duration;this.progress=l.progress;this.fps=l.D;this.state=l.W},Bt=function(r,l,U,F,Y){yj.call(this,l,U,F,Y);
this.element=r},BDC=function(r,l,U,F,Y){if(l.length!=2||U.length!=2)throw Error("Start and end points must be 2D");
Bt.call(this,r,l,U,F,Y)},HaC=function(r){return Math.pow(r,3)},gyG=function(r){return 3*r*r-2*r*r*r},wvq=function(r){g.H.call(this);
this.X=r||window;this.W=[]},Ht=function(r){return r.baseUrl||null},ge=function(r,l){return g.wV(g.aI(r,l),function(U){return!!U})},DbC=function(r,l,U){function F(U4){var $$=U4.hovercardButton;
if(!$$)return null;$$=$$.subscribeButtonRenderer;if(!$$)return null;var Y$=e($$.unsubscribedButtonText),L=e($$.subscribedButtonText);if($$.subscribed){var Ae=e($$.subscriberCountWithUnsubscribeText);var G3=e($$.subscriberCountText)}else Ae=e($$.subscriberCountText),G3=e($$.subscriberCountWithSubscribeText);var z3=null;if(U4.signinEndpoint){z3=jB(U4,"signinEndpoint","webNavigationEndpointData","url");if(!z3){var RY,dR;z3=(dR=g.V((RY=$$.signInEndpoint)==null?void 0:RY.commandMetadata,g.hq))==null?void 0:
dR.url}if(!z3)return null}return Y$&&(L||z3)?{subscribed:$$.subscribed,subscribeText:Y$,subscribeCount:Ae,unsubscribeText:L,unsubscribeCount:G3,enabled:$$.enabled,signinUrl:z3,classic:U4.useClassicSubscribeButton}:null}
function Y(U4){if(U4){var $$=[],Y$=U4.videoId;Y$&&$$.push("v="+Y$);(Y$=U4.playlistId)&&$$.push("list="+Y$);(U4=U4.startTimeSeconds)&&$$.push("t="+U4);return"/watch?"+$$.join("&")}}
function e(U4){if(!U4)return null;var $$=U4.simpleText;return $$?$$:U4.runs?g.aI(U4.runs,function(Y$){return Y$.text}).join(""):null}
l=l.endscreenElementRenderer;if(!l)return null;var d=l.style,K=l.endpoint||{},C=null,v=null,J=!1,m=null,P=null,A=null,M=null,E=!1,Z=null,n=null,h=null,N=null,u=null,D=null;if(d==="VIDEO")g.V(K,g.aK)?C=g.V(K,g.aK).url:(D=g.V(K,g.Kk),C=Y(D)),v=!1,m=r,l.thumbnailOverlays?(J=l.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,P=e(J.text),J=J.style==="LIVE"):P=e(l.videoDuration);else if(d==="PLAYLIST")g.V(K,g.aK)?C=g.V(K,g.aK).url:(D=g.V(K,g.Kk),C=Y(D)),v=!1,m=r,A=e(l.playlistLength);else if(d===
"CHANNEL"){if(E=jB(K,"browseEndpoint","browseId"))M=E,C="/channel/"+M;v=!1;m="new";(E=!!l.isSubscribe)?Z=F(l):n=e(l.subscribersText)}else d==="WEBSITE"?((h=jB(K,"urlEndpoint","url"))&&(C=h),v=!0,m="new",h=l.icon.thumbnails[0].url):d==="CREATOR_MERCHANDISE"&&(l.productPrice&&(N=e(l.productPrice)),l.additionalFeesText&&(u=e(l.additionalFeesText)),(v=jB(K,"urlEndpoint","url"))&&(C=v),v=!0,m="new");r=jB(l,"title","accessibility","accessibilityData","label");var t=l.endpoint?l.endpoint.clickTrackingParams:
null,z="";if(l.metadata){var I=e(l.metadata);I&&(z=I)}return{id:"element-"+U,type:d,title:e(l.title),metadata:z,callToAction:e(l.callToAction),Am:l.image,iconUrl:h,left:Number(l.left),width:Number(l.width),top:Number(l.top),aspectRatio:Number(l.aspectRatio),startMs:Math.floor(Number(l.startMs)),endMs:Math.floor(Number(l.endMs)),videoDuration:P,Pf:J,playlistLength:A,channelId:M,subscribeButton:Z,subscribersText:n,isSubscribe:E,targetUrl:C||null,ZQ:v,sessionData:t?{itct:t}:null,rhH:m,Fy:r?r:null,isPlaceholder:l.isPlaceholder,
impressionUrls:ge(l.impressionUrls||[],Ht),P6:ge(l.hovercardShowUrls||[],Ht),clickUrls:ge(K.loggingUrls||[],Ht),visualElement:g.Tz(l.trackingParams),productPrice:N,additionalFeesText:u,watchEndpoint:D||null}},Vjr=function(r,l){var U={startMs:Math.floor(Number(r.startMs)),
impressionUrls:ge(r.impressionUrls||[],Ht),elements:ge(r.elements||[],function(F,Y){return DbC(l,F,Y)})};
r.trackingParams&&(U.visualElement=g.Tz(r.trackingParams));return U},f40=function(r){g.Rf.call(this,r);
this.K=this.endscreen=null;this.X={};this.D={};this.U=this.L=null;this.T=[];this.W=null;this.kN=!0;this.j=0;r=r.N();this.V=g.th(r)||g.cp(r);this.events=new g.Lg(this);g.w(this,this.events);this.events.G(this.player,g.x1("creatorendscreen"),this.onCueRangeEnter);this.events.G(this.player,g.W9("creatorendscreen"),this.onCueRangeExit);this.events.G(this.player,"resize",this.hB);this.events.G(window,"focus",this.CJw);this.load();var l=g.I1("STYLE");(g.Vp("HEAD")[0]||document.body).appendChild(l);this.addOnDisposeCallback(function(){g.lD(l)});
l.sheet&&(l.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),l.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},S68=function(r){return r.player.getVideoData().f0?"current":r.V?"new":"current"},we=function(r){return r.player.N().playerStyle==="creator-endscreen-editor"},zqY=function(r){var l=r.player.getVideoData(),U=l.videoId;
r.K&&r.K.abort();U={method:"POST",onFinish:function(Y){var e=r.K=null;Y.status===200&&(Y=Y.responseText,Y.substring(0,3)===")]}"&&(Y=Y.substring(3),e=JSON.parse(Y),e=Vjr(e,S68(r))));DE(r,e)},
urlParams:{v:U},withCredentials:!0};r.V&&(U.urlParams.ptype="embedded");var F=l.wc;F&&(U.postParams={ad_tracking:F});if(l=g.iV$(l))if(l=g.py(l),l=g.fy(l))r.K=g.Tj(l,U)},DE=function(r,l,U){U=U===void 0?!0:U;
r.player.MB("creatorendscreen");r.L&&(r.L.dispose(),r.L=null,r.U.dispose(),r.U=null);for(var F=g.Q(Object.values(r.X)),Y=F.next();!Y.done;Y=F.next())Y.value.dispose();r.X={};r.D={};r.T.length>0&&(r.T.forEach(function(K){K.dispose()}),r.T.length=0);
r.W&&(g.M0(r.W,"ytp-ce-element-show"),r.W.setAttribute("aria-hidden","true"));r.j=0;if((r.endscreen=l)&&l.elements){U&&pvj(r);U=[];F=new g.M2(l.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});U.push(F);r.player.N().X||(r.L=new g.p({Z:"div",S:"ytp-ce-shadow"}),g.Sg(r.player,r.L.element,4),r.U=new g.P5(r.L,200));for(F=0;F<l.elements.length;++F){Y=l.elements[F];var e=tj8(r,Y);if(e){r.X[Y.id]=e;r.D[Y.id]=Y;g.Sg(r.player,e.element,4);var d=new g.M2(Y.startMs,Y.endMs,{id:"ytp-ce-element-"+
Y.id,namespace:"creatorendscreen"});U.push(d);Le8(r,e,Y)}else g.pZ(new g.lY("buildEndscreenElement null",Y))}r.player.sN(U);r.hB()}},pvj=function(r){var l=g.y$(),U=g.Bh();
U&&l&&r.endscreen.visualElement&&g.e7(g.Fv)(void 0,U,l,r.endscreen.visualElement)},tj8=function(r,l){var U=null;
switch(l.type){case "VIDEO":r={Z:"div",Dz:["ytp-ce-element","ytp-ce-video"],J:{tabindex:"0","aria-label":l.Fy||"","aria-hidden":"true"},B:[{Z:"div",S:"ytp-ce-element-shadow"},{Z:"div",S:"ytp-ce-covering-image",J:Vj(l)},{Z:"div",S:"ytp-ce-covering-shadow-top"},{Z:"a",S:"ytp-ce-covering-overlay",J:{href:fc(r,l.targetUrl),tabindex:"-1"},B:[{Z:"div",Dz:["ytp-ce-video-title","ytp-webkit-ellipsis"],J:{dir:g.nJ(l.title||"")},XT:l.title},{Z:"div",S:l.Pf?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
XT:l.videoDuration||void 0}]}]};U=new g.p(r);break;case "PLAYLIST":r={Z:"div",Dz:["ytp-ce-element","ytp-ce-playlist"],J:{tabindex:"0","aria-label":l.Fy||"","aria-hidden":"true"},B:[{Z:"div",S:"ytp-ce-element-shadow"},{Z:"div",S:"ytp-ce-covering-image",J:Vj(l)},{Z:"div",S:"ytp-ce-covering-shadow-top"},{Z:"a",S:"ytp-ce-covering-overlay",J:{href:fc(r,l.targetUrl),tabindex:"-1"},B:[{Z:"div",Dz:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],J:{dir:g.nJ(l.title||"")},XT:l.title},{Z:"div",S:"ytp-ce-playlist-count",
B:[{Z:"div",S:"ytp-ce-playlist-icon"},{Z:"div",S:"ytp-ce-playlist-count-text",XT:l.playlistLength||void 0}]}]}]};U=new g.p(r);break;case "CHANNEL":U={Z:"div",Dz:["ytp-ce-element","ytp-ce-channel",l.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],J:{tabindex:"0","aria-label":l.Fy||"","aria-hidden":"true"},B:[{Z:"div",S:"ytp-ce-element-shadow"},{Z:"div",S:"ytp-ce-expanding-overlay",B:[{Z:"div",S:"ytp-ce-expanding-overlay-hider"},{Z:"div",S:"ytp-ce-expanding-overlay-background"},{Z:"div",S:"ytp-ce-expanding-overlay-content",
B:[{Z:"div",S:"ytp-ce-expanding-overlay-body",B:[{Z:"div",S:"ytp-ce-expanding-overlay-body-padding",B:[{Z:"a",Dz:["ytp-ce-channel-title","ytp-ce-link"],J:{href:fc(r,l.targetUrl),target:"_blank",tabindex:"-1",dir:g.nJ(l.title||"")},XT:l.title},l.subscribeButton?{Z:"div",S:"ytp-ce-subscribe-container",B:[{Z:"div",S:"ytp-ce-channel-subscribe"}]}:"",l.subscribersText?{Z:"div",S:"ytp-ce-channel-subscribers-text",XT:l.subscribersText}:"",l.metadata?{Z:"div",Dz:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],XT:l.metadata}:""]}]}]}]},{Z:"div",S:"ytp-ce-expanding-image",J:Vj(l)}]};U=new g.p(U);var F=g.St(document,"div","ytp-ce-channel-subscribe",U.element)[0];if(l.subscribeButton&&l.channelId){g.Pl(F,"ytp-ce-subscribe-button");if(r.player.N().X){var Y=null;var e=l.sessionData.itct}else Y="endscreen",e=null;Y=new g.lX(l.subscribeButton.subscribeText,l.subscribeButton.subscribeCount,l.subscribeButton.unsubscribeText,l.subscribeButton.unsubscribeCount,!!l.subscribeButton.enabled,!!l.subscribeButton.classic,
l.channelId,!!l.subscribeButton.subscribed,Y,e,r.player,!1);F.appendChild(Y.element);r.T.push(Y)}break;case "WEBSITE":r={Z:"div",Dz:["ytp-ce-element","ytp-ce-website"],J:{tabindex:"0","aria-label":l.Fy||"","aria-hidden":"true"},B:[{Z:"div",S:"ytp-ce-element-shadow"},{Z:"div",S:"ytp-ce-expanding-overlay",B:[{Z:"div",S:"ytp-ce-expanding-overlay-hider"},{Z:"div",S:"ytp-ce-expanding-overlay-background"},{Z:"div",S:"ytp-ce-expanding-overlay-content",B:[{Z:"div",S:"ytp-ce-expanding-overlay-body",B:[{Z:"div",
S:"ytp-ce-expanding-overlay-body-padding",B:[{Z:"div",S:"ytp-ce-website-title",J:{dir:g.nJ(l.title||"")},XT:l.title},{Z:"div",S:"ytp-ce-website-metadata",XT:l.metadata},{Z:"a",Dz:["ytp-ce-website-goto","ytp-ce-link"],J:{href:fc(r,l.targetUrl),target:"_blank",tabindex:"-1"},XT:l.callToAction}]}]}]}]},{Z:"div",S:"ytp-ce-expanding-image",J:Vj(l)},{Z:"div",S:"ytp-ce-expanding-icon",J:cER(l.iconUrl)}]};U=new g.p(r);break;case "CREATOR_MERCHANDISE":U="",l.productPrice&&(U={Z:"div",S:"ytp-ce-merchandise-price-container",
B:[{Z:"div",S:"ytp-ce-merchandise-price",XT:l.productPrice}]},l.additionalFeesText&&U.B.push({Z:"div",S:"ytp-ce-merchandise-additional-fees",XT:l.additionalFeesText})),r={Z:"div",Dz:["ytp-ce-element","ytp-ce-merchandise"],J:{tabindex:"0","aria-label":l.Fy||"","aria-hidden":"true"},B:[{Z:"div",S:"ytp-ce-element-shadow"},{Z:"div",S:"ytp-ce-expanding-overlay",B:[{Z:"div",S:"ytp-ce-expanding-overlay-hider"},{Z:"div",S:"ytp-ce-expanding-overlay-background"},{Z:"div",S:"ytp-ce-expanding-overlay-content",
B:[{Z:"div",S:"ytp-ce-expanding-overlay-body",B:[{Z:"div",S:"ytp-ce-expanding-overlay-body-padding",B:[{Z:"div",S:"ytp-ce-merchandise-title",J:{dir:g.nJ(l.title||"")},XT:l.title},U,{Z:"div",S:"ytp-ce-merchandise-metadata",XT:l.metadata},{Z:"a",Dz:["ytp-ce-merchandise-goto","ytp-ce-link"],J:{href:fc(r,l.targetUrl),target:"_blank",tabindex:"-1"},XT:l.callToAction}]}]}]}]},{Z:"div",S:"ytp-ce-expanding-image",J:Vj(l)},{Z:"div",S:"ytp-ce-merchandise-invideo-cta-container",B:[{Z:"div",S:"ytp-ce-merchandise-invideo-cta",
XT:l.callToAction||void 0}]}]},U=new g.p(r)}l.isPlaceholder&&g.Pl(U.element,"ytp-ce-placeholder");return U},Vj=function(r){if(r.Am)var l=r.Am.thumbnails;
return cER(l?l[l.length-1].url:null)},cER=function(r){return r?{style:"background-image: url("+r+")"}:{}},Le8=function(r,l,U){function F(C){C&&(l.listen("blur",function(){C.style.display!="none"&&r.kN&&C.focus()}),l.G(C,"focus",e),l.G(C,"blur",d))}
function Y(C){r.j+=C;r.j>0?(g.Pl(l.element,"ytp-ce-force-expand"),SB(r,U.id,!0)):(g.M0(l.element,"ytp-ce-force-expand"),g.M0(l.element,"ytp-ce-element-hover"),SB(r,U.id,!1))}
function e(){Y(1)}
function d(){Y(-1)}
l.listen("mouseenter",function(){a4C(r,l,U)});
l.listen("mouseleave",function(){I48(r,l,U)});
r.player.N().X||l.listen("click",function(){g.Pl(l.element,"ytp-ce-element-hover")});
l.listen("click",function(C){kSC(r,U,C)});
l.listen("keypress",function(C){kSC(r,U,C)});
l.listen("focus",function(){a4C(r,l,U)});
l.listen("blur",function(){I48(r,l,U)});
l.listen("touchstart",function(){a4C(r,l,U)});
var K=g.ze("ytp-ce-expanding-overlay-hider",l.element);K&&l.G(K,"touchstart",function(C){C.stopPropagation();g.M0(l.element,"ytp-ce-element-hover");g.M0(l.element,"ytp-ce-force-expand")});
l.listen("keydown",function(C){r.kN=C.keyCode===9&&!C.shiftKey});
F(g.ze("ytp-sb-subscribe",l.element));F(g.ze("ytp-sb-unsubscribe",l.element));l.listen("focus",e);l.listen("blur",d)},kSC=function(r,l,U){if(l.targetUrl&&(!U||U.type!=="keypress"||U.keyCode===13)){for(var F=U.target;F&&!g.mJ(F,"ytp-ce-element");){g.mJ(F,"subscribe-label")&&oTC(r,l);
if(g.mJ(F,"ytp-ce-channel-subscribe"))return;F=F.parentElement||null}if(!F||g.mJ(F,"ytp-ce-element-hover")){U.preventDefault();U.stopPropagation();if(F=r.X[l.id])I48(r,F,l),F.element.blur();if(U.ctrlKey||U.metaKey||l.rhH==="new")oTC(r,l),r.player.sendVideoStatsEngageEvent(17,void 0),r.player.pauseVideo(),U=g.py(fc(r,l.targetUrl)),U=g.fy(U),g.UO(U,void 0,l.sessionData);else{var Y=g.Oi(r.player.N())||r.player.getVideoData().f0,e=function(){var d=fc(r,l.targetUrl),K=l.sessionData,C=l.watchEndpoint,v=
g.JZ(d);Y&&v&&(v.v||v.list)?r.player.zI(v.v,K,v.list,!1,void 0,C||void 0):g.lO(d,K)};
oTC(r,l,function(){r.player.sendVideoStatsEngageEvent(17,e)})}}}},fc=function(r,l){r=r.player.N();
if(l){if(l.startsWith("//"))return r.protocol+":"+l;if(l.startsWith("/"))return g.Ad(r)+l}else return"";return l},a4C=function(r,l,U){g.mJ(l.element,"ytp-ce-element-hover")||(U.type==="VIDEO"||U.type==="PLAYLIST"?g.Pl(l.element,"ytp-ce-element-hover"):r.player.N().X?(new g.F1(function(){g.Pl(l.element,"ytp-ce-element-hover")},200)).start():g.Pl(l.element,"ytp-ce-element-hover"),zB(r,U.P6),SB(r,U.id,!0))},I48=function(r,l,U){g.M0(l.element,"ytp-ce-element-hover");
g.M0(l.element,"ytp-ce-force-expand");SB(r,U.id,!1)},SB=function(r,l,U){r.L&&(U?r.U.show():r.U.hide());
for(var F=g.Q(Object.keys(r.X)),Y=F.next();!Y.done;Y=F.next())Y=Y.value,Y!==l&&g.xl(r.X[Y].element,"ytp-ce-element-shadow-show",U)},zB=function(r,l,U){function F(){e||(Y++,Y===l.length&&(d.stop(),U&&U()))}
if(!l||l.length===0||we(r))U&&U();else{l=rsY(r,l);var Y=0,e=!1,d=new g.F1(function(){e=!0;U&&U()},1E3,r);
d.start();for(r=0;r<l.length;r++)g.cg(l[r],F)}},oTC=function(r,l,U){zB(r,l.clickUrls,U);
(r=g.Bh())&&l.ZQ&&g.MP(r,l.visualElement)},rsY=function(r,l){var U=r.player.getVideoData().clientPlaybackNonce;
r=r.player.getCurrentTime().toFixed(2);U={CPN:U,AD_CPN:U,MT:r};r=[];for(var F=0;F<l.length;F++)r.push($q8(l[F],U));return r},$q8=function(r,l){return r.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(U){var F=unescape(U);
F=F.substring(1,F.length-1);return l[F]?escape(l[F]):U})},lb8=function(r){return typeof r==="string"?r:""},pc=function(r,l,U){for(var F in l)if(l[F]===r)return r;
return U},Uqf=function(r,l,U,F){this.value=r;
this.target=l;this.showLinkIcon=U;this.W=F},tX=function(r){return r.value?r.value:null},Lc=function(r){if(!r)return null;
var l=g.py(lb8(r.value));l=g.fy(l);if(!l)return null;var U=pc(r.target,FS0,"current");if(U==null)r=null;else{var F=r.show_link_icon;r=new Uqf(l,U,F==="true"||F==="false"?F==="true":!0,r.pause_on_navigation!=null?r.pause_on_navigation:!0)}return r},Yb0=function(r,l,U){this.type=r;
this.trigger=l;this.url=U},O7G=function(r){if(!r)return null;
var l=pc(r.type,eF8),U=pc(r.trigger,dqr);r=r.url;r=Array.isArray(r)&&r.length?r[0]:r;r=Lc(r?r:null);return l?new Yb0(l,U,r):null},KSG=function(r,l,U,F,Y){this.id=r;
this.type=l;this.style=U;this.data=Y;this.action=F||[]},CQY=function(r,l){return g.m8(r.action,l)},vTb=function(r,l){this.context=r;
this.W=l},JsC=function(r){return r.customMessage?ct("div","iv-card-message",r.customMessage):""},aw=function(r,l){r="background-image: url("+r+");";
var U=[];l&&U.push(l);return{Z:"div",S:"iv-card-image",J:{style:r},B:U}},mq0=function(r){if(!r.metaInfo||r.metaInfo.length===0)return"";
var l=[];r=g.Q(r.metaInfo);for(var U=r.next();!U.done;U=r.next())l.push(ct("li","",U.value));return{Z:"ul",S:"iv-card-meta-info",B:l}},ct=function(r,l,U){l?typeof l==="string"?l={"class":l}:Array.isArray(l)&&(l={"class":l.join(" ")}):l={};
l.dir=g.nJ(U);return{Z:r,J:l,XT:U}},PQR=function(r){if(!r.customMessage)return"";
var l=["iv-card-action","iv-card-primary-link"],U={};r.Qs&&(l.push("iv-card-action-icon"),U.style="background-image: url("+r.Qs+");");U.dir=g.nJ(r.customMessage);var F=[{Z:"span",XT:r.customMessage}];r.showLinkIcon&&(F.push("\u00a0"),F.push({Z:"span",S:"iv-card-link-icon"}));return{Z:"div",Dz:l,J:U,B:F}},Iw=function(r,l,U,F){if(F){l=g.Q(l);
for(var Y=l.next();!Y.done;Y=l.next())r.W(Y.value,F,U.id,U.sessionData,U.X6.click,5)}},As8=function(r,l){this.merchant=r;
this.price=l},MKC=function(r){var l;
(l=r)&&!(l=r.length>1?r.charAt(0)==="/"&&r.charAt(1)!=="/":r==="/")&&(l=r.replace(/^(https?:)?\/\//,"").split("/",1),l=!l||l.length<1||!l[0]?[]:l[0].toLowerCase().split(".").reverse(),l=l[0]==="com"&&l[1]==="youtube"||l[0]==="be"&&l[1]==="youtu");return l?r.indexOf("/redirect?")===-1:!1},sJq=function(r,l){return l?l:MKC(r)?"current":"new"},k5=function(r,l){g.H.call(this);
var U=this;this.element=r;this.context=l;this.W5=!1;this.yT=new Map;this.Nh=new Map;this.context.C.addEventListener(g.x1("annotations_module"),function(F){(F=U.yT.get(F))&&F.apply(U)});
this.context.C.addEventListener(g.W9("annotations_module"),function(F){(F=U.Nh.get(F))&&F.apply(U)})},oy=function(r,l,U,F,Y,e,d){r.context.W.listen(l,"click",function(K){r.Wp(U,F,Y,e||[],d||0,K)});
r.context.W.listen(l,"touchstart",function(){r.W5=!1});
r.context.W.listen(l,"touchmove",function(){r.W5=!0})},xqf=function(r){var l;
return((l=g.V(r,g.aK))==null?0:l.url)?g.V(r,g.aK).url:(r=g.V(r,g.Kk))&&r.videoId?(l="/watch?v="+r.videoId,r.playlistId&&(l+="&list="+r.playlistId),r.index&&(l+="&index="+r.index),r.startTimeSeconds&&(l+="&t="+r.startTimeSeconds),l):null},r9=function(r,l,U){return{sX:(r.impressionLoggingUrlsV2s||[]).map(function(F){return F.baseUrl||""}),
click:(U.loggingUrls||[]).map(function(F){return F.baseUrl||""}),
close:(l.dismissLoggingUrlsV2s||[]).map(function(F){return F.baseUrl||""}),
nF:(l.impressionLoggingUrlsV2s||[]).map(function(F){return F.baseUrl||""}),
Qb:(l.clickLoggingUrlsV2s||[]).map(function(F){return F.baseUrl||""})}},WSY=function(r,l,U){k5.call(this,l,U);
var F=this;this.C=r;this.eventId=null;this.Kp=this.iG=this.xq=this.L=this.isInitialized=!1;this.cards=[];this.kq=this.T=this.YN=this.U=this.vQ=this.W=null;this.kN=[];this.sF=this.j=this.hf=this.qh=null;this.D=0;this.rz=new g.F1(function(){},U.WQ.hK?4E3:3E3);
g.w(this,this.rz);this.If=new g.F1(function(){});
g.w(this,this.If);this.KP=new vTb(U,function(Y,e,d,K,C,v){oy(F,Y,e,d,K,C,v)});
this.V=new g.p({Z:"div",S:"iv-drawer",J:{id:"iv-drawer"},B:[{Z:"div",S:"iv-drawer-header",J:{"aria-role":"heading"},B:[{Z:"span",S:"iv-drawer-header-text"},{Z:"button",Dz:["iv-drawer-close-button","ytp-button"],J:{"aria-label":"Hide cards",tabindex:"0"}}]},{Z:"div",S:"iv-drawer-content"}]});g.w(this,this.V);this.K=this.V.element;this.lG=new g.P5(this.V,330);g.w(this,this.lG);this.Rg=g.ze("iv-drawer-header-text",this.K);this.X=g.ze("iv-drawer-content",this.K);this.addCueRange(0,U.videoData.lengthSeconds*
1E3,"",function(){F.xq&&$E(F,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(F.xq=F.L)&&lv(F)});
this.OF=new g.Lg(this);g.w(this,this.OF);this.C.addEventListener("videodatachange",this.wJ.bind(this))},QJY=function(r,l){l=l.data;
l.autoOpenMs&&r.addCueRange(l.autoOpenMs,0x8000000000000,"",function(){$E(r,"YOUTUBE_DRAWER_AUTO_OPEN")});
l.autoCloseMs&&r.addCueRange(l.autoCloseMs,0x8000000000000,"",function(){lv(r)});
var U=l.headerText;g.Fk(r.Rg,U);r.T&&r.T.setAttribute("title",U);l.eventId&&(r.eventId=l.eventId);r.qh=g.Tz(l.trackingParams);r.j=g.Tz(l.closeTrackingParams);r.hf=g.Tz(l.iconTrackingParams)},ETC=function(r,l){var U=l.cardId?l.cardId:"cr:"+r.D,F=r.C.N().experiments.Jw("enable_error_corrections_infocard_web_client");
if(!l.content&&l.teaser.simpleCardTeaserRenderer&&F){var Y=l.teaser.simpleCardTeaserRenderer,e=l.icon?l.icon.infoCardIconRenderer:null;if(Y.channelAvatar&&Y.channelAvatar.thumbnails&&Y.channelAvatar.thumbnails.length>0)var d=Ul(Y.channelAvatar.thumbnails,22,22).url;l={id:U,timestamp:r.D,type:"simple",teaserText:g.Xv(Y.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:{},sponsored:!1,X6:{},MN:null,Nb:Y.trackingParams?
g.Tz(Y.trackingParams):null,hf:e&&e.trackingParams?g.Tz(e.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,Qs:null,title:"",customMessage:"",url:null,onClickCommand:Y.onTapCommand||null,Xg:d};FK(r,l)}else{var K;if((K=l.content)==null?0:K.simpleCardContentRenderer){if(!l.cueRanges.length)return;d=(Y=l.content)==null?void 0:Y.simpleCardContentRenderer;Y=l.teaser.simpleCardTeaserRenderer;e=l.icon?l.icon.infoCardIconRenderer:null;l={id:U,timestamp:r.D,type:"simple",teaserText:g.Xv(Y.message),
teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:YE(r,U,l,d),sponsored:!1,X6:r9(d,Y,d.command),MN:d.trackingParams?g.Tz(d.trackingParams):null,Nb:Y.trackingParams?g.Tz(Y.trackingParams):null,hf:e&&e.trackingParams?g.Tz(e.trackingParams):null,imageUrl:Ul(d.image.thumbnails,290,290).url,displayDomain:d.displayDomain?g.Xv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Qs:null,title:d.title?g.Xv(d.title):"",
customMessage:d.callToAction?g.Xv(d.callToAction):"",url:g.V(d.command,g.aK).url?Lc({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:g.V(d.command,g.aK).url}):null,onClickCommand:null};FK(r,l)}else{var C;if((C=l.content)==null?0:C.collaboratorInfoCardContentRenderer){if(!l.cueRanges.length)return;d=(e=l.content)==null?void 0:e.collaboratorInfoCardContentRenderer;Y=l.teaser.simpleCardTeaserRenderer;e=l.icon?l.icon.infoCardIconRenderer:null;l={id:U,timestamp:r.D,type:"collaborator",
teaserText:g.Xv(Y.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:YE(r,U,l,d),sponsored:!1,X6:r9(d,Y,d.endpoint),MN:d.trackingParams?g.Tz(d.trackingParams):null,Nb:Y.trackingParams?g.Tz(Y.trackingParams):null,hf:e&&e.trackingParams?g.Tz(e.trackingParams):null,channelId:g.V(d.endpoint,g.yw).browseId,customMessage:d.customText?g.Xv(d.customText):null,profileImageUrl:Ul(d.channelAvatar.thumbnails,290,
290).url,title:d.channelName?g.Xv(d.channelName):"",metaInfo:[d.subscriberCountText?g.Xv(d.subscriberCountText):""],url:Lc({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:g.V(d.endpoint,g.yw).canonicalBaseUrl?g.V(d.endpoint,g.yw).canonicalBaseUrl:"/channel/"+g.V(d.endpoint,g.yw).browseId}),onClickCommand:null};FK(r,l)}else{var v;if((v=l.content)==null?0:v.playlistInfoCardContentRenderer){if(!l.cueRanges.length)return;var J;d=(J=l.content)==null?void 0:J.playlistInfoCardContentRenderer;
Y=l.teaser.simpleCardTeaserRenderer;e=l.icon?l.icon.infoCardIconRenderer:null;l={id:U,timestamp:r.D,type:"playlist",teaserText:g.Xv(Y.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:YE(r,U,l,d),sponsored:!1,X6:r9(d,Y,d.action),MN:d.trackingParams?g.Tz(d.trackingParams):null,Nb:Y.trackingParams?g.Tz(Y.trackingParams):null,hf:e&&e.trackingParams?g.Tz(e.trackingParams):null,Ly:Ul(d.playlistThumbnail.thumbnails,
258,290).url,customMessage:d.customMessage?g.Xv(d.customMessage):null,playlistVideoCount:g.Xv(d.playlistVideoCount),title:d.playlistTitle?g.Xv(d.playlistTitle):"",metaInfo:[d.channelName?g.Xv(d.channelName):"",d.videoCountText?g.Xv(d.videoCountText):""],url:Lc({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:xqf(d.action)}),onClickCommand:null};FK(r,l)}else{var m;if((m=l.content)==null?0:m.videoInfoCardContentRenderer){if(!l.cueRanges.length)return;var P;d=(P=l.content)==
null?void 0:P.videoInfoCardContentRenderer;Y=l.teaser.simpleCardTeaserRenderer;e=l.icon?l.icon.infoCardIconRenderer:null;l={id:U,timestamp:r.D,type:"video",teaserText:g.Xv(Y.message),teaserDurationMs:Number(l.cueRanges[0].teaserDurationMs),startMs:Number(l.cueRanges[0].startCardActiveMs),autoOpen:!!l.autoOpen,sessionData:YE(r,U,l,d),sponsored:!1,X6:r9(d,Y,d.action),MN:d.trackingParams?g.Tz(d.trackingParams):null,Nb:Y.trackingParams?g.Tz(Y.trackingParams):null,hf:e&&e.trackingParams?g.Tz(e.trackingParams):
null,Ly:Ul(d.videoThumbnail.thumbnails,258,290).url,videoDuration:d.lengthString?g.Xv(d.lengthString):null,customMessage:d.customMessage?g.Xv(d.customMessage):null,title:d.videoTitle?g.Xv(d.videoTitle):"",metaInfo:[d.channelName?g.Xv(d.channelName):"",d.viewCountText?g.Xv(d.viewCountText):""],isLiveNow:!!d.badge,url:Lc({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:xqf(d.action)}),onClickCommand:null};FK(r,l)}}}}}r.D++},Ul=function(r,l,U){for(var F=-1,Y=-1,e=0;e<r.length;e++){if(r[e].height===
l||r[e].width===U)return r[e];
((r[e].height||0)<l||(r[e].width||0)<U)&&(F<0||(r[F].height||0)<(r[e].height||0)||(r[F].width||0)<(r[e].width||0))?F=e:((r[e].height||0)>=l||(r[e].width||0)>=U)&&(Y<0||(r[Y].height||0)>(r[e].height||0)||(r[Y].width||0)>(r[e].width||0))&&(Y=e)}return r[Y>=0?Y:F]},YE=function(r,l,U,F){return{feature:U.feature?U.feature:"cards",
src_vid:r.context.videoData.videoId,annotation_id:l,ei:r.context.videoData.eventId||"",itct:F.trackingParams||""}},RF$=function(r,l){if(l=Z78(r,l))l===r.W&&(r.W=null),r.C.removeCueRange(l.Gp.id),g.lD(l.dZ),g.sY(r.cards,l),r.BM(),er(r)},$E=function(r,l,U){if(!r.L){r.lG.show();
r.vQ=new g.F1(function(){g.Pl(r.context.C.getRootNode(),g.OZ.IV_DRAWER_OPEN)},0);
r.vQ.start();r.OF.G(r.X,"mousewheel",function(d){r.rz.start();d.preventDefault();d=d||window.event;var K=0;d.type=="MozMousePixelScroll"?K=0==(d.axis==d.HORIZONTAL_AXIS)?d.detail:0:window.opera?K=d.detail:K=d.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?d.wheelDeltaY/-30:d.wheelDeltaY/-1.2:d.wheelDelta/-1.6:d.wheelDeltaY/-3;if(d=K)r.X.scrollTop+=d});
r.L=!0;var F=g.Bh();F&&r.qh&&r.j&&g.PV(F,[r.qh,r.j]);l={TRIGGER_TYPE:l};for(var Y=g.Q(r.cards),e=Y.next();!e.done;e=Y.next())e=e.value,e.IY||(e.IY=!0,hFC(r.context.logger,e.Gp.X6.sX,l)),F&&g.PV(F,[e.Gp.MN]);Np(r.C);U&&(r.U=new g.F1(function(){r.YN=r.T;r.kq.focus()},330),r.U.start())}},lv=function(r){r.L&&(r.lG.hide(),g.gl(r.OF),g.M0(r.context.C.getRootNode(),g.OZ.IV_DRAWER_OPEN),r.L=!1,Np(r.C),r.U&&r.U.stop(),r.U=new g.F1(function(){r.YN&&(r.YN.focus(),r.YN=null)},330),r.U.start())},nTY=function(r){g.Ab(r.rR(),
[g.OZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Sg(r.C,r.K,5);r.vM();r.T=g.ze("ytp-cards-button",r.C.getRootNode());r.kq=g.ze("iv-drawer-close-button",r.K);r.isInitialized=!0},GNq=function(r){r.kN.push(g.mR("iv-teaser-shown",r.lm,r));
r.kN.push(g.mR("iv-teaser-hidden",r.ym,r));r.kN.push(g.mR("iv-teaser-clicked",r.yy,r));r.Kp=!0},XYq=function(r,l){var U;
return l.onClickCommand&&((U=g.V(l.onClickCommand,g.Y08))==null?void 0:U.targetId)==="engagement-panel-error-corrections"?(r.sF=l,!0):!1},i7Y=function(r,l){r.sF=l;
var U=r.C.getVideoData();if(!U)return!1;U=g.gO(U);if(U==null?0:U.markersMap)for(var F,Y=0;((F=U)==null?void 0:F.markersMap.length)>Y;Y++){var e=void 0,d=(e=U)==null?void 0:e.markersMap[Y];if(d.key==="ERROR_CORRECTION_MARKERS"&&(e=void 0,(d=(e=d.value)==null?void 0:e.markers)&&d.length>0))return F=void 0,l.startMs=((F=g.V(d[0],g.SJm))==null?void 0:F.timeRangeStartMillis)||0,r.sF=null,!0}return!1},FK=function(r,l){if(!XYq(r,l)||i7Y(r,l)){var U=b7j(r,l);
if(U){var F={Gp:l,dZ:U.element,IY:!1};if(l.onClickCommand)r.C.Y("web_infocards_teaser_show_logging_fix")&&(r.Kp||GNq(r),RF$(r,l.id),U=r.findLastIndex(F),g.nr(r.cards,U,0,F));else{r.isInitialized||nTY(r);RF$(r,l.id);var Y=r.findLastIndex(F);g.nr(r.cards,Y,0,F);U.CP(r.X,Y);r.BM()}l.autoOpen?r.addCueRange(l.startMs,0x8000000000000,l.id,function(){r.L||(r.W=F,er(r),NBq(r,F),$E(r,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(U=r.context.C.getCurrentTime()*1E3,U<5E3&&U>l.startMs&&jJb(r,F),r.addCueRange(l.startMs,
l.startMs+1,l.id,function(){jJb(r,F)}),er(r))}}},b7j=function(r,l){switch(l.type){case "simple":r=r.KP;
var U=l.displayDomain?{Z:"div",S:"iv-card-image-text",XT:l.displayDomain}:void 0;var F=PQR(l);U={Z:"div",Dz:["iv-card"],B:[{Z:"a",S:"iv-click-target",J:{href:l.url?tX(l.url)||"":""},B:[aw(l.imageUrl,U),{Z:"div",S:"iv-card-content",B:[ct("h2",void 0,l.title),F]}]}]};U=new g.p(U);Iw(r,g.fR("iv-click-target",U.element),l,l.url);l=U;break;case "collaborator":r=r.KP;U={Z:"div",Dz:["iv-card","iv-card-channel"],B:[{Z:"a",Dz:["iv-click-target"],J:{href:tX(l.url)||"","data-ytid":l.channelId},B:[aw(l.profileImageUrl),
{Z:"div",S:"iv-card-content",B:[JsC(l),{Z:"h2",S:"iv-card-primary-link",XT:l.title},mq0(l)]}]}]};U=new g.p(U);Iw(r,g.fR("iv-click-target",U.element),l,l.url);l=U;break;case "playlist":r=r.KP;U={Z:"div",Dz:["iv-card","iv-card-playlist"],B:[{Z:"a",S:"iv-click-target",J:{href:tX(l.url)||""},B:[aw(l.Ly,{Z:"div",S:"iv-card-image-overlay",B:[{Z:"span",S:"iv-card-playlist-video-count",XT:l.playlistVideoCount}]}),{Z:"div",S:"iv-card-content",B:[JsC(l),ct("h2","iv-card-primary-link",l.title),mq0(l)]}]}]};
U=new g.p(U);Iw(r,g.fR("iv-click-target",U.element),l,l.url);l=U;break;case "productListing":r=r.KP;var Y=l.offers.length!=0;U=["iv-card"];F="";var e=PQR(l);Y&&(U.push("iv-card-product-listing"),F="iv-card-primary-link",e=l.offers[0],Y=[],e.price&&Y.push({Z:"div",S:"iv-card-offer-price",XT:e.price}),e.merchant&&Y.push({Z:"div",S:"iv-card-offer-merchant",XT:e.merchant}),e={Z:"div",B:Y});Y=l.url?tX(l.url)||"":"";U={Z:"div",Dz:U,J:{tabindex:"0"},B:[{Z:"a",Dz:["iv-card-image","iv-click-target"],J:{style:"background-image: url("+
l.imageUrl+");",href:Y,"aria-hidden":"true",tabindex:"-1"}},{Z:"div",S:"iv-card-content",B:[l.sponsored?{Z:"div",S:"iv-card-sponsored",B:["Sponsored",{Z:"div",S:"iv-ad-info-container",B:[{Z:"div",S:"iv-ad-info",XT:"{{adInfo}}"},{Z:"div",S:"iv-ad-info-icon-container",B:[{Z:"div",S:"iv-ad-info-icon"},{Z:"div",S:"iv-ad-info-callout"}]}]}]}:"",{Z:"a",S:"iv-click-target",J:{href:Y},B:[ct("h2",F,l.title),e]}]}]};U=new g.p(U);F=g.I1("span");g.Fk(F,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
U.VZ(F,"adInfo");Iw(r,g.fR("iv-click-target",U.element),l,l.url);l=U;break;case "video":r=r.KP;F=l.videoDuration?{Z:"span",S:"iv-card-video-duration",XT:l.videoDuration}:void 0;e=l.isLiveNow?{Z:"span",Dz:["yt-badge","yt-badge-live"],XT:"LIVE NOW"}:null;Y={Z:"div",Dz:["iv-card","iv-card-video"],B:[{Z:"a",S:"iv-click-target",J:{href:((U=l.url)==null?void 0:tX(U))||""},B:[aw(l.Ly,F),{Z:"div",S:"iv-card-content",B:[JsC(l),ct("h2","iv-card-primary-link",l.title),mq0(l),e]}]}]};U=new g.p(Y);Iw(r,g.fR("iv-click-target",
U.element),l,l.url);l=U;break;default:return null}return l},qbY=function(r){if(r.W)return r.W.Gp.type==="productListing";
if(r.C.Y("enable_wn_infocards")){var l;return!((l=r.cards)==null||!l.length)&&g.II(r.cards,function(U){return U.Gp.type==="productListing"})}return g.II(r.cards,function(U){return U.Gp.type==="productListing"})},er=function(r){g.xl(r.C.getRootNode(),"ytp-cards-shopping-active",qbY(r))},jJb=function(r,l){if(!g.mJ(r.C.getRootNode(),"ytp-cards-teaser-shown")){if(r.W!==l){var U=g.Bh(),F=r.W?r.W.Gp.hf:r.hf;
U&&F&&g.Ac(U,[F]);r.W=l;er(r)}(U=r.isInitialized&&r.rR().style.display=="none")||(U=r.context.C.getPlayerState(),F=U===0&&r.context.C.getCurrentTime()===0,U=!(U===1||U===3||F));if(!U&&l.Gp.teaserDurationMs){var Y;U={teaserText:l.Gp.teaserText,durationMs:l.Gp.teaserDurationMs,onClickCommand:l.Gp.onClickCommand,Xg:(Y=l.Gp.Xg)!=null?Y:null};r.C.D2(!0,U)}r.If.isActive()||((!r.L||!r.rz.isActive()&&r.iG)&&NBq(r,l),r.If.start(910+l.Gp.teaserDurationMs))}},NBq=function(r,l){r.V.H5?(l=new yj([0,
r.X.scrollTop],[0,l.dZ.offsetTop],600,gyG),r.context.L.listen(l,"animate",function(U){r.X.scrollTop=U.y}),r.context.L.listen(l,"finish",function(U){r.X.scrollTop=U.y}),l.play()):(r.V.zf(!0),r.X.scrollTop=l.dZ.offsetTop,r.V.zf(!1))},d9=function(r){return r.W&&r.W.Gp?r.W.Gp:r.cards[0]&&r.cards[0].Gp?r.cards[0].Gp:null},Z78=function(r,l){return g.m8(r.cards,function(U){return U.Gp.id===l})},Ol=function(r,l,U){k5.call(this,r,l);
this.annotation=U;this.isActive=!1},TBC=function(r){var l=r.annotation.data;
"start_ms"in l&&"end_ms"in l&&r.addCueRange(Number(l.start_ms),Number(l.end_ms),r.annotation.id,function(){r.show()},function(){r.hide()})},KE=function(r,l,U){Ol.call(this,r,l,U);
this.X=null;this.j=!1;this.L=null;this.K=!1;this.W=this.D=this.U=null},uhq=function(r,l){var U=U===void 0?0:U;
var F=ba8(l).width;g.bD(l,F);U=new BDC(l,[F,l.offsetTop],[F-F-U,l.offsetTop],200,HaC);g.w(r,U);r.context.L.listen(U,"begin",function(){g.yg(l,!0)});
U.play()},H7C=function(r,l){if(l.channel_name){var U=r.createElement({Z:"div",
Dz:["iv-branding-context-name"],XT:l.channel_name}),F=r.createElement({Z:"div",Dz:["iv-branding-context-subscribe"]}),Y=l.standalone_subscribe_button_data;Y&&(r.W=new g.lX(Y.subscribeText,Y.subscribeCount,Y.unsubscribeText,Y.unsubscribeCount,!!Y.enabled,!!Y.classic,l.channel_id,!!Y.subscribed,Y.feature,l.session_data.itct,r.context.C,!1),r.W.CP(F));var e=r.createElement({Z:"div",Dz:["iv-branding-context-subscribe-caret"]}),d=r.createElement({Z:"div",Dz:["branding-context-container-inner"]});d.appendChild(e);
d.appendChild(U);d.appendChild(F);g.yg(d,!1);var K=r.createElement({Z:"div",Dz:["branding-context-container-outer"]});K.appendChild(d);g.RI(K,"right",l.image_width+"px");g.oI(r.rR(),K);r.L=new g.F1(function(){ysC(r,d,K)},500);
g.w(r,r.L);r.context.W.listen(r.rR(),"mouseover",function(){BBr(r,d,K,e,l.image_height)});
r.context.W.listen(r.rR(),"mouseout",function(){r.L.start()})}},BBr=function(r,l,U,F,Y){r.L.stop();
if(!r.K){var e=g.uD(l);r.W||(l.style.width=g.iD(e.width,!0),U.style.width=g.iD(e.width,!0));g.RI(F,"top",e.height-Math.max(Math.min(e.height,Y)/2+10,20)+"px");g.RI(F,"right","1px");r.K=!0;g.yg(l,!0);r.U=new g.F1(function(){g.Pl(this.rR(),"iv-branding-active")},0,r);
r.U.start()}},ysC=function(r,l,U){g.M0(r.rR(),"iv-branding-active");
r.D=new g.F1(function(){g.yg(l,!1);r.W||(U.style.width=g.iD(0,!0))},250);
r.D.start();r.K=!1},gTY=function(r,l,U,F,Y,e,d){this.W=r;
this.L=l;this.WQ=U;this.videoData=F;this.logger=Y;this.C=e;this.X=d},wYb=function(r,l,U){Ol.call(this,r,l,U);
var F=this;this.T=this.isCollapsed=this.V=!1;this.D=5E3;this.X=this.L=this.W=this.K=null;this.j=this.createElement({Z:"div",Dz:["iv-promo-contents"]});this.U=new g.F1(function(){F.W.setAttribute("aria-hidden","true");g.yg(F.L,!1);g.yg(F.X,!0)},700,this);
g.w(this,this.U)},VKR=function(r){var l=r.annotation.data;
if(r.annotation.style==="cta")var U=6;else if(r.annotation.style==="video"||r.annotation.style==="playlist")U=7;r.D=l.collapsedelay_ms||r.D;var F=["iv-promo","iv-promo-inactive"];r.rR().setAttribute("aria-hidden","true");r.rR().setAttribute("aria-label","Promotion");r.rR().tabIndex=0;var Y=r.annotation.O4(),e=l.image_url;if(e){var d=r.createElement({Z:"div",Dz:["iv-promo-img","iv-click-target"]});e=r.createElement({Z:"img",J:{src:e,"aria-hidden":"true"}});d.appendChild(e);l.video_duration&&!l.is_live?
(e=r.createElement({Z:"span",S:"iv-promo-video-duration",XT:l.video_duration}),d.appendChild(e)):l.playlist_length&&(e=r.createElement({Z:"span",S:"iv-promo-playlist-length",XT:l.playlist_length.toString()}),d.appendChild(e));Y&&oy(r,d,Y,r.annotation.id,l.session_data,void 0,U)}Y?(e=r.createElement({Z:"a",S:"iv-promo-txt"}),g.ci(e,tX(Y)),r.W=e):r.W=r.createElement({Z:"div",S:"iv-promo-txt"});switch(r.annotation.style){case "cta":case "website":var K=r.createElement({Z:"p",B:[{Z:"strong",XT:l.text_line_1}]});
var C=r.createElement({Z:"p",B:[{Z:"span",S:"iv-promo-link",XT:l.text_line_2}]});if(e=l.text_line_3){F.push("iv-promo-website-card-cta-redesign");var v=r.createElement({Z:"button",Dz:["iv-promo-round-expand-icon","ytp-button"]});e=r.createElement({Z:"button",Dz:["iv-button","iv-promo-button"],B:[{Z:"span",S:"iv-button-content",XT:e}]});var J=r.createElement({Z:"div",S:"iv-promo-button-container"});J.appendChild(e);Y&&oy(r,r.rR(),Y,r.annotation.id,l.session_data,void 0,U)}g.Pl(r.W,"iv-click-target");
Y&&oy(r,r.W,Y,r.annotation.id,l.session_data,void 0,U);break;case "playlist":case "video":K=r.createElement({Z:"p",B:[{Z:"span",XT:l.text_line_1}]}),C=r.createElement({Z:"p",B:[{Z:"strong",XT:l.text_line_2}]}),l.is_live&&(K=C,C=r.createElement({Z:"span",Dz:["yt-badge","iv-promo-badge-live"],XT:"LIVE NOW"})),g.Pl(r.W,"iv-click-target"),Y&&oy(r,r.W,Y,r.annotation.id,l.session_data,void 0,U),F.push("iv-promo-video")}K&&r.W.appendChild(K);C&&r.W.appendChild(C);r.j.appendChild(r.W);J&&r.j.appendChild(J);
U=r.createElement({Z:"div",S:"iv-promo-actions"});r.X=r.createElement({Z:"button",Dz:["iv-promo-expand","ytp-button"]});r.X.title="Expand";r.context.W.listen(r.X,"click",function(m){DqY(r,5E3,m)});
U.appendChild(r.X);g.yg(r.X,!1);r.context.W.listen(r.rR(),"mouseover",r.xe,r);r.context.W.listen(r.rR(),"mouseout",r.i5,r);r.context.W.listen(r.rR(),"touchend",function(m){DqY(r,5E3,m)});
r.L=r.createElement({Z:"button",Dz:["iv-promo-close","ytp-button"]});r.L.title="Close";r.context.W.listen(r.L,"click",r.annotation.style==="cta"&&l.text_line_3?r.qx:r.rp,r);U.appendChild(r.L);g.Ab(r.rR(),F);d&&(g.oI(r.rR(),d),v&&d.appendChild(v));g.oI(r.rR(),r.j);g.oI(r.rR(),U)},DqY=function(r,l,U){U.stopPropagation();
fbY(r);SbG(r,l);r.W.focus()},zFf=function(r){r.isCollapsed||r.T||r.K||(g.Pl(r.rR(),"iv-promo-collapsed"),r.isCollapsed=!0,r.U.start())},fbY=function(r){r.U.stop();
r.isCollapsed&&(g.sS(r.rR(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),r.isCollapsed=!1,r.W&&r.W.removeAttribute("aria-hidden"),g.yg(r.X,!1),g.yg(r.L,!0))},SbG=function(r,l){r.K||(r.K=g.SH(function(){pYb(this);
zFf(this)},l,r))},pYb=function(r){r.K&&(g.pP.clearTimeout(r.K),r.K=null)},tK$=function(r){this.C=r},hFC=function(r,l,U){l&&(U?CE(r,l.map(function(F){return g.wc(F,U)})):CE(r,l))},CE=function(r,l,U,F){var Y=1,e=void 0,d=-1;
if(U){var K=!1;e=function(){Y--;Y||K||(clearTimeout(d),K=!0,U())};
d=setTimeout(function(){K=!0;U()},1E3)}l=g.Q(l||[]);
for(var C=l.next();!C.done;C=l.next())C=C.value,Y++,g.cg(C,e);F&&(Y++,F!==0&&r.C.sendVideoStatsEngageEvent(F,e))},LSG=function(r){g.Rf.call(this,r);
var l=this;this.kN=this.T=!1;this.loadNumber=0;this.D={};this.logger=new tK$(this.player);this.K=new g.Lg(this);this.U=this.j=null;this.events=new g.Lg(this);this.Fs=this.V=this.W=null;this.sF=[];g.w(this,this.K);this.K.G(this.player,"onVideoAreaChange",function(){l.publish("onVideoAreaChange")});
this.K.G(this.player,"onHideControls",function(){l.publish("onHideControls")});
this.K.G(this.player,"onShowControls",function(){l.publish("onShowControls")});
this.K.G(this.player,"resize",function(F){l.publish("resize",F)});
this.K.G(this.player,"presentingplayerstatechange",function(F){l.publish("presentingplayerstatechange",F)});
this.subscribe("presentingplayerstatechange",this.tP,this);this.subscribe("resize",this.hC,this);this.player.N().iG.subscribe("vast_info_card_add",this.KN,this);g.w(this,this.events);this.KP=this.createElement({Z:"div",S:"video-custom-annotations"});this.X=new g.p({Z:"div",Dz:["ytp-player-content","ytp-iv-player-content"]});g.w(this,this.X);g.Sg(this.player,this.X.element,4);this.X.hide();this.L=new g.p({Z:"div",Dz:["ytp-iv-video-content"]});g.w(this,this.L);r=this.createElement({Z:"div",S:"video-annotations"});
r.appendChild(this.KP);this.L.element.appendChild(r);this.J7()&&this.load();var U=this.createElement({Z:"style"});(g.Vp("HEAD")[0]||document.body).appendChild(U);this.addOnDisposeCallback(function(){g.lD(U)});
if(r=U.sheet)r.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),r.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),r.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),r.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),r.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),r.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),r.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),r.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},csR=function(r){r=r.createElement({Z:"div",
Dz:["annotation","annotation-type-custom"]});g.yg(r,!1);return r},ab8=function(r,l){l=!l.isCued()&&!g.c(l,1024);
r.X.zf(l);r.L.zf(l)},Ibr=function(r,l,U){r.T=!0;
r.U=g.Tj(l,U)},kNC=function(r,l){for(var U={},F=g.Q(l.attributes),Y=F.next();!Y.done;Y=F.next())Y=Y.value,U[Y.name]=Y.nodeValue;
for(F=0;F<l.childNodes.length;F++)if(Y=l.childNodes[F],g.oY(Y)&&Y.nodeType==1){if(U[Y.tagName])var e=U[Y.tagName];else if(Y.tagName==="data"){Y.childNodes.length>0&&(e=Y.childNodes[0].nodeValue,U[Y.tagName]=typeof e==="string"?e.trim():e);continue}else e=[],U[Y.tagName]=e;Y&&Y.tagName==="TEXT"?Y.childNodes.length===1&&Y.childNodes[0].nodeType===3?e.push(Y.childNodes[0].nodeValue):e.push(""):Y&&e.push(kNC(r,Y))}return U},lAr=function(r){var l=r.player.getVideoData();
if(l.OF){var U=r.player.N().iG.get(l.videoId);if(U){var F={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(Y,e,d){Y=r.loadNumber;e=l.videoId;r.loaded&&r.loadNumber===Y&&r.player.getVideoData().videoId===e&&(d=g.Zi(d)&&d.responseXML?d.responseXML:null)&&oPC(r,d)}};
g.Cp()&&(F.onFinish=r_C(r,F.onFinish));F.postParams={ic_only:"1"};$K0(F,U);r.T=!0;g.Tj(l.OF,F)}}},$K0=function(r,l){r.method="POST";
r.postParams=r.postParams||{};l.HX&&(r.postParams.ic_coll=l.HX);l.rZ&&(r.postParams.ic_xml=l.rZ);l.r7&&(r.postParams.ic_track=l.r7)},UKC=function(r){var l=new g.p({Z:"div"});
g.yg(l.element,!1);var U=new WSY(r.player,l.element,vH(r));g.w(U,l);l.CP(r.X.element);U.zm();return U},Y$Y=function(r,l){var U,F;
if(l=(U=l.getWatchNextResponse())==null?void 0:(F=U.cards)==null?void 0:F.cardCollectionRenderer)r.kN=!0,F98(r,l),l.headerText&&r.Fs&&(U=g.Xv(l.headerText),r.Fs.setAttribute("title",U))},vH=function(r){if(!r.V){var l=new wvq(r);
g.w(r,l);var U=new g.RN(r);g.w(r,U);r.V=new gTY(l,U,r.player.N(),r.player.getVideoData(),r.logger,r.player,r.ZF)}return r.V},oPC=function(r,l){var U=!1,F=l.getElementsByTagName("annotations");
if(F&&!(F.length<1)&&(F=F[0].getAttribute("itct"))){var Y=g.Bh();if(Y){var e=g.y$();e&&g.e7(g.UI)(void 0,Y,e,[g.Tz(F)])}}l=l.getElementsByTagName("annotation");for(F=0;F<l.length;F++){e=kNC(r,l[F]);Y=null;try{if(e){var d=e.id,K=/.+/;var C=typeof d==="string"&&K!=null&&d!=null&&d.match(K)?d:"";var v=pc(e.type,eBr),J=pc(e.style,dKp),m=lb8(e.data),P=m.length!==0?JSON.parse(m):{};var A=e.action;e=O7G;if(A==null)var M=null;else if(g.k$(A)){K=[];for(var E=g.Q(A),Z=E.next();!Z.done;Z=E.next()){var n=e(Z.value);
n&&K.push(n)}M=K}else{var h=e(A);M=h?[h]:[]}Y=C&&v?new KSG(C,v,J,M,P):null}else Y=null}catch(I){}if(Y)if(Y.type==="branding"||Y.type==="promotion"){e=r;K=Y;var N=csR(e),u=null;switch(K.type){case "branding":if(e.player.N().LJ)break;e.X.element.appendChild(N);u=new KE(N,vH(e),K);break;case "promotion":g.Sg(e.player,N,4),u=new wYb(N,vH(e),K)}u&&u.zm();if(e=u)g.w(r,e),r.D[Y.id]=e}else if(Y.type==="card"||Y.type==="drawer"){r.W||(r.W=UKC(r),g.w(r,r.W));if(Y.type==="card"){N=r.W;var D=(U=Y)&&U.data&&U.data.card_type;
Y=U.data;if(D)switch(e=Y.tracking||{},e={sX:e.impression,click:e.click,close:e.close,nF:e.teaser_impression,Qb:e.teaser_click},K=Y.tracking_params||{},u=null,D){case "collaborator":U={id:U.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,X6:e,MN:K.card?g.Tz(K.card):null,Nb:K.teaser?g.Tz(K.teaser):null,hf:K.icon?g.Tz(K.icon):null,channelId:Y.channel_id,
customMessage:Y.custom_message?Y.custom_message:null,profileImageUrl:Y.image_url,title:Y.title,metaInfo:Y.meta_info,url:Lc({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};FK(N,U);break;case "playlist":U={id:U.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,X6:e,MN:K.card?g.Tz(K.card):null,
Nb:K.teaser?g.Tz(K.teaser):null,hf:K.icon?g.Tz(K.icon):null,Ly:Y.image_url,playlistVideoCount:Y.playlist_video_count,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,url:Lc({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};FK(N,U);break;case "productListing":Y.signin_url&&(u=Lc({target:"current",value:Y.signin_url}));D=[];for(var t=Y.offers||[],z=0;z<t.length;z++)D.push(new As8(g.Ms(t[z].merchant),g.Ms(t[z].price)));
U={id:U.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,X6:e,MN:K.card?g.Tz(K.card):null,Nb:K.teaser?g.Tz(K.teaser):null,hf:K.icon?g.Tz(K.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:null,showLinkIcon:!!Y.show_link_icon,Qs:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?
Y.custom_message:null,url:Lc({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),Jnu:u,o7T:Y.signin_title?Y.signin_title:void 0,zhw:Y.signin_message?Y.signin_message:void 0,offers:D,onClickCommand:null};FK(N,U);break;case "simple":U={id:U.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,X6:e,MN:K.card?g.Tz(K.card):
null,Nb:K.teaser?g.Tz(K.teaser):null,hf:K.icon?g.Tz(K.icon):null,imageUrl:Y.image_url,displayDomain:Y.display_domain?Y.display_domain:null,showLinkIcon:!!Y.show_link_icon,Qs:Y.button_icon_url?Y.button_icon_url:null,title:Y.title,customMessage:Y.custom_message?Y.custom_message:null,url:Lc({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null};FK(N,U);break;case "video":U={id:U.id,timestamp:Y.timestamp||0,type:Y.card_type,teaserText:Y.teaser_text,teaserDurationMs:Y.teaser_duration_ms,
startMs:Y.start_ms,autoOpen:Y.auto_open||!1,sessionData:Y.session_data||{},sponsored:Y.sponsored||!1,X6:e,MN:K.card?g.Tz(K.card):null,Nb:K.teaser?g.Tz(K.teaser):null,hf:K.icon?g.Tz(K.icon):null,Ly:Y.image_url,videoDuration:Y.video_duration||null,customMessage:Y.custom_message?Y.custom_message:null,title:Y.title,metaInfo:Y.meta_info,isLiveNow:!!Y.is_live_now,url:Lc({pause_on_navigation:Y.pause_on_navigation,target:Y.target||"new",value:Y.url}),onClickCommand:null},FK(N,U)}}else QJY(r.W,Y);U=!0}}U&&
(Np(r.player),r.hC())},F98=function(r,l){var U=!1;
r.W||(r.W=UKC(r),g.w(r,r.W));for(var F=g.Q(l.cards||[]),Y=F.next();!Y.done;Y=F.next())Y=Y.value,Y.cardRenderer&&(ETC(r.W,Y.cardRenderer),U=!0);if(U){var e;(e=r.player.getVideoData())!=null&&g.fk(e)||(U=r.W,F=l.headerText?g.Xv(l.headerText):"",g.Fk(U.Rg,F),U.T&&U.T.setAttribute("title",F),U.context.videoData.eventId&&(U.eventId=U.context.videoData.eventId),U.qh=l.trackingParams?g.Tz(l.trackingParams):null,U.j=l.closeButton.infoCardIconRenderer.trackingParams?g.Tz(l.closeButton.infoCardIconRenderer.trackingParams):
null,U.hf=l.icon.infoCardIconRenderer.trackingParams?g.Tz(l.icon.infoCardIconRenderer.trackingParams):null,r.hC());Np(r.player)}},OX0=function(r,l,U,F,Y){if(!r.player.N().LJ){var e=[];
l.navigationEndpoint&&g.V(l.navigationEndpoint,g.yw)&&g.V(l.navigationEndpoint,g.yw).browseId&&e.push(new Yb0("openUrl","click",new Uqf("/channel/"+g.V(l.navigationEndpoint,g.yw).browseId,"new",!0,!0)));var d=l.watermark.thumbnails[0];F={channel_name:l.channelName,end_ms:l.endTimeMs,image_height:d.height,image_type:1,image_url:d.url,image_width:d.width,is_mobile:!1,session_data:{annotation_id:U,ei:Y,feature:"iv",itct:l.trackingParams,src_vid:F},start_ms:l.startTimeMs};if(l.subscribeButton&&g.V(l.subscribeButton,
g.BZ)){F.channel_id=g.V(l.subscribeButton,g.BZ).channelId;var K;l=g.V(l.subscribeButton,g.BZ);d=Y=null;l.subscribed?(l.subscriberCountWithUnsubscribeText&&(Y=g.Xv(l.subscriberCountWithUnsubscribeText)),l.subscriberCountText&&(d=g.Xv(l.subscriberCountText))):(l.subscriberCountText&&(Y=g.Xv(l.subscriberCountText)),l.subscriberCountWithSubscribeText&&(d=g.Xv(l.subscriberCountWithSubscribeText)));var C,v=((C=g.V((K=l.signInEndpoint)==null?void 0:K.commandMetadata,g.hq))==null?void 0:C.url)||"";K={subscribeText:g.Xv(l.unsubscribedButtonText),
subscribeCount:Y||"",unsubscribeText:g.Xv(l.subscribedButtonText),unsubscribeCount:d||"",enabled:l.enabled||!1,classic:!1,subscribed:l.subscribed||!1,feature:"iv",signInUrl:v};F.standalone_subscribe_button_data=K}e=new KSG(U,"branding","branding",e,F);K=csR(r);r.X.element.appendChild(K);e=new KE(K,vH(r),e);e.zm();g.w(e,e);r.D[U]=e}},r_C=function(r,l){return function(){var U=g.uz.apply(0,arguments);
r.QT()||r.sF.push(g.cs.fH(function(){l.apply(null,g.G(U))}))}},K9R=function(r){return r==="annotation-editor"||r==="live-dashboard"};
g.yy.prototype.D2=g.FL(39,function(r,l){var U=g.yl(this.FL());U&&U.D2(r,l)});
var qp={},TB=null;g.OY(yj,g.Wl);g.x=yj.prototype;g.x.getDuration=function(){return this.duration};
g.x.play=function(r){if(r||this.W==0)this.progress=0,this.coords=this.X;else if(this.isPlaying())return!1;uL(this);this.startTime=r=g.Y0();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.K=this.startTime;this.progress||this.GZ();this.CT("play");this.isPaused()&&this.CT("resume");this.W=1;var l=g.lC(this);l in qp||(qp[l]=this);q6C();TDG(this,r);return!0};
g.x.stop=function(r){uL(this);this.W=0;r&&(this.progress=1);uF0(this,this.progress);this.onStop();this.RJ()};
g.x.pause=function(){this.isPlaying()&&(uL(this),this.W=-1,this.CT("pause"))};
g.x.Rf=function(){this.W==0||this.stop(!1);this.CT("destroy");yj.Xe.Rf.call(this)};
g.x.destroy=function(){this.dispose()};
g.x.m8=function(){this.CT("animate")};
g.x.CT=function(r){this.dispatchEvent(new yE0(r,this))};
g.OY(yE0,g.lM);g.OY(Bt,yj);Bt.prototype.L=function(){};
Bt.prototype.m8=function(){this.L();Bt.Xe.m8.call(this)};
Bt.prototype.RJ=function(){this.L();Bt.Xe.RJ.call(this)};
Bt.prototype.GZ=function(){this.L();Bt.Xe.GZ.call(this)};
g.OY(BDC,Bt);BDC.prototype.L=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.W(wvq,g.H);g.x=wvq.prototype;g.x.listen=function(r,l,U,F){U=(0,g.UY)(U,F||this.X);r=g.NO(r,l,U);this.W.push(r);return r};
g.x.Fx=function(r,l,U,F){U=(0,g.UY)(U,F||this.X);r=ND8(r,l,U);this.W.push(r);return r};
g.x.ev=function(r){g.jX(r);g.sY(this.W,r)};
g.x.removeAll=function(){g.jX(this.W);this.W.length=0};
g.x.Rf=function(){this.removeAll();g.H.prototype.Rf.call(this)};g.W(f40,g.Rf);g.x=f40.prototype;g.x.load=function(){g.Rf.prototype.load.call(this);if(!we(this)){var r=g.bVf(this.player.getVideoData());r?(r=Vjr(r,S68(this)),DE(this,r,!1)):zqY(this)}};
g.x.unload=function(){DE(this,null);this.K&&(this.K.abort(),this.K=null);g.Rf.prototype.unload.call(this)};
g.x.hj=function(r,l){return we(this)?r==="loadCustomEndscreenRenderer"?(r=Vjr(l,"new"),DE(this,r),!0):null:null};
g.x.getOptions=function(){return we(this)?["loadCustomEndscreenRenderer"]:[]};
g.x.hB=function(){if(this.endscreen&&this.endscreen.elements){var r=this.player.getVideoContentRect();if(r&&r.width!==0&&r.height!==0){var l=this.player.getPlayerSize();if(l&&l.width!==0&&l.height!==0){var U=r.width/r.height;var F=0;for(var Y=-1,e=0;e<C1b.length;e++){var d=Math.abs(l.width-C1b[e]);if(Y===-1||F>=d)Y=e,F=d}F=vPC[Y];this.L&&g.RI(this.L.element,"outline-width",Math.max(l.width,l.height)+"px");for(l=0;l<this.endscreen.elements.length;++l)if(e=this.endscreen.elements[l].id,Y=this.X[e],
d=this.D[e],Y&&d){var K=d.width*U/d.aspectRatio,C=Math.round(d.width*r.width);e=Math.round(K*r.height);var v=r.left+Math.round(d.left*r.width),J=r.top+Math.round(d.top*r.height);g.TC(Y.element,C,e);g.bD(Y.element,v,J);g.sS(Y.element,J_0);C>256||e>256?g.Pl(Y.element,"ytp-ce-large-round"):C>96||e>96?g.Pl(Y.element,"ytp-ce-medium-round"):g.Pl(Y.element,"ytp-ce-small-round");g.sS(Y.element,mK$);C=d.left+d.width/2;d=d.top+K/2;g.Pl(Y.element,C<=.5&&d<=.5?"ytp-ce-top-left-quad":C>.5&&d<=.5?"ytp-ce-top-right-quad":
C<=.5&&d>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sS(Y.element,vPC);g.Pl(Y.element,F);(Y=g.St(document,"div","ytp-ce-expanding-overlay-body",Y.element)[0])&&g.RI(Y,"height",e+"px")}}}}};
g.x.onCueRangeEnter=function(r){if(this.endscreen)if(r.getId()==="ytp-ce-in-endscreen")zB(this,this.endscreen.impressionUrls),(r=g.Bh())&&this.endscreen.visualElement&&g.mf(r,this.endscreen.visualElement),this.W&&(g.Pl(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.mf()?g.Pl(this.W,"ytp-ce-hide-button-lower"):g.M0(this.W,"ytp-ce-hide-button-lower"));else{r=r.getId().substring(15);var l=this.X[r],U=this.D[r];g.Pl(l.element,"ytp-ce-element-show");l.element.removeAttribute("aria-hidden");
l=this.player.getRootNode();g.Pl(l,"ytp-ce-shown");zB(this,U.impressionUrls);(l=g.Bh())&&g.mf(l,U.visualElement);this.player.N().T&&this.player.PQ("endscreenelementshown",r)}};
g.x.onCueRangeExit=function(r){if(r.getId()==="ytp-ce-in-endscreen")this.W&&(g.M0(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{r=r.getId().substring(15);var l=this.X[r];g.M0(l.element,"ytp-ce-element-show");l.element.setAttribute("aria-hidden","true");l=this.player.getRootNode();g.M0(l,"ytp-ce-shown");this.player.N().T&&this.player.PQ("endscreenelementhidden",r)}};
g.x.CJw=function(r){var l=this;r.target===window&&(new g.F1(function(){for(var U=g.Q(Object.values(l.X)),F=U.next();!F.done;F=U.next())g.sS(F.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.x.zf=function(r){for(var l=g.Q(Object.values(this.X)),U=l.next();!U.done;U=l.next())U=U.value,r?U.element.setAttribute("hidden",""):U.element.removeAttribute("hidden")};
g.x.EaP=function(r){this.W&&this.player.getRootNode().removeChild(this.W);r&&(g.Pl(r,"ytp-ce-hide-button-container"),this.W=r,g.Sg(this.player,this.W,4))};
var C1b=[346,426,470,506,570,640,853,1280,1920],vPC="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),mK$=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],J_0=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var FS0={yFQ:"current",qkz:"new"};var eF8={CLOSE:"close",Q2w:"openUrl",SUBSCRIBE:"subscribe"},dqr={iHw:"click",CLOSE:"close",cKH:"hidden",KwF:"rollOut",ZKQ:"rollOver",QDu:"shown"};KSG.prototype.O4=function(){var r=CQY(this,function(l){return l.type==="openUrl"&&l.url!=null});
return r?r.url:null};
var dKp={M2u:"anchored",w9:"branding",CHANNEL:"channel",fFh:"cta",znP:"highlightText",Mrh:"label",PLAYLIST:"playlist",POPUP:"popup",v3w:"speech",SUBSCRIBE:"subscribe",zBP:"title",VIDEO:"video",agN:"website"},eBr={w9:"branding",Lou:"card",Vsf:"drawer",NGF:"highlight",IJc:"marker",ofu:"promotion",TEXT:"text",kvH:"widget"};g.W(k5,g.H);g.x=k5.prototype;g.x.addCueRange=function(r,l,U,F,Y){r=new g.M2(r,l,{id:U,namespace:"annotations_module"});F&&this.yT.set(r,F);Y&&this.Nh.set(r,Y);this.context.C.sN([r],1)};
g.x.zm=function(){this.context.X.subscribe("resize",this.BM,this)};
g.x.rR=function(){return this.element};
g.x.Wp=function(r,l,U,F,Y,e){if(this.W5)return!1;e&&(e.stopPropagation(),e.preventDefault());this.navigate(r,U,F,Y);return!1};
g.x.show=function(){};
g.x.hide=function(){};
g.x.destroy=function(){g.lD(this.rR())};
g.x.BM=function(){};
g.x.navigate=function(r,l,U,F){var Y=this,e=tX(r);if(e){var d=sJq(e,r.target),K=function(){r.W&&Y.context.C.pauseVideo();var C=Y.context.videoData.f0||!1,v=g.JZ(e||"");C&&v&&(v.v||v.list)?Y.context.C.zI(v.v,l,v.list,!1):g.UO(e||"",d==="current"?"_top":void 0,l)};
d==="new"&&(K(),K=null);CE(this.context.logger,U,K,F);MKC(e)||(U=g.Bh(),F=l.itct,U&&F&&g.MP(U,g.Tz(F)))}};
g.x.Rf=function(){this.yT.clear();this.Nh.clear();g.H.prototype.Rf.call(this)};
g.x.createElement=function(r){r=new g.p(r);g.w(this,r);return r.element};g.W(WSY,k5);g.x=WSY.prototype;g.x.wJ=function(){this.sF&&FK(this,this.sF)};
g.x.isAvailable=function(){var r;if(r=!!this.cards.length)(r=this.C.getRootNode())?(r=g.uD(r),r=173<r.width&&173<r.height):r=!1;return r};
g.x.BM=function(){var r=this.isAvailable();g.yg(this.rR(),r);g.xl(this.context.C.getRootNode(),g.OZ.IV_DRAWER_ENABLED,r);Np(this.C)};
g.x.destroy=function(){this.C.D2(!1);try{this.C.getRootNode().removeChild(this.K)}catch(r){}g.P6(this.kN);g.gl(this.OF);this.vQ&&this.vQ.dispose();this.U&&this.U.dispose();k5.prototype.destroy.call(this)};
g.x.vM=function(){var r=this;this.context.W.listen(g.ze("iv-drawer-close-button",this.K),"click",this.ZM,this);this.context.W.listen(this.X,"touchend",function(){r.rz.start()});
this.context.W.listen(this.X,"scroll",this.Ea,this);this.context.X.subscribe("onHideControls",function(){r.iG=!0});
this.context.X.subscribe("onShowControls",function(){r.iG=!1});
this.context.X.subscribe("onVideoAreaChange",function(){r.iG=g.mJ(r.C.getRootNode(),"ytp-autohide")});
this.kN.push(g.mR("iv-button-shown",this.E0,this));this.kN.push(g.mR("iv-button-hidden",this.Tq,this));GNq(this)};
g.x.findLastIndex=function(r){if(this.cards.length===0)return 0;var l=g.Pb(this.cards,function(U){return r.Gp.startMs>U.Gp.startMs||r.Gp.startMs===U.Gp.startMs&&r.Gp.timestamp>=U.Gp.timestamp?!0:!1});
return l===-1?0:l+1};
g.x.ZM=function(){if(this.L){CE(this.context.logger,d9(this).X6.close);var r=g.Bh();r&&this.j&&g.MP(r,this.j);lv(this)}};
g.x.Ea=function(){g.xl(this.K,"iv-drawer-scrolled",this.X.scrollTop>0)};
g.x.E0=function(){var r=g.Bh(),l=d9(this);l=l?l.hf:this.hf;r&&l&&g.PV(r,[l])};
g.x.Tq=function(){var r=g.Bh(),l=d9(this);l=l?l.hf:this.hf;r&&l&&g.Ac(r,[l])};
g.x.lm=function(){var r=d9(this);CE(this.context.logger,r.X6.nF);var l=g.Bh();if(l&&r)if(this.C.Y("web_infocards_teaser_show_logging_fix")){var U=[];r.Nb&&U.push(r.Nb);r.hf&&U.push(r.hf);U.length>0&&g.PV(l,U)}else g.PV(l,[r.Nb,r.hf])};
g.x.ym=function(){var r=g.Bh(),l=d9(this);r&&l&&g.Ac(r,[l.Nb])};
g.x.yy=function(r){var l=d9(this),U=g.Bh();this.W?r?(r=this.context.logger,CE(r,l.X6.Qb),r.C.sendVideoStatsEngageEvent(4,void 0),U&&l.Nb&&g.MP(U,l.Nb)):(r=this.context.logger,CE(r,l.X6.Qb),r.C.sendVideoStatsEngageEvent(4,void 0),U&&l.hf&&g.MP(U,l.hf)):(r=this.context.logger,CE(r,l.X6.Qb),r.C.sendVideoStatsEngageEvent(4,void 0),U&&this.hf&&g.MP(U,this.hf))};g.W(Ol,k5);Ol.prototype.zm=function(){k5.prototype.zm.call(this);TBC(this)};
Ol.prototype.show=function(){k5.prototype.show.call(this);var r=g.Bh(),l=this.annotation.data;r&&l&&(l=l.session_data)&&g.PV(r,[g.Tz(l.itct)])};
Ol.prototype.hide=function(){k5.prototype.hide.call(this);var r=g.Bh(),l=this.annotation.data;r&&l&&(l=l.session_data)&&g.Ac(r,[g.Tz(l.itct)])};g.W(KE,Ol);
KE.prototype.show=function(){if(!this.isActive){Ol.prototype.show.call(this);if(!this.j){g.Pl(this.rR(),"iv-branding");var r=this.annotation.data;this.X=this.createElement({Z:"img",Dz:["branding-img","iv-click-target"],J:{"aria-label":"Channel watermark",src:r.image_url,width:r.image_width,height:r.image_height}});g.yg(this.X,!1);var l=this.createElement({Z:"button",Dz:["branding-img-container","ytp-button"]});l.appendChild(this.X);this.rR().appendChild(l);var U=this.annotation.O4();U&&oy(this,l,
U,this.annotation.id,r.session_data);this.context.C.Y("disable_branding_context")||H7C(this,r);this.j=!0}g.yg(this.rR(),!0);this.isActive=!0;if(this.X){try{uhq(this,this.X)}catch(F){}g.Pl(this.context.C.getRootNode(),"ytp-branding-shown");this.context.C.getRootNode().style.setProperty("--branding-image-width",this.X.getAttribute("width")+"px")}}};
KE.prototype.hide=function(){this.isActive&&(Ol.prototype.hide.call(this),g.yg(this.rR(),!1),this.isActive=!1,g.M0(this.context.C.getRootNode(),"ytp-branding-shown"))};
KE.prototype.destroy=function(){this.W&&(this.W.dispose(),this.W=null);g.M0(this.context.C.getRootNode(),"ytp-branding-shown");Ol.prototype.destroy.call(this)};g.W(wYb,Ol);g.x=wYb.prototype;g.x.show=function(){this.isActive||(Ol.prototype.show.call(this),this.V||(VKR(this),this.V=!0),g.yg(this.rR(),!0),g.SH(function(){g.M0(this.rR(),"iv-promo-inactive")},100,this),this.rR().removeAttribute("aria-hidden"),this.isActive=!0,pYb(this),fbY(this),SbG(this,this.D))};
g.x.hide=function(){this.isActive&&(g.Pl(this.rR(),"iv-promo-inactive"),this.isActive=!1,this.rR().setAttribute("aria-hidden","true"))};
g.x.Wp=function(r,l,U,F,Y,e){return this.isCollapsed?!1:Ol.prototype.Wp.call(this,r,l,U,F,Y,e)};
g.x.xe=function(r){this.T=!0;DqY(this,500,r)};
g.x.i5=function(){this.T=!1;zFf(this)};
g.x.rp=function(r){r.stopPropagation();this.hide()};
g.x.qx=function(r){r.stopPropagation();pYb(this);this.isCollapsed=!0;g.Pl(this.rR(),"iv-promo-collapsed-no-delay");this.U.start()};
g.x.destroy=function(){this.U.dispose();Ol.prototype.destroy.call(this)};g.W(LSG,g.Rf);g.x=LSG.prototype;g.x.hj=function(r,l){if(!K9R(this.player.N().playerStyle))return null;switch(r){case "loadCustomAnnotationsXml":return(r=g.o6(l))&&oPC(this,r),!0;case "removeCustomAnnotationById":return l&&this.W&&(RF$(this.W,l),Np(this.player)),!0}return null};
g.x.getOptions=function(){return K9R(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.x.J7=function(){var r=this.player.N(),l=this.player.getVideoData(),U=r.annotationsLoadPolicy||l.annotationsLoadPolicy;return g.CF(l)||this.player.isMutedByEmbedsMutedAutoplay()?!1:U===1&&!l.Z9||r.iG.get(l.videoId)||g.S0(l)||g.z2(l)?!0:!1};
g.x.hC=function(){if(this.L){var r=this.player.hw().getVideoContentRect(!0);g.TC(this.L.element,r.width,r.height);g.bD(this.L.element,r.left,r.top)}if(this.W){var l=this.player.qt();r=this.W;l=l.width;g.xl(r.K,"iv-drawer-small",l<=426);g.xl(r.K,"iv-drawer-big",l>=1280)}};
g.x.tP=function(r){ab8(this,r.state);g.c(r.state,2)&&(this.mf()&&this.ai()&&this.player.getPresentingPlayerType()!==2&&this.x8(!1),this.D2(!1))};
g.x.load=function(){function r(d){var K=l.loadNumber;l.U=null;l.loaded&&l.loadNumber===K&&l.player.getVideoData().videoId===F&&(d=g.Zi(d)&&d.responseXML?d.responseXML:null)&&(oPC(l,d),g.Pl(l.player.getRootNode(),"iv-module-loaded"))}
var l=this;g.Rf.prototype.load.call(this);ab8(this,this.player.getPlayerStateObject());this.loadNumber++;var U=this.player.getVideoData(),F=U.videoId;g.Cp()&&(r=r_C(this,r));var Y={format:"XML",onFinish:r,onError:function(){l.U=null},
urlParams:{}};U.isPharma&&(Y.urlParams.pharma="1");Y.method="POST";Y.withCredentials=!0;var e=this.player.N().iG.get(F);e&&$K0(Y,e);e=e&&(e.rZ||e.HX);if(!U.Hm||e)U.OF?Ibr(this,U.OF,Y):(this.j=function(){if(!l.T)l.onVideoDataChange(Y);var d=l.player.getVideoData();(d==null?0:g.fk(d))&&!l.kN&&Y$Y(l,d)},this.player.addEventListener("videodatachange",this.j));
g.Sg(this.player,this.L.element,4);this.hC();(e=g.S0(U))&&F98(this,e);(e=g.z2(U))&&e.featuredChannel&&OX0(this,e.featuredChannel,e.annotationId||"branding",U.videoId||null,U.eventId||null);this.Fs=g.ze("ytp-cards-button",this.player.getRootNode());g.fk(U)&&Y$Y(this,U)};
g.x.onVideoDataChange=function(r){var l=this.player.getVideoData();l.OF&&Ibr(this,l.OF,r)};
g.x.unload=function(){this.player.MB("annotations_module");for(var r=g.Q(Object.keys(this.D)),l=r.next();!l.done;l=r.next())this.D[l.value].destroy();this.V=null;this.W&&(this.W.destroy(),this.W=null,Np(this.player));this.T=!1;this.U&&(this.U.abort(),this.U=null);this.kN=!1;this.D={};this.X.hide();g.Rf.prototype.unload.call(this);this.L.detach();this.j&&(this.player.removeEventListener("videodatachange",this.j),this.j=null)};
g.x.KN=function(r){r===this.player.getVideoData().videoId&&(this.loaded?lAr(this):this.load())};
g.x.mf=function(){var r;return((r=this.W)==null?void 0:r.isAvailable())||this.kN};
g.x.ai=function(){return!!this.W&&this.W.L};
g.x.x8=function(r,l,U){l=l===void 0?!1:l;this.mf();this.W&&(r?U?$E(this.W,U,l):$E(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",l):lv(this.W))};
g.x.D2=function(r,l){this.player.publish(r?"cardsteasershow":"cardsteaserhide",l)};
g.x.Rf=function(){this.player.N().iG.unsubscribe("vast_info_card_add",this.KN,this);g.M0(this.player.getRootNode(),g.OZ.IV_DRAWER_OPEN);for(var r=this.sF,l=g.cs,U=0,F=r.length;U<F;U++)l.W_(r[U]);this.sF.length=0;g.Rf.prototype.Rf.call(this)};
g.x.createElement=function(r){r=new g.p(r);g.w(this,r);return r.element};g.ZR("annotations_module",LSG);g.ZR("creatorendscreen",f40);})(_yt_player);
