(function(g){var window=this;'use strict';var MZG=function(r,l,U){g.y(function(F){r.W=g.Tj(l,U);g.Wm(F)})},Jn=function(r){r.isActive()||r.start()},sq8=function(r,l){return l?r.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},xKG=function(r){return g.Oi(r)||r.Y("web_enable_caption_language_preference_stickiness")},W9b=function(r,l){var U=new g.nf;
U.languageCode=r.languageCode;U.languageName=r.languageName;U.name=r.name;U.displayName=r.displayName;U.kind=r.kind;U.isDefault=!1;U.W=r.W;U.isTranslateable=r.isTranslateable;U.vssId=r.vssId;U.url=r.url;U.translationLanguage=l;r.xtags&&(U.xtags=r.xtags);r.captionId&&(U.captionId=r.captionId);return U},Qq$=function(r,l){var U,F,Y;
return g.y(function(e){if(e.X==1)return U=r+"|"+l,g.T(e,g.eJ(),2);if(e.X!=3){F=e.W;if(!F)throw g.NZ("gct");return g.T(e,g.Sy(F),3)}Y=e.W;return e.return(Y.get("captions",U))})},EPY=function(r,l,U){Qq$(r,l).then(function(F){F&&U(F.trackData,new g.nf(F.metadata))})},hB8=function(r){if(!ZXq.test(r))throw Error("'"+r+"' is not a valid hex color");
r.length==4&&(r=r.replace(RBp,"#$1$1$2$2$3$3"));r=r.toLowerCase();r=parseInt(r.slice(1),16);return[r>>16,r>>8&255,r&255]},nP8=function(){var r=void 0;
r=r===void 0?{}:r;var l="suggest_correction"in g.aOG?g.aOG.suggest_correction:"Edit caption";l=l||"";var U={},F;for(F in r){U={H8:U.H8};U.H8=F;var Y=function(e){return function(){return String(r[e.H8])}}(U);
l=l.replace(new RegExp("\\$\\{"+U.H8+"\\}","gi"),Y);l=l.replace(new RegExp("\\$"+U.H8,"gi"),Y)}return l},GcY=function(){return g.SX("yt-player-caption-display-settings")},m7=function(){this.segments=[]},X_8=function(r,l){var U=g.Xq(r.segments,l);
U>=0||U<0&&(-U-1)%2===1||(U=-U-1,U>0&&l-r.segments[U-1]===1&&U<r.segments.length&&r.segments[U]-l===1?(g.Mj(r.segments,U),g.Mj(r.segments,U-1)):U>0&&l-r.segments[U-1]===1?r.segments[U-1]=l:U<r.segments.length&&r.segments[U]-l===1?r.segments[U]=l:(g.nr(r.segments,U,0,l),g.nr(r.segments,U+1,0,l)))},iX8=function(r,l,U,F,Y,e){g.H.call(this);
this.policy=r;this.player=l;this.kN=U;this.T=F;this.U=Y;this.V=e;this.K=new m7;this.D=-1;this.L=this.X=this.W=null;this.sF=0;this.j=new g.F1(this.z1,1E3,this);this.events=new g.Lg(this);g.w(this,this.j);g.w(this,this.events);this.events.G(l,"SEEK_COMPLETE",this.xZ);this.xZ();this.z1()},bXr=function(r){return r.W&&r.W.D?r.W.D+r.player.EL()<r.player.getCurrentTime():!1},NCr=function(r,l){if(r.policy.oD&&r.player.A8()){var U=g.Yi(l,r.policy,{});
U.set("pot",r.player.A8());U=U.O4()}else U=g.Yi(l,r.policy,{}).O4();var F={format:"RAW",withCredentials:!0};if(r.policy.YN){F.method="POST";var Y=l.K;Y&&Object.keys(Y).length>0?F.postBody=g.W2(Y,g.MC):F.postBody=(0,g.GJ)([120,0])}r.U&&(F.responseType="arraybuffer");var e=++r.sF,d=(0,g.f)();r.L=g.Hx(U,F,3,100,-1,function(K){K.errorCode==="net.timeout"&&r.player.pP("capnt",{rn:e++})}).then(function(K){if(r.policy.Er&&e%100===1){var C=(0,g.f)();
r.player.pP("caprsp",{rn:e,ms:C-d,kb:(K.xhr.responseText.length/1024).toFixed()})}a:{K=K.xhr;r.QT();if(r.X){var v=!(r.U?K.response:K.responseText)||K.status>=400;if(C=g.K6L(K)){K=g.Yi(r.X,r.policy,{});r.X.dU(K,C);NCr(r,r.X);break a}if(v)r.player.pP("capfail",{status:K.status});else{var J;g.w6("fcb_r",(0,g.f)(),((J=r.player.getVideoData())==null?void 0:J.V)||"");J=r.X.BQ[0].xN;r.T!=null&&r.D!==J&&(C=r.X.BQ[0],r.U?r.T(K.response,(C.startTime+r.player.EL())*1E3):r.T(K.responseText,(C.startTime+r.player.EL())*
1E3),r.D=J)}}r.X=null;r.L=null}}).zL(function(K){r.X=null;
r.L=null;var C;r.player.pP("capfail",{rn:e,status:(C=K.xhr)==null?void 0:C.status})});
r.X=l;X_8(r.K,r.X.BQ[0].xN)},PH=function(r,l){g.n5.call(this,l);
this.W=r;this.C=l;this.L=null;this.D=!1;this.logger=new g.AV("caps");this.j=g.ZYR(this.C,this.W)},q$0=function(r,l){var U=[],F;
for(F in r.W.W)if(r.W.W.hasOwnProperty(F)){var Y=r.W.W[F];if(g.XT(Y,l||null)){var e=Y.info.id,d=e,K="."+e,C="",v="";if(Y=Y.info.captionTrack)e=Y.languageCode,d=Y.displayName,K=Y.vssId,C=Y.kind,v=Y.id;else{Y=e;var J=g.sl0.get(Y);J==null&&(J=jqb[Y]||jqb[Y.replace(/-/g,"_")],g.sl0.set(Y,J));Y=J;d=Y||d}U.push(new g.nf({id:F,languageCode:e,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:K,kind:C,captionId:v}))}}return U},TCR=function(r,l){return l!=null&&l in r.W.W?r.W.W[l]:null},
u8p=function(r,l,U){var F=[],Y;
for(Y in r.W.W)if(r.W.W.hasOwnProperty(Y)){var e=r.W.W[Y];if(g.XT(e,U||null)){var d=e.info.captionTrack;d&&d.languageCode===l&&F.push(e)}}return F.length?F[0]:null},An=function(r,l,U,F,Y,e,d,K,C,v){var J=v.isInline()&&!0,m={};
Object.assign(m,l);Object.assign(m,r.params);Object.assign(m,U);var P={};Object.assign(P,l.RT);r.params.RT&&Object.assign(P,r.params.RT);Object.assign(P,U.RT);J&&(m.windowOpacity=.6,P.backgroundOpacity=0);m.RT=P;var A=m.TJ===1,M=[{Z:"span",S:"captions-text",J:{style:"word-wrap: normal; display: block;"}}],E,Z,n;(K=K.Jw("caption_edit_on_hover")&&((E=v.getVideoData().getPlayerResponse())==null?void 0:(Z=E.captions)==null?void 0:(n=Z.playerCaptionsTracklistRenderer)==null?void 0:n.openTranscriptCommand))&&
M.unshift({Z:"button",S:"caption-edit",J:{tabindex:"0","aria-label":nP8()},B:[{Z:"svg",J:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},B:[{Z:"path",J:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.p.call(this,{Z:"div",S:"caption-window",J:{id:"caption-window-"+r.id,dir:A?"rtl":"ltr",tabindex:"0",lang:m.lang},B:M});var h=
this;this.j=[];this.qh=!1;this.X=r;this.iG=this.YN=null;this.bI=e;this.P5=d;this.T=null;this.maxWidth=e*.96;this.maxHeight=d*.96;this.W=m;this.JB=U;this.sF=l;this.K=this.Zz("captions-text");this.xq=this.K.style.getPropertyValue("box-decoration-break")!==""||this.K.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.vQ=y_R(F,Y,e,d);this.c5=C;K&&(this.D=this.Zz("caption-edit"),this.G(this.D,"click",function(){h.c5()}));
this.type=0;this.yT=this.vQ*BCG(P);this.kq=J;r=new g.Dl(this.element,!0);g.w(this,r);r.subscribe("dragstart",this.oP,this);r.subscribe("dragmove",this.z_,this);r.subscribe("dragend",this.NT,this);this.lG=this.Nh=this.W5=this.If=0;r="";this.W.windowOpacity&&(r=hB8(this.W.windowColor),r="rgba("+r[0]+","+r[1]+","+r[2]+","+this.W.windowOpacity+")");l={"background-color":r,display:this.W.isVisible===!1?"none":"","text-align":HX0[this.W.textAlign]};this.xq&&(l["border-radius"]=r?this.yT/8+"px":"");(this.L=
this.X.params.TJ===2||this.X.params.TJ===3)&&gPC(this,this.element);g.RI(this.element,l);if(J){var N;(N=this.element.parentElement)==null||N.style.setProperty("--caption-window-color",r)}switch(this.W.pK){case 0:case 1:case 2:g.Pl(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Pl(this.element,"ytp-caption-window-bottom")}},gPC=function(r,l){var U="vertical-rl";
r.W.L_===1&&(U="vertical-lr");g.Zs&&(U=U==="vertical-lr"?"tb-lr":"tb-rl");g.RI(l,"-o-writing-mode",U);g.RI(l,"-webkit-writing-mode",U);g.RI(l,"writing-mode",U);g.RI(l,"text-orientation","upright");g.Pl(l,"ytp-vertical-caption");r.X.params.TJ===3&&(g.RI(l,"text-orientation",""),g.RI(l,"transform","rotate(180deg)"))},BCG=function(r){var l=1+.25*(r.fontSizeIncrement||0);
if(r.offset===0||r.offset===2)l*=.8;return l},w_$=function(r,l){var U={},F=l.background?l.background:r.W.RT.background;
if(l.backgroundOpacity!=null||l.background){var Y=l.backgroundOpacity!=null?l.backgroundOpacity:r.W.RT.backgroundOpacity;F=hB8(F);U.background="rgba("+F[0]+","+F[1]+","+F[2]+","+Y+")";r.xq&&(U["box-decoration-break"]="clone",U["border-radius"]=r.yT/8+"px")}if(l.fontSizeIncrement!=null||l.offset!=null)U["font-size"]=r.vQ*BCG(l)+"px";F=1;Y=l.color||r.W.RT.color;if(l.color||l.textOpacity!=null)Y=hB8(Y),F=l.textOpacity==null?r.W.RT.textOpacity:l.textOpacity,Y="rgba("+Y[0]+","+Y[1]+","+Y[2]+","+F+")",
U.color=Y,U.fill=Y;var e=l.charEdgeStyle;e===0&&(e=void 0);if(e){Y="rgba(34, 34, 34, "+F+")";var d="rgba(204, 204, 204, "+F+")";l.qv&&(d=Y=l.qv);var K=r.vQ/16/2,C=Math.max(K,1),v=Math.max(2*K,1),J=Math.max(3*K,1),m=Math.max(5*K,1);F=[];switch(e){case 4:for(;J<=m;J+=K)F.push(v+"px "+v+"px "+J+"px "+Y);break;case 1:v=window.devicePixelRatio>=2?.5:1;for(e=C;e<=J;e+=v)F.push(e+"px "+e+"px "+Y);break;case 2:F.push(C+"px "+C+"px "+d);F.push("-"+C+"px -"+C+"px "+Y);break;case 3:for(J=0;J<5;J++)F.push("0 0 "+
v+"px "+Y)}U["text-shadow"]=F.join(", ")}Y="";switch(l.fontFamily){case 1:Y='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:Y='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Y='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:Y='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:Y='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Y=g.oW()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Y='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Y&&(U["font-family"]=Y);Y=l.offset;Y==null&&(Y=r.W.RT.offset);switch(Y){case 0:U["vertical-align"]="sub";break;case 2:U["vertical-align"]="super"}l.fontFamily===7&&(U["font-variant"]="small-caps");l.bold&&(U["font-weight"]="bold");l.italic&&(U["font-style"]="italic");l.underline&&(U["text-decoration"]=
"underline");l.zY&&(U.visibility="hidden");l.kU===1&&r.L&&(U["text-combine-upright"]="all",U["text-orientation"]="mixed",Y=g.vU||g.iY,r.X.params.TJ===3?U.transform=Y?"rotate(90deg)":"rotate(180deg)":Y&&(U.transform="rotate(-90deg)"));if(l.textEmphasis===1||l.textEmphasis===2||l.textEmphasis===3||l.textEmphasis===4||l.textEmphasis===5)if(g.vU)U["font-weight"]="bold";else switch(U["text-emphasis-style"]="filled circle",U["text-emphasis-color"]="currentcolor",U["webkit-text-emphasis"]="filled circle",
l.textEmphasis){case 4:case 3:U["text-emphasis-position"]="under left";U["webkit-text-emphasis-position"]="under left";break;case 5:case 2:U["text-emphasis-position"]="over right",U["webkit-text-emphasis-position"]="over right"}return U},MV=function(r){r=r.split("px");
return r.length>0?(r=Number(r[0]))?r:0:0},DKC=function(r){r.T=g.I1("SPAN");
g.RI(r.T,{display:"block"});g.Pl(r.T,"caption-visual-line");r.K.appendChild(r.T)},VZf=function(r,l){var U=g.I1("SPAN");
g.RI(U,{display:"inline-block","white-space":"pre-wrap"});g.RI(U,w_$(r,l));U.classList.add("ytp-caption-segment");r.T.appendChild(U);U.previousElementSibling&&(g.RI(U.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.RI(U,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return U},fAr=function(r,l,U){r.qh=r.qh||!!U;
var F={};Object.assign(F,r.W.RT);Object.assign(F,U||l.W);Object.assign(F,r.JB.RT);(U=!r.T)&&DKC(r);for(var Y=r.YN&&r.iG&&g.k0(F,r.iG)?r.YN:VZf(r,F),e=typeof l.text==="string",d=e?l.text.split("\n"):[l.text],K=0;K<d.length;K++){var C=K>0||!l.append,v=d[K];C&&!U?(DKC(r),Y=VZf(r,F)):C&&U&&(U=!1);v&&(Y.appendChild(e?g.kR(v):v),e||v.tagName!=="RUBY"||v.childElementCount!==4||g.vU||!g.nC(v.children[2],"text-emphasis")||(C=r.L?"padding-right":"padding-top",g.nC(v.children[2],"text-emphasis-position")&&(C=
r.L?"padding-left":"padding-bottom"),g.tM?g.RI(Y,C,"1em"):g.RI(Y,C,"0.5em")))}r.iG=F;r.YN=Y;r.j.push(l)},y_R=function(r,l,U,F){var Y=l/360*16;
l>=r&&(r=640,F>U*1.3&&(r=480),Y=U/r*16);return Y},zBr=function(){this.L=this.time=this.mode=this.X=0;
this.K=new S$q(this);this.U=new S$q(this);this.W=[];this.clear()},tZ$=function(r,l,U){if(r===255&&l===255||!r&&!l)return{IK:r,
XA:l,result:0};r=p_R[r];l=p_R[l];if(r&128){var F;if(F=!(l&128))F=l,F=U.NB()&&U.XA===F;if(F)return{IK:r,XA:l,result:1}}else if(l&128&&1<=r&&r<=31)return{IK:r,XA:l,result:2};return{IK:r,XA:l,result:3}},c_b=function(r,l,U,F){l===255&&U===255||!l&&!U?(++r.L===45&&r.reset(),r.K.X.clear(),r.U.X.clear()):(r.L=0,L9C(r.K,l,U,F))},aAY=function(r,l){r.W.sort(function(Y,e){var d=Y.time-e.time;
return d===0?Y.order-e.order:d});
for(var U=g.Q(r.W),F=U.next();!F.done;F=U.next())F=F.value,r.time=F.time,F.type===0?c_b(r,F.hc,F.VQ,l):F.type===1&&r.X&496&&L9C(r.U,F.hc,F.VQ,l);r.W.length=0},sl=function(){this.type=0},xE=function(){this.state=this.XA=this.IK=0},IAq=function(){this.timestamp=this.W=0},WH=function(r){this.U=r;
this.L=[];this.W=this.X=this.row=0;this.style=new sl;for(r=this.K=0;r<=15;r++){this.L[r]=[];for(var l=0;l<=32;l++)this.L[r][l]=new IAq}},Qo=function(r,l){if(r.style.type===3){for(var U=0,F=0,Y=r.U.time+0,e="",d="",K=Y,C=1;C<=15;++C){for(var v=!1,J=F?F:1;J<=32;++J){var m=r.L[C][J];
if(m.W!==0){U===0&&(U=C,F=J);v=String.fromCharCode(m.W);var P=m.timestamp;P<Y&&(Y=P);m.timestamp=K;d&&(e+=d,d="");e+=v;v=!0}if((m.W===0||J===32)&&v){d="\n";break}else if(F&&!v)break}if(U&&!v)break}e&&l.K(U,F,Y,K,e)}else for(F=U=0,e=Y=r.U.time+0,d=1;d<=15;++d)for(K="",C=1;C<=32;++C)if(J=r.L[d][C],m=J.W,m!==0&&(U===0&&(U=d,F=C),v=String.fromCharCode(m),P=J.timestamp,P<=Y&&(Y=P),K+=v,J.reset()),C===32||m===0)K&&l.K(U,F,Y,e,K),Y=e,K="",F=U=0},l8r=function(r,l){switch(r){case 0:return kcq[(l&127)-32];
case 1:return ojY[l&15];case 2:return r2C[l&31];case 3:return $or[l&31]}return 0},El=function(r){return r.L[r.row][r.X]},ZD=function(r,l,U){l>=2&&r.X>1&&(--r.X,El(r).W=0);
var F=El(r);F.timestamp=r.U.time+0;F.W=l8r(l,U);r.X<32&&r.X++},Uoj=function(r,l,U,F){for(var Y=0;Y<F;Y++)for(var e=0;e<=32;e++){var d=r.L[l+Y][e],K=r.L[U+Y][e];
d.W=K.W;d.timestamp=K.timestamp}},Ry=function(r,l,U){for(var F=0;F<U;F++)for(var Y=0;Y<=32;Y++)r.L[l+F][Y].reset()},FWb=function(r){r.row=r.W>0?r.W:1;
r.X=1;Ry(r,0,15)},YDb=function(r){this.L=r;
this.U=0;this.style=new sl;this.D=new WH(this.L);this.j=new WH(this.L);this.text=new WH(this.L);this.X=this.D;this.K=this.j;this.W=this.X},eLq=function(r,l,U){var F=r.X,Y=!1;
switch(r.style.get()){case 4:case 1:case 2:r.style.get()===4&&F.W>0||(Qo(F,U),FWb(r.X),FWb(r.K),F.row=15,F.W=l,Y=!0)}r.style.set(3);r.W=F;r.W.style=r.style;r.L.mode=1<<F.K;Y?F.X=1:F.W!==l&&(F.W>l?(Qo(F,U),Ry(F,F.row-F.W,l)):F.row<l&&(l=F.W),F.W=l)},dop=function(r){r.style.set(1);
r.W=r.K;r.W.W=0;r.W.style=r.style;r.L.mode=1<<r.W.K},OMC=function(r){r.style.set(4);
r.W=r.text;r.W.style=r.style;r.L.mode=1<<r.W.K},S$q=function(r){this.W=r;
this.U=0;this.L=new YDb(this.W);this.D=new YDb(this.W);this.X=new xE;this.K=this.L},L9C=function(r,l,U,F){r.X.update();
l=tZ$(l,U,r.X);switch(l.result){case 0:return;case 1:case 2:return}var Y=l.IK;U=l.XA;if(32<=Y||!Y)r.W.mode&r.W.X&&(l=Y,l&128&&(l=127),U&128&&(U=127),r=r.K.W,l&96&&ZD(r,0,l),U&96&&ZD(r,0,U),l!==0&&U!==0&&r.style.type===3&&Qo(r,F));else if(Y&16)a:if(!r.X.matches(Y,U)&&(l=r.X,l.IK=Y,l.XA=U,l.state=2,l=Y&8?r.D:r.L,r.K=l,r.W.mode=1<<(r.U<<2)+(l.U<<1)+(l.style.type===4?1:0),(r.W.mode|1<<(r.U<<2)+(l.U<<1)+(l.style.type!==4?1:0))&r.W.X))if(U&64){F=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Y&7)<<1|U>>5&1];
r=U&16?((U&14)>>1)*4:0;U=l.W;switch(l.style.get()){case 4:F=U.row;break;case 3:if(F!==U.row){if(F<U.W&&(F=U.W,F===U.row))break;var e=1+U.row-U.W,d=1+F-U.W;Uoj(U,d,e,U.W);l=e;Y=U.W;d<e?(e=d+Y-e,e>0&&(l+=e,Y-=e)):(e=e+Y-d,e>0&&(Y-=e));Ry(U,l,Y)}}U.row=F;U.X=r+1}else switch(Y&7){case 1:switch(U&112){case 32:ZD(l.W,0,32);break a;case 48:U===57?(F=l.W,El(F).W=0,F.X<32&&F.X++):ZD(l.W,1,U&15)}break;case 2:U&32&&ZD(l.W,2,U&31);break;case 3:U&32&&ZD(l.W,3,U&31);break;case 4:case 5:if(32<=U&&U<=47)switch(U){case 32:dop(l);
break;case 33:F=l.W;F.X>1&&(--F.X,El(F).W=0);break;case 36:F=l.W;l=El(F);for(r=0;r<=15;r++)for(U=0;U<=32;U++)if(F.L[r][U]===l){for(;U<=32;U++)F.L[r][U].reset();break}break;case 37:eLq(l,2,F);break;case 38:eLq(l,3,F);break;case 39:eLq(l,4,F);break;case 40:ZD(l.W,0,32);break;case 41:l.style.set(2);l.W=l.X;l.W.W=0;l.W.style=l.style;l.L.mode=1<<l.W.K;break;case 42:F=l.text;F.W=15;F.style.set(4);FWb(F);OMC(l);break;case 43:OMC(l);break;case 44:r=l.X;switch(l.style.get()){case 1:case 2:case 3:Qo(r,F)}Ry(r,
0,15);break;case 45:b:{r=l.W;switch(l.style.get()){default:case 2:case 1:break b;case 4:if(r.row<15){++r.row;r.X=1;break b}break;case 3:}r.W<2&&(r.W=2,r.row<r.W&&(r.row=r.W));l=r.row-r.W+1;Qo(r,F);Uoj(r,l,l+1,r.W-1);Ry(r,r.row,1)}break;case 46:Ry(l.K,0,15);break;case 47:Qo(l.X,F),l.K.updateTime(l.L.time+0),F=l.K,l.K=l.X,l.X=F,dop(l)}break;case 7:switch(U){case 33:case 34:case 35:F=l.W,(F.X+=U&3)>32&&(F.X=32)}}},KW8=function(){},hn=function(r,l,U,F,Y,e,d){e=e===void 0?!1:e;
d=d===void 0?null:d;g.M2.call(this,r,r+l,{priority:U,namespace:"captions"});this.windowId=F;this.text=Y;this.append=e;this.W=d},vjY=function(r,l,U,F,Y,e,d){var K=e[0],C=d[K.getAttribute("p")];
if(C.rK===1){var v=e[1],J=e[2];e=e[3];K.getAttribute("t");v.getAttribute("t");J.getAttribute("t");e.getAttribute("t");K.getAttribute("p");v.getAttribute("p");e.getAttribute("p");d=d[J.getAttribute("p")];K=Ce8(K.textContent,v.textContent,J.textContent,e.textContent,d);return new hn(r,l,Y,U,K,F,C)}switch(C.rK){case 9:case 10:C.textEmphasis=1;break;case 11:C.textEmphasis=2;break;case 12:C.textEmphasis=3;break;case 13:C.textEmphasis=4;break;case 14:C.textEmphasis=5}return new hn(r,l,Y,U,K.textContent||
"",F,C)},Ce8=function(r,l,U,F,Y){var e=g.oW(),d=e?g.I1("DIV"):g.I1("RUBY"),K=g.I1("SPAN");
K.textContent=r;d.appendChild(K);r=e?g.I1("DIV"):g.I1("RP");r.textContent=l;d.appendChild(r);l=e?g.I1("DIV"):g.I1("RT");l.textContent=U;d.appendChild(l);U=Y.rK;if(U===10||U===11||U===12||U===13||U===14)if(g.RI(l,"text-emphasis-style","filled circle"),g.RI(l,"text-emphasis-color","currentcolor"),g.RI(l,"webkit-text-emphasis","filled circle"),Y.rK===11||Y.rK===13)g.RI(l,"webkit-text-emphasis-position","under left"),g.RI(l,"text-emphasis-position","under left");U=!0;if(Y.rK===4||Y.rK===7||Y.rK===12||
Y.rK===14)g.RI(d,"ruby-position","over"),g.RI(d,"-webkit-ruby-position","before");else if(Y.rK===5||Y.rK===6||Y.rK===11||Y.rK===13)g.RI(d,"ruby-position","under"),g.RI(d,"-webkit-ruby-position","after"),U=!1;Y=e?g.I1("DIV"):g.I1("RP");Y.textContent=F;d.appendChild(Y);e&&(F=U,g.RI(d,{display:"inline-block",position:"relative"}),e=d.firstElementChild.nextElementSibling,g.RI(e,"display","none"),e=e.nextElementSibling,g.RI(e,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.RI(d.lastElementChild,"display","none"),F?(g.RI(d,"padding-top","0.6em"),g.RI(e,"top","0")):(g.RI(d,"padding-bottom","0.6em"),g.RI(e,"bottom","0")));return d},nE=function(){g.H.apply(this,arguments)},GO=function(r,l,U,F,Y){g.M2.call(this,r,r+l,{priority:U,
namespace:"captions"});this.id=F;this.params=Y;this.W=[]},J2Y=function(r){var l="_"+XK++;
return new GO(0,0x8000000000000,0,l,r)},iv=function(r){nE.call(this);
this.K=r;this.pens={};this.T={};this.V={};this.U="_"+XK++;this.j={};this.X=this.W=null;this.D=!0},bv=function(r,l){r=r.getAttribute(l);
if(r!=null)return Number(r)},NV=function(r,l){r=r.getAttribute(l);
if(r!=null)return r==="1"},jr=function(r,l){r=bv(r,l);
return r!==void 0?r:null},TO=function(r,l){r=r.getAttribute(l);
if(r!=null)return qV.test(r),r},moY=function(r,l){var U={},F=l.getAttribute("ws");
Object.assign(U,F?r.V[F]:r.K);r=jr(l,"mh");r!=null&&(U.vz=r);r=jr(l,"ju");r!=null&&(U.textAlign=r);r=jr(l,"pd");r!=null&&(U.TJ=r);r=jr(l,"sd");r!=null&&(U.L_=r);r=TO(l,"wfc");r!=null&&(U.windowColor=r);l=bv(l,"wfo");l!==void 0&&(U.windowOpacity=l/255);return U},Pe$=function(r,l){var U={},F=l.getAttribute("wp");
F&&Object.assign(U,r.T[F]);r=jr(l,"ap");r!=null&&(U.pK=r);r=bv(l,"cc");r!=null&&(U.KW=r);r=bv(l,"ah");r!=null&&(U.wU=r);r=bv(l,"rc");r!=null&&(U.UH=r);l=bv(l,"av");l!=null&&(U.Lb=l);return U},A2R=function(r,l,U,F){var Y={};
Object.assign(Y,Pe$(r,l));Object.assign(Y,moY(r,l));F?g.k0(Y,r.K)?(F=r.U,Y=r.K):F="_"+XK++:F=l.getAttribute("id")||"_"+XK++;r=bv(l,"t")+U;l=bv(l,"d")||0x8000000000000;if(Y.TJ===2||Y.TJ===3)U=Y.UH,Y.UH=Y.KW,Y.KW=U;return new GO(r,l,0,F,Y)},uv=function(r){nE.call(this);
this.D=r;this.W=new Map;this.K=new Map;this.U=new Map;this.X=new Map},yo=function(r){r=g.Ge(Math.round(r),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-r.length)+r},MDC=function(r,l,U,F,Y){F===0&&(F=0x8000000000000);
var e={};l.wpWinPosId&&Object.assign(e,r.K.get(l.wpWinPosId));l.wsWinStyleId&&Object.assign(e,r.U.get(l.wsWinStyleId));r=l.rcRowCount;r!==void 0&&(e.UH=r);l=l.ccColCount;l!==void 0&&(e.KW=l);if(e.TJ===2||e.TJ===3)l=e.UH,e.UH=e.KW,e.KW=l;return new GO(U,F,0,Y,e)},BH=function(r,l,U){g.n5.call(this,r);
this.videoData=l;this.audioTrack=U;this.U=l.FE},HH=function(r,l,U,F,Y,e,d,K,C,v){An.call(this,r,l,U,F,Y,e,d,K,C,v);
this.type=1},g9=function(r,l,U){this.trackData=r;
this.D=U;this.version=this.U=this.L=this.byteOffset=0;this.X=[];this.W=new DataView(this.trackData)},w9=function(r){var l=r.byteOffset;
r.byteOffset+=1;return r.W.getUint8(l)},DD=function(r){var l=r.byteOffset;
r.byteOffset+=4;return r.W.getUint32(l)},Vo=function(r,l){nE.call(this);
this.X=r;this.K=l;this.track=this.K.languageName==="CC3"?4:0;this.W=new zBr;this.W.X=1<<this.track},xo8=function(r){if(typeof r==="string")return!1;
r=new g9(r,8,0);return s9Y(r)},s9Y=function(r){if(!(r.byteOffset<r.W.byteLength)||DD(r)!==1380139777)return!1;
r.version=w9(r);if(r.version>1)return!1;w9(r);w9(r);w9(r);return!0},fE=function(r,l,U,F,Y,e,d,K,C,v){An.call(this,r,l,U,F,Y,e,d,K,C,v);
var J=this;this.type=2;this.KP=[];this.kN=this.V=this.OF=0;this.rz=NaN;this.Rg=0;this.SN=null;this.Kp=new g.F1(this.LU,433,this);this.D&&(v.createClientVe(this.D,this,167342),this.G(this.D,"click",function(){v.logClick(J.D)}),r=new g.Dl(this.element,!0),g.w(this,r),r.subscribe("hoverstart",function(){v.logVisibility(J.D,!0)},this));
g.Pl(this.element,"ytp-caption-window-rollup");g.w(this,this.Kp);g.RI(this.element,"overflow","hidden")},WWR=function(r,l){if(!l)return"";
r.L&&r.X.params.L_!==1&&(l*=-1);return"translate"+(r.L?"X":"Y")+"("+l+"px)"},Q9p=function(r){r.KP=Array.from(r.element.getElementsByClassName("caption-visual-line"));
for(var l=r.X.params.UH,U=0,F=0,Y=r.KP.length-1;U<l&&Y>-1;){var e=r.KP[Y];F+=r.L?e.offsetWidth:e.offsetHeight;U++;Y--}r.V=F;l=Math;U=l.max;isNaN(r.rz)&&((F=r.W.KW)?(Y=g.I1("SPAN"),g.Fk(Y,"\u2013".repeat(F)),g.RI(Y,w_$(r,r.W.RT)),r.K.appendChild(Y),r.rz=Y.offsetWidth,r.K.removeChild(Y)):r.rz=0);F=r.K;r.kN=U.call(l,r.rz,r.Rg,(r.L?F.offsetHeight:F.offsetWidth)+1)},Ejb=function(r,l){Q9p(r);
var U=r.KP.reduce(function(e,d){return(r.L?d.offsetWidth:d.offsetHeight)+e},0);
U=r.V-U;if(U!==r.OF){var F=U>0&&r.OF===0,Y=U<r.OF;l||isNaN(U)||F||!Y||(g.Pl(r.element,"ytp-rollup-mode"),r.G(r.element,"transitionend",r.LU));g.RI(r.K,"transform",WWR(r,U));r.OF=U}Q9p(r)},ZMC=function(r,l,U,F){var Y=this;
this.C=r;this.L=l;this.logger=U;this.Yq=F;this.L1=[];this.Uy=[];this.W=null;this.wv={JYa:function(){return Y.W},
I9:function(){return Y.L1}};
r=g.GQ(this.C.N().experiments,"html5_override_micro_discontinuities_threshold_ms");this.X=r>0?r:10},njG=function(r,l){r.W=function(U,F){if(U.info.U){var Y=U;
if(r.Uy.length>0){for(Y=r.Uy.shift();r.Uy.length>0;)Y=g.WF(Y,r.Uy.shift());Y=g.WF(Y,U)}if(Y){U=Y;try{var e=g.QD(U)*1E3}catch(v){e=U.info.startTime*1E3}try{var d=g.oNf(U)*1E3}catch(v){d=U.info.duration*1E3}if(e<0||d<0)e<0&&(e=U.info.startTime*1E3),d<0&&(d=U.info.duration*1E3);U.info.startTime=e/1E3;U.info.K=e/1E3;U.info.duration=d/1E3;U.info.j=d/1E3;e=r.x$(Y);d=e.xN;e={formatId:e.formatId,startTimeMs:e.startTimeMs,durationMs:e.durationMs,cw:d,R9:d};d=RLr(r.L1,e.startTimeMs);var K=(U=d>=0?r.L1[d]:null)?
U.startTimeMs+U.durationMs:0,C=e.startTimeMs+e.durationMs;!U||e.startTimeMs-K>r.X?r.L1.splice(d+1,0,e):(U.durationMs=Math.max(K,C)-U.startTimeMs,U.R9=Math.max(U.R9,e.R9));F(r.L1);F=g.xi(Y);hLb(r.L,F.buffer.slice(F.byteOffset,F.byteLength+F.byteOffset),l,Y.info.K)}else r.logger.W(350058965,"Empty slice")}else r.Uy.push(U)};
r.C.addEventListener("sabrCaptionsDataLoaded",r.W)},RLr=function(r,l){r=g.Xq(r,{startTimeMs:l},function(U,F){return U.startTimeMs-F.startTimeMs});
return r>=0?r:-r-2},Gkj=function(r,l){g.n5.call(this,l);
this.W=r;this.C=l;this.logger=new g.AV("caps");this.L=this.D=null;this.j=new ZMC(this.C,this,this.logger,this.W.Yq)},hLb=function(r,l,U,F){r.logger.debug(function(){return"SABR captions data received for "+F});
r.D?r.L==null?r.logger.W(350058965,"Null loaded track meta data at captions data received"):U.A7(l,r.L,F*1E3):r.logger.W(350058965,"Null Representation at captions data received")},XDj=function(r,l){var U=[],F;
for(F in r.W.W)if(r.W.W.hasOwnProperty(F)){var Y=r.W.W[F];if(g.XT(Y,l||null)){var e=Y.info.id,d=e,K="."+e,C="",v="";if(Y=Y.info.captionTrack)e=Y.languageCode,d=Y.displayName,K=Y.vssId,C=Y.kind,v=Y.id;U.push(new g.nf({id:F,languageCode:e,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:K,kind:C,captionId:v}))}}return U},iMC=function(r,l,U){var F=[],Y;
for(Y in r.W.W)if(r.W.W.hasOwnProperty(Y)){var e=r.W.W[Y];if(g.XT(e,U||null)){var d=e.info.captionTrack;d&&d.languageCode===l&&F.push(e)}}return F.length?F[0]:null},bMR=function(r,l){if(!g.The(r)||r.W!=null&&g.ZYR(l,r.W)&&r.W.W.rawcc!=null)return!1;
l=!!r.W&&r.W.isManifestless&&Object.values(r.W.W).some(function(U){return g.XT(U,"386")});
r=!!r.W&&!r.W.isManifestless&&g.mU4(r.W);return l||r},N08=function(){nE.call(this)},qD8=function(r){var l=j9Y.length;
if(r.byteLength<l)return!1;r=new Uint8Array(r,0,l);for(var U=0;U<l;U++)if(j9Y[U]!==r[U])return!1;return!0},T08=function(r,l,U,F,Y,e,d,K,C){switch(d.tagName){case "b":K.bold=!0;
break;case "i":K.italic=!0;break;case "u":K.underline=!0}for(var v=0;v<d.childNodes.length;v++){var J=d.childNodes[v];if(J.nodeType===3)J=new hn(l,U,F,Y.id,J.nodeValue,e||v>0,g.aY(K)?void 0:K),C.push(J),Y.W.push(J);else{var m={};Object.assign(m,K);T08(r,l,U,F,Y,!0,J,m,C)}}},uAr=function(r){var l=r.split(":");
r=0;l=g.Q(l);for(var U=l.next();!U.done;U=l.next())r=r*60+Number(U.value);return r*1E3},y2p=function(r,l,U,F){F=Object.assign({vz:0},F);
return new GO(r,l,U,"_"+XK++,F)},Sr=function(r,l){g.H.call(this);
this.C=r;this.WQ=l;this.W=null;this.X=this.C.a7();this.logger=new g.AV("caps")},HMr=function(r,l,U){if(typeof l==="string"||xo8(l))return[{trackData:l,
DT:U}];if(typeof l==="string"&&l.substring(0,6)==="WEBVTT"||typeof l!=="string"&&qD8(l))return[{trackData:l,DT:U}];var F=new DataView(l);if(F.byteLength<=8||F.getUint32(4)!==1718909296)return[];var Y=g.rL4(F);if(r.X&&Y){var e=g.pK4(Y),d=g.tGP(Y);Y=Y.Tl;e&&Y&&r.X.XE(Y,e,d)}r=g.sq(F,1835295092);if(!r||!r.length||!r[0].size)return[];e=[];for(d=0;d<r.length;d++)Y=r[d],Y=new Uint8Array(l,Y.dataOffset,Y.size-(Y.dataOffset-Y.offset)),Y=g.D0(Y),e.push({trackData:Y,DT:U+d*1E3});B0C(F,e,U);return e=e.filter(function(K){return!!K.trackData})},
B0C=function(r,l,U){var F=g.dK(r,0,1836476516),Y=9E4;
F&&(Y=g.Oq(F)||9E4);F=0;for(var e=g.sq(r,1836019558),d=0;d<e.length;d++){var K=e[d];d<l.length&&(K=g.dK(r,K.dataOffset,1953653094))&&(K=g.dK(r,K.dataOffset,1952867444))&&(K=g.A8(K)/Y*1E3,d===0&&(F=K),l[d].DT=K-F+U||U*d*1E3)}},gjG=function(r,l,U){r.W||(r.W=new N08);
r=r.W.L(l,U);Math.random()<.01&&g.pZ(Error("Deprecated subtitles format in web player: WebVTT"));return r},wDj=function(r){var l={};
if(r=g.iE(r))l.lang=r,g.iyj.test(r)&&(l.TJ=1);return l},f8Y=function(r){g.Rf.call(this,r);
var l=this;this.C=r;this.YN=[];this.KP={};this.yT={};this.D=!1;this.K="NONE";this.X=this.V=this.kN=this.vQ=this.If=null;this.Kp={by:function(){l.by()},
A7:function(e,d,K,C){l.A7(e,d,K,C)}};
this.W=null;this.WQ=this.C.N();this.videoData=this.C.getVideoData();this.W5=this.C.hw();this.L={RT:{}};this.j={RT:{}};g.lT(this.videoData)?this.K="OFFLINE":bMR(this.videoData,this.C)?this.K="SABR_LIVE":g.RIK(this.videoData,this.C)?this.K="LIVE":this.videoData.captionTracks.length?this.K="INNERTUBE":this.videoData.Wl&&(this.K="TTS");this.Nh=this.WQ.controlsType==="3";this.lG=new Sr(this.C,this.WQ);this.qh=new g.Lg(this);this.T=new g.p({Z:"div",S:"ytp-caption-window-container",J:{id:"ytp-caption-window-container"}});
this.sF={top:0,right:0,bottom:0,left:0,width:1,height:1};var U=null,F=g.pJ("yt-html5-player-modules::subtitlesModuleData");F&&(U=new g.Bl(F));this.storage=U;var Y;this.kq=!((Y=r.dh())==null||!Y.k_());this.U=Do0(this);this.rz=!this.U&&this.Nh&&this.kq&&(this.K==="LIVE"||this.K==="SABR_LIVE");g.w(this,this.lG);this.U?this.OF=this.iG=null:(this.iG=new g.US(this.GK,void 0,this),g.w(this,this.iG),this.OF=new g.F1(this.LUz,2E3,this),g.w(this,this.OF));g.w(this,this.qh);g.Sg(this.player,this.T.element,4);
g.w(this,this.T);this.U||this.qh.G(r,"resize",this.aU);(this.Rg=g.pA(this.WQ)&&!g.nS()&&!this.C.isFullscreen()&&!this.U&&!this.rz)&&this.qh.G(r,"resize",this.rBz);this.qh.G(r,"onPlaybackAudioChange",this.Mcf);this.qh.G(r,g.x1("captions"),function(e){l.onCueRangeEnter(e)});
this.qh.G(r,g.W9("captions"),function(e){l.onCueRangeExit(e)});
VD$(this,GcY()||{});this.player.mx("onCaptionsModuleAvailable")},pDC=function(r){if(r.WQ.J2===1||r.videoData.nC===1||g.T2(r.videoData,"yt:cc")==="alwayson")return!0;
if(r.videoData.captionTracks.length)var l=r.getAudioTrack().X;if(r.WQ.J2===2){if(g.Oi(r.WQ))var U=SD8(r);else if(r.storage)try{U=r.storage.get("module-enabled")}catch(Y){r.storage.remove("module-enabled")}else U=null;if(U!=null)return!!U}U=sq8(r.player.getAudioTrack(),g.Oi(r.WQ));var F=g.T2(r.videoData,"yt:cc");if(zLb(r)===void 0){if(U==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return F?F==="on":!0;if(U==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return F==="on"}else return F==="on";return l==="ON"||
g.T2(r.videoData,"yt:cc")==="on"},zO=function(r,l){if(r.W&&(l===void 0||!l)||!r.videoData.captionTracks.length)return!1;
r=r.getAudioTrack();return!!r.W||r.X==="FORCED_ON"},zLb=function(r){var l=void 0,U=g.IW(g.aW(),65);
if(g.Oi(r.WQ)&&U!=null){if(SD8(r)!=null)return!1;l=!U}return l},tn=function(r,l){if(!r.X)return null;
if(r.V&&r.V.K)return r.V.K;l=tD$(r,l);l=g.Yd(r.X.X,l);var U=null;if(xKG(r.WQ)){var F=r.C.isInline()?void 0:g.SX("yt-player-caption-sticky-language");for(var Y=[F,r.videoData.captionsLanguagePreference,r.WQ.captionsLanguagePreference,g.T2(r.videoData,"yt:cc_default_lang")],e=!1,d=0;d<Y.length;d++){var K=Y[d];if(K){e=!0;for(var C=0;C<l.length;C++)if(g.iE(l[C])===K)return l[C];for(C=0;C<l.length;C++)if(g.iE(l[C]).split("-")[0]===K.split("-")[0])return l[C]}}if(e&&r.X&&(Y=r.X.U,Y.length))for(Y=g.Q(Y),
e=Y.next();!e.done;e=Y.next())if(e=e.value,e.languageCode===F){U=e;break}}else for(F=[r.videoData.captionsLanguagePreference,r.WQ.captionsLanguagePreference,g.T2(r.videoData,"yt:cc_default_lang")],Y=0;Y<F.length;Y++)for(e=0;e<l.length;e++)if(g.iE(l[e])===F[Y])return l[e];F=null;r.V&&r.V.L&&(F=r.V.L);F||(F=l.find(function(v){return v.isDefault})||null);
F||(F=l[0]||pE(r));F&&U&&g.iE(F).split("-")[0]!==U.languageCode.split("-")[0]&&(F=W9b(F,U));return F},pE=function(r){return r.V&&r.V.W},LE=function(r){var l=pE(r);
return!!l&&r.W===l},LW0=function(r,l){var U=r.C.dh().rR().textTracks;
r=r.W.toString();for(var F=0;F<U.length;F++){var Y=U[F];Y.id===r&&(l?Y.mode!=="showing"&&(Y.mode="showing"):Y.mode==="showing"&&(Y.mode="disabled"))}},kE=function(r,l,U){r.loaded&&r.unload();
U!=null&&(r.D=U,r.D&&(g.Oi(r.WQ)?cH(r,!!l):ay(r,!!l)));r.WQ.Y("html5_sends_cfs_after_caption_loaded")||r.WQ.Y("html5_sends_cfs_after_caption_parsed")?(l!==null||zO(r,!0)||Iy(r,null,l,r.D,!1),r.W=l,zO(r)&&(r.W=pE(r))):(Iy(r,r.W,l,r.D,!1),r.W=l,zO(r)&&(l=pE(r),Iy(r,r.W,l,r.D,!0),r.W=l));var F;c28(r,(F=r.W)!=null?F:void 0);r.load()},I8C=function(r,l){if(l instanceof GO){var U=r.KP[l.id];
U&&U.X!==l&&(U.dispose(),delete r.KP[l.id],U=null);U||(U=a80(r,l))&&(r.KP[l.id]=U)}else U=l.windowId,r.yT[U]||(r.yT[U]=[]),r.yT[U].push(l)},a80=function(r,l){var U=kkY(r);
if(!U)return null;var F=r.W?g.iE(r.W):null;F&&g.iyj.test(F)&&(l.params.TJ=1);var Y=r.W5.getPlayerSize();F=Y.height*r.sF.height;Y=Y.width*r.sF.width;r.WQ.playerStyle!=="google-live"||r.L.isDefault||Object.assign(l.params,r.L);switch(l.params.vz!=null?l.params.vz:l.W.length>1?1:0){case 1:return new HH(l,r.L,r.j,U.width,U.height,Y,F,r.WQ.experiments,r.Hp.bind(r),r.C);case 2:return new fE(l,r.L,r.j,U.width,U.height,Y,F,r.WQ.experiments,r.Hp.bind(r),r.C);default:return new An(l,r.L,r.j,U.width,U.height,
Y,F,r.WQ.experiments,r.Hp.bind(r),r.C)}},VD$=function(r,l,U){U=U===void 0?!1:U;
var F=os.RT;r.L={};Object.assign(r.L,os);r.L.RT={};Object.assign(r.L.RT,F);r.j={RT:{}};var Y=l.backgroundOverride?r.j:r.L,e=l.background||F.background;qV.test(e);Y.RT.background=e;Y=l.colorOverride?r.j:r.L;e=l.color||F.color;qV.test(e);Y.RT.color=e;Y=l.windowColorOverride?r.j:r.L;e=l.windowColor||os.windowColor;qV.test(e);Y.windowColor=e;Y=l.backgroundOpacityOverride?r.j:r.L;e=l.backgroundOpacity;e==null&&(e=F.backgroundOpacity);Y.RT.backgroundOpacity=e;Y=l.fontSizeIncrementOverride?r.j:r.L;e=l.fontSizeIncrement;
e==null&&(e=F.fontSizeIncrement);Y.RT.fontSizeIncrement=e;e=l.fontStyleOverride?r.j:r.L;Y=l.fontStyle;Y==null&&(Y=F.bold&&F.italic?3:F.bold?1:F.italic?2:0);e=e.RT;switch(Y){case 1:e.bold=!0;delete e.italic;break;case 2:delete e.bold;e.italic=!0;break;case 3:e.bold=!0;e.italic=!0;break;default:delete e.bold,delete e.italic}Y=l.textOpacityOverride?r.j:r.L;e=l.textOpacity;e==null&&(e=F.textOpacity);Y.RT.textOpacity=e;Y=l.windowOpacityOverride?r.j:r.L;e=l.windowOpacity;e==null&&(e=os.windowOpacity);Y.windowOpacity=
e;Y=l.charEdgeStyleOverride?r.j:r.L;e=l.charEdgeStyle;e==null&&(e=F.charEdgeStyle);Y.RT.charEdgeStyle=e;Y=l.fontFamilyOverride?r.j:r.L;e=l.fontFamily;e==null&&(e=F.fontFamily);Y.RT.fontFamily=e;r.loaded&&r.aU();U&&g.fS("yt-player-caption-display-settings",l,2592E3)},oY$=function(r,l){if(!r.X)return{};
if(l){g.aY(l)||r.cZ(l.vss_id,"m");if(r.U||!g.oY(l))return;if(g.aY(l)){kE(r,null,!0);return}for(var U,F=g.Yd(r.X.X,!0),Y=0;Y<F.length;Y++){var e=F[Y];e.languageCode!==l.languageCode||U&&(e.languageName!==l.languageName||(e.captionId||"")!==(l.captionId||"")||g.GP(e)!==l.displayName)||(U=l.translationLanguage?W9b(e,l.translationLanguage):e)}r.bz(l.position);!U||U===r.W&&r.loaded||(l=g.ek(),F=g.iE(U),l.length&&F===l[l.length-1]||(l.push(F),g.fS("yt-player-caption-language-preferences",l)),xKG(r.WQ)&&
!r.C.isInline()&&g.fS("yt-player-caption-sticky-language",F,2592E3),kE(r,U,!0))}else return r.loaded&&r.W&&!LE(r)?g.XY(r.W):{};return""},$5R=function(r,l,U){l&&!r.kN?(l=J2Y({TJ:0,
lang:"en-GB"}),r.kN=[l,new hn(l.start,l.end-l.start,0,l.id,U!=null?U:"Captions look like this")],r.player.sN(r.kN)):!l&&r.kN&&(ra8(r,r.kN),r.kN=null)},ra8=function(r,l){r.player.bl(l);
l=g.Q(l);for(var U=l.next();!U.done;U=l.next())g.sY(r.YN,U.value);Jn(r.iG)},c28=function(r,l){r.WQ.Y("html5_modify_caption_vss_logging")&&(r.videoData.Np=l)},kkY=function(r){var l=r.W5.getVideoContentRect(!0).height,U=r.W5.getVideoContentRect(!0).width;
if(!l||!U)return null;l*=r.sF.height;U*=r.sF.width;return{width:U,height:l}},ay=function(r,l){if(r.storage)try{r.storage.set("module-enabled",l)}catch(U){}},cH=function(r,l){r.C.isInline()||g.fS("yt-player-sticky-caption",l,2592E3)},SD8=function(r){if(!r.C.isInline())return g.SX("yt-player-sticky-caption")},Do0=function(r){var l,U=!((l=r.C.dh())==null||!l.Ha());
return r.Nh&&U&&r.K!=="LIVE"&&r.K!=="SABR_LIVE"},tD$=function(r,l){g.tp(r.videoData)&&(l=!0);
l||(l=r.K==="TTS"?!1:r.K==="INNERTUBE"?!1:!0);return l||r.WQ.Y("web_deprecate_always_includes_asr_setting")&&g.Oi(r.WQ)?!0:!!g.IW(g.aW(),66)},Iy=function(r,l,U,F,Y){r.WQ.Y("html5_sends_cfs_after_caption_loaded")||r.WQ.Y("html5_sends_cfs_after_caption_parsed")?r.Ec(U,!!U,Y?"g":F?"m":"s"):Y?r.Ec(U,!0,"g"):F?l?r.Ec(U,!!U,"m"):U&&r.Ec(U,!0,"m"):!l&&U&&r.Ec(U,!0,"s")};
g.n5.prototype.EY=g.FL(71,function(){return!1});
g.n5.prototype.Bm=g.FL(70,function(){});
g.Gi.prototype.Bm=g.FL(69,function(r,l,U){var F=this;this.QT();l=this.T6(r,l);var Y=this.jc.N().Y("html5_report_captions_ctmp_qoe"),e=(0,g.f)();this.Kb();MZG(this,l,{format:"RAW",onSuccess:function(d){F.W=null;if(Y){var K=(d.responseText.length/1024).toFixed(),C=(0,g.f)();F.videoData.pP("capresp",{ms:C-e,kb:K})}U.A7(d.responseText,r)},
onError:Y?function(d){var K;d=(K=d==null?void 0:d.status)!=null?K:0;F.videoData.pP("capfail",{status:d})}:void 0,
withCredentials:!0})});
g.id.prototype.Bm=g.FL(68,function(r,l,U){var F=this;this.QT();l=this.T6(r,l);this.Kb();this.W=g.Tj(l,{format:"RAW",onSuccess:function(Y){F.W=null;U.A7(Y.responseText,r)},
withCredentials:!0})});
g.c1.prototype.gx=g.FL(67,function(){for(var r=g.St(document,"track",void 0,this.W),l=0;l<r.length;l++)g.lD(r[l])});
g.gy.prototype.gx=g.FL(66,function(){this.mediaElement.gx()});
g.c1.prototype.k_=g.FL(65,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.gy.prototype.k_=g.FL(64,function(){return this.mediaElement.k_()});
g.c1.prototype.Ha=g.FL(63,function(){return!!this.W.textTracks});
g.gy.prototype.Ha=g.FL(62,function(){return this.mediaElement.Ha()});
g.c1.prototype.C5=g.FL(61,function(r){for(var l=0;l<r.length;l++)this.W.appendChild(r[l])});
g.gy.prototype.C5=g.FL(60,function(r){this.mediaElement.C5(r)});
g.lA.prototype.XE=g.FL(59,function(r,l,U){this.NS.XE(r,l,U)});
g.ke.prototype.XE=g.FL(58,function(r,l,U){this.X.set(r,{uv:l,cC:U})});
g.oH.prototype.XE=g.FL(57,function(r,l,U){this.rz.XE(r,l,U)});
g.lA.prototype.dD=g.FL(56,function(r){return this.NS.dD(r)});
g.oH.prototype.dD=g.FL(55,function(r){var l=2;this.j.has(r)?l=0:g.Jo3(this,r)&&(l=1);return l});
g.yy.prototype.oi=g.FL(43,function(r){var l=this.app.Gn({playerType:void 0});return l?l.oi(r):!1});
g.a4.prototype.oi=g.FL(42,function(r){return this.HQ.OM.oi(r)});
g.y8.prototype.oi=g.FL(41,function(r){return this.My().some(function(l){return l.namespace===r})});
g.SI.prototype.oi=g.FL(40,function(){return!1});
g.yy.prototype.cZ=g.FL(38,function(r,l){this.app.fP().cZ(r,l)});
g.a4.prototype.cZ=g.FL(37,function(r,l){this.HQ.cZ(r,l)});
g.Q8.prototype.cZ=g.FL(36,function(r,l){r=[r,l];g.Wj(this,g.$S(this.provider),"cfi",r)});
g.uA.prototype.cZ=g.FL(35,function(r,l){this.qoe&&this.qoe.cZ(r,l)});
g.Yv.prototype.cZ=g.FL(34,function(r,l){this.Gf.cZ(r,l)});
g.SI.prototype.cZ=g.FL(33,function(){});
g.yy.prototype.Ec=g.FL(32,function(r,l,U){this.app.fP().Ec(r,l,U)});
g.a4.prototype.Ec=g.FL(31,function(r,l,U){this.HQ.Ec(r,l,U)});
g.Q8.prototype.Ec=g.FL(30,function(r,l,U){if(this.iG!==r||this.c5!==l)l=l==="rawcc"?"":l,U=[r,l,this.iG,U],g.Wj(this,g.$S(this.provider),"cfs",U),this.iG=r,this.c5=l});
g.uA.prototype.Ec=g.FL(29,function(r,l,U){this.qoe&&this.qoe.Ec(r,l,U)});
g.Yv.prototype.Ec=g.FL(28,function(r,l,U){this.Gf.Ec(r,l,U)});
g.SI.prototype.Ec=g.FL(27,function(){});
g.rj.prototype.jp=g.FL(12,function(){return this.kN});
g.QP.prototype.jp=g.FL(11,function(){return this.fP().a7()});
g.yy.prototype.a7=g.FL(10,function(){return this.app.jp()});
g.a4.prototype.a7=g.FL(9,function(){return this.HQ.a7()});
g.Yv.prototype.a7=g.FL(8,function(){var r;return((r=this.loader)==null?void 0:r.jp())||null});
g.SI.prototype.a7=g.FL(7,function(){return null});
g.LU.prototype.Xh=g.FL(1,function(r){return(r=this.iW(r))?r.W:0});
g.hV.prototype.Xh=g.FL(0,function(){return 0});
var RBp=/#(.)(.)(.)/,ZXq=/^#(?:[0-9a-f]{3}){1,2}$/i,jqb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};m7.prototype.contains=function(r){r=g.Xq(this.segments,r);return r>=0||r<0&&(-r-1)%2===1};
m7.prototype.length=function(){return this.segments.length/2};
g.W(iX8,g.H);g.x=iX8.prototype;g.x.Rf=function(){g.H.prototype.Rf.call(this);this.L&&this.L.cancel()};
g.x.xZ=function(){this.seekTo(this.player.getCurrentTime())};
g.x.seekTo=function(r){r-=this.player.EL();var l=this.W;this.W=g.Cr(this.kN.G6(r).BQ);l!==this.W&&this.V&&this.V()};
g.x.reset=function(){this.K=new m7;this.D=-1;this.L&&(this.L.cancel(),this.L=null)};
g.x.z1=function(){this.QT();var r;if(r=this.W!=null)r=this.W,r=r.W.Bx(r);if(r&&!this.L&&!(this.W&&this.W.startTime-this.player.getCurrentTime()>30)){r=this.W;r=r.W.T0(r);var l=r.BQ[0],U;if((U=this.player.getVideoData())==null?0:U.enableServerStitchedDai)if(U=this.player.a7()){var F=l.W.info.id,Y=l.xN,e=r.BQ[0].K;if(this.policy.YN){if(U=U.K7(e,Y,F,3))r.K=U}else if(F=U.UW(e,Y,F,3))if(U=U.dD(Y),U===0)F&&(r.W=new g.wz(F));else if(U===2){this.j.start();bXr(this)&&this.seekTo(this.player.getCurrentTime());
return}}l.W.index.Gz(l.xN)?(this.K.contains(r.BQ[0].xN)||NCr(this,r),this.W=g.Cr(r.BQ)):bXr(this)&&this.seekTo(this.player.getCurrentTime())}this.j.start()};
g.W(PH,g.n5);g.x=PH.prototype;g.x.Bm=function(r,l,U){var F=this;this.Kb();l=TCR(this,r.getId());l||(l=r.languageCode,l=this.W.isManifestless?u8p(this,l,"386"):u8p(this,l));if(l){var Y=(l.index.Xh(l.index.Yr())-l.index.getStartTime(l.index.Yr()))*1E3,e=this.C.N(),d=new g.Jh4(e),K=function(){F.L&&F.L.reset();F.D=!0};
e.Y("html5_keep_caption_data_after_seek")&&(K=null);this.L=new iX8(d,this.C,l,function(C,v){U.A7(C,r,v,Y)},this.j||g.Kb(l.info),K)}};
g.x.EY=function(){var r=this.D;this.D=!1;return r};
g.x.XO=function(r){var l=this.C.N().Y("html5_fallback_if_rawcc_missing");var U=this.W.W.rawcc!=null;if(!this.j||!U&&l)l=this.W.isManifestless?q$0(this,"386"):q$0(this);else{if(!U){this.logger.W(386248249,"rawcc used but unavailable");return}l=[new g.nf({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.nf({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}l=g.Q(l);
for(U=l.next();!U.done;U=l.next())g.hQ(this.X,U.value);r.by()};
g.x.Kb=function(){this.L&&(this.L.dispose(),this.L=null)};
g.x.T6=function(){return""};
g.x.BS=function(){this.L&&(this.L.reset(),this.C.MB("captions"))};
var qV=/^#(?:[0-9a-f]{3}){1,2}$/i;var HX0=["left","right","center","justify"];g.W(An,g.p);g.x=An.prototype;g.x.oP=function(r,l){this.Nh=r;this.lG=l;var U=g.qx(this.element,this.element.parentElement);this.If=r-U.x;this.W5=l-U.y};
g.x.z_=function(r,l){if(r!==this.Nh||l!==this.lG){g.mJ(this.element,"ytp-dragging")||g.Pl(this.element,"ytp-dragging");var U=g.uD(this.element);r=r-this.If-.02*this.bI;var F=l-this.W5-.02*this.P5,Y=(r+U.width/2)/this.maxWidth*3;Y=Math.floor(g.Ge(Y,0,2));var e=(F+U.height/2)/this.maxHeight*3;e=Math.floor(g.Ge(e,0,2));l=Y+e*3;r=(r+Y/2*U.width)/this.maxWidth;r=g.Ge(r,0,1)*100;U=(F+e/2*U.height)/this.maxHeight;U=g.Ge(U,0,1)*100;this.X.params.pK=l;this.X.params.Lb=U;this.X.params.wU=r;this.X.params.isDefault=
!1;this.W.pK=l;this.W.Lb=U;this.W.wU=r;this.W.isDefault=!1;this.sF.pK=l;this.sF.Lb=U;this.sF.wU=r;this.sF.isDefault=!1;this.kX()}};
g.x.NT=function(){g.M0(this.element,"ytp-dragging")};
g.x.kX=function(){this.j8(this.j)};
g.x.j8=function(r){var l=this.kq?0:Math.min(this.RX(),this.maxWidth),U=this.Xf(),F=this.kq;if(F){var Y=getComputedStyle(this.K.parentNode);Y=MV(Y.borderLeftWidth)+MV(Y.borderRightWidth)+MV(Y.paddingLeft)+MV(Y.paddingRight)}else Y=0;var e=Y;Y="";this.X.params.TJ===3&&(Y="rotate(180deg)");var d=F?"calc(96% - "+e+"px)":"96%";g.RI(this.element,{top:0,left:0,right:"",bottom:"",width:l?l+"px":"",height:U?U+"px":"","max-width":d,"max-height":d,margin:"",transform:""});this.VU(r);Y={transform:Y,top:"",left:"",
width:l?l+"px":"",height:U?U+"px":"","max-width":"","max-height":""};var K=this.W.wU*.96+2;d=this.W.pK;switch(d){case 0:case 3:case 6:(F=this.W.RT.fontSizeIncrement)&&F>0&&this.W.TJ!==2&&this.W.TJ!==3&&(K=Math.max(K/(1+F*2),2));Y.left=K+"%";break;case 1:case 4:case 7:Y.left=K+"%";K=this.K.offsetWidth;l||K?(l=l||K+1,Y.width=l+"px",Y["margin-left"]=F?l/-2-e/2+"px":l/-2+"px"):Y.transform+=" translateX(-50%)";break;case 2:case 5:case 8:Y.right=100-K+"%"}F=this.W.Lb*.96+2;switch(d){case 0:case 1:case 2:Y.top=
F+"%";break;case 3:case 4:case 5:Y.top=F+"%";(U=U||this.element.clientHeight)?(Y.height=U+"px",Y["margin-top"]=U/-2+"px"):Y.transform+=" translateY(-50%)";break;case 6:case 7:case 8:Y.bottom=100-F+"%"}g.RI(this.element,Y);if(this.D){U=this.K.offsetHeight;F=1;for(l=0;l<r.length;l++)Y=r[l],typeof Y.text==="string"&&(F+=Y.text.split("\n").length-1,Y.append||l===0||F++);U/=F;this.D.style.height=U+"px";this.D.style.width=U+"px";this.element.style.paddingLeft=U+5+"px";this.element.style.paddingRight=U+
5+"px";r=Number(this.element.style.marginLeft.replace("px",""))-U-5;U=Number(this.element.style.marginRight.replace("px",""))-U-5;this.element.style.marginLeft=r+"px";this.element.style.marginRight=U+"px"}};
g.x.VU=function(r){var l;for(l=0;l<r.length&&r[l]===this.j[l];l++);if(this.qh||this.j.length>l)l=0,this.qh=!1,this.j=[],this.T=this.iG=this.YN=null,g.rA(this.K);for(;l<r.length;l++)fAr(this,r[l])};
g.x.RX=function(){return 0};
g.x.Xf=function(){return 0};
g.x.toString=function(){return g.p.prototype.toString.call(this)};zBr.prototype.clear=function(){this.L=this.time=this.mode=0;this.W=[];this.reset()};
zBr.prototype.reset=function(){this.mode=0;this.K.reset(0);this.U.reset(1)};
var p_R=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];sl.prototype.set=function(r){this.type=r};
sl.prototype.get=function(){return this.type};
xE.prototype.clear=function(){this.state=0};
xE.prototype.update=function(){this.state=this.state===2?1:0};
xE.prototype.NB=function(){return this.state!==0};
xE.prototype.matches=function(r,l){return this.NB()&&r===this.IK&&l===this.XA};
IAq.prototype.reset=function(){this.timestamp=this.W=0};
WH.prototype.updateTime=function(r){for(var l=1;l<=15;++l)for(var U=1;U<=32;++U)this.L[l][U].timestamp=r};
WH.prototype.debugString=function(){for(var r="\n",l=1;l<=15;++l){for(var U=1;U<=32;++U){var F=this.L[l][U];r=F.W===0?r+"_":r+String.fromCharCode(F.W)}r+="\n"}return r};
WH.prototype.reset=function(r){for(var l=0;l<=15;l++)for(var U=0;U<=32;U++)this.L[l][U].reset();this.K=r;this.W=0;this.X=this.row=1};
var kcq=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ojY=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],r2C=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],$or=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];YDb.prototype.reset=function(r,l){this.U=l;this.style.set(2);this.X=this.D;this.K=this.j;this.W=this.X;var U=(r<<2)+(l<<1);this.D.reset(U);this.j.reset(U);this.text.reset((r<<2)+(l<<1)+1)};
S$q.prototype.reset=function(r){this.U=r;this.X.clear();this.K=this.L;this.L.reset(r,0);this.D.reset(r,1)};KW8.prototype.K=function(){};g.W(hn,g.M2);hn.prototype.toString=function(){return g.M2.prototype.toString.call(this)};g.W(nE,g.H);nE.prototype.reset=function(){};g.W(GO,g.M2);GO.prototype.toString=function(){return g.M2.prototype.toString.call(this)};
var XK=0;g.W(iv,nE);iv.prototype.reset=function(){this.j={};this.X=this.W=null;this.D=!0};
iv.prototype.L=function(r,l){r=r.firstChild;r.getAttribute("format");l=l||0;Number.isFinite(l);r=Array.from(r.childNodes);r=g.Q(r);for(var U=r.next();!U.done;U=r.next())if(U=U.value,U.nodeType===1)switch(U.tagName){case "head":var F=U;break;case "body":var Y=U}if(F)for(F=Array.from(F.childNodes),F=g.Q(F),r=F.next();!r.done;r=F.next())if(r=r.value,r.nodeType===1)switch(r.tagName){case "pen":U=r.getAttribute("id");var e=this.pens,d={},K=r.getAttribute("p");K&&Object.assign(d,this.pens[K]);K=NV(r,"b");
K!=null&&(d.bold=K);K=NV(r,"i");K!=null&&(d.italic=K);K=NV(r,"u");K!=null&&(d.underline=K);K=jr(r,"et");K!=null&&(d.charEdgeStyle=K);K=jr(r,"of");K!=null&&(d.offset=K);K=TO(r,"bc");K!=null&&(d.background=K);K=TO(r,"ec");K!=null&&(d.qv=K);K=TO(r,"fc");K!=null&&(d.color=K);K=jr(r,"fs");K!=null&&K!==0&&(d.fontFamily=K);K=bv(r,"sz");K!==void 0&&(d.fontSizeIncrement=K/100-1);K=bv(r,"bo");K!==void 0&&(d.backgroundOpacity=K/255);K=bv(r,"fo");K!==void 0&&(d.textOpacity=K/255);K=jr(r,"rb");K!=null&&K!==10&&
K!==0&&(d.rK=K>10?K-1:K);r=jr(r,"hg");r!=null&&(d.kU=r);e[U]=d;break;case "ws":U=r.getAttribute("id");this.V[U]=moY(this,r);break;case "wp":U=r.getAttribute("id"),this.T[U]=Pe$(this,r)}if(Y){F=[];Y=Array.from(Y.childNodes);Y=g.Q(Y);for(r=Y.next();!r.done;r=Y.next())if(r=r.value,r.nodeType===1)switch(r.tagName){case "w":this.W=A2R(this,r,l,!1);(r=this.j[this.W.id])&&r.end>this.W.start&&(r.end=this.W.start);this.j[this.W.id]=this.W;F.push(this.W);break;case "p":var C=r;K=l;U=[];e=C.getAttribute("w")||
this.U;d=!!NV(C,"a");K=(bv(C,"t")||0)+K;var v=bv(C,"d")||5E3;d||(!this.D&&this.X&&this.X.windowId===e&&this.X.end>K&&(this.X.end=K),this.X&&this.X.text==="\n"&&(this.X.text=""));var J=d?6:5,m=C.getAttribute("p");m=m?this.pens[m]:null;var P=Array.from(C.childNodes);P.length&&(this.D=C.getAttribute("d")!=null);for(C=0;C<P.length;C++){var A=P[C],M=void 0;C>0&&(d=!0);var E=void 0;A.nodeType===1&&(E=A);if(E&&E.tagName==="s"){if((A=(A=E.getAttribute("p"))?this.pens[A]:null)&&A.rK&&(A.rK===1?(A=P.slice(C,
C+4),A.length===4&&(M=vjY(K,v,e,d,J,A,this.pens),C+=3)):M=vjY(K,v,e,d,J,[E],this.pens)),!M){var Z=E;M=K;E=v;A=e;var n=d,h=J,N=Z.textContent?Z.textContent:"",u=Z.getAttribute("p");u=u?this.pens[u]:null;Z=bv(Z,"t")||0;M=new hn(M+Z,E-Z,h,A,N,n,u)}}else M=new hn(K,v,J,e,A.textContent||"",d,m);U.push(M);this.X=M}if(U.length>0)for(U[0].windowId===this.U&&(this.W=A2R(this,r,l,!0),F.push(this.W)),r=g.Q(U),U=r.next();!U.done;U=r.next())U=U.value,U.windowId=this.W.id,this.W.W.push(U),F.push(U)}l=F}else l=[];
return l};var lLq=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.W(uv,nE);uv.prototype.reset=function(){this.X.clear()};
uv.prototype.L=function(r,l){var U=JSON.parse(r);if(!U)return[];if(U.pens){r=0;for(var F=g.Q(U.pens),Y=F.next();!Y.done;Y=F.next()){Y=Y.value;var e={},d=Y.pParentId;d&&Object.assign(e,this.W.get(d));Y.bAttr&&(e.bold=!0);Y.iAttr&&(e.italic=!0);Y.uAttr&&(e.underline=!0);d=Y.ofOffset;d!=null&&(e.offset=d);Y.szPenSize!==void 0&&(e.fontSizeIncrement=Y.szPenSize/100-1);d=Y.etEdgeType;d!=null&&(e.charEdgeStyle=d);Y.ecEdgeColor!==void 0&&(e.qv=yo(Y.ecEdgeColor));d=Y.fsFontStyle;d!=null&&d!==0&&(e.fontFamily=
d);Y.fcForeColor!==void 0&&(e.color=yo(Y.fcForeColor));Y.foForeAlpha!==void 0&&(e.textOpacity=Y.foForeAlpha/255);Y.bcBackColor!==void 0&&(e.background=yo(Y.bcBackColor));Y.boBackAlpha!==void 0&&(e.backgroundOpacity=Y.boBackAlpha/255);(d=Y.rbRuby)&&d!==10&&(e.rK=d>10?d-1:d,e.textEmphasis=lLq.get(e.rK));Y.hgHorizGroup&&(e.kU=Y.hgHorizGroup);this.W.set(r++,e)}}if(U.wsWinStyles)for(r=0,F=g.Q(U.wsWinStyles),Y=F.next();!Y.done;Y=F.next())Y=Y.value,e={},(d=Y.wsParentId)?Object.assign(e,this.U.get(d)):Object.assign(e,
this.D),Y.mhModeHint!==void 0&&(e.vz=Y.mhModeHint),Y.juJustifCode!==void 0&&(e.textAlign=Y.juJustifCode),Y.pdPrintDir!==void 0&&(e.TJ=Y.pdPrintDir),Y.sdScrollDir!==void 0&&(e.L_=Y.sdScrollDir),Y.wfcWinFillColor!==void 0&&(e.windowColor=yo(Y.wfcWinFillColor)),Y.wfoWinFillAlpha!==void 0&&(e.windowOpacity=Y.wfoWinFillAlpha/255),this.U.set(r++,e);if(U.wpWinPositions)for(r=0,F=g.Q(U.wpWinPositions),Y=F.next();!Y.done;Y=F.next())Y=Y.value,e={},(d=Y.wpParentId)&&Object.assign(e,this.K.get(d)),Y.ahHorPos!==
void 0&&(e.wU=Y.ahHorPos),Y.apPoint!==void 0&&(e.pK=Y.apPoint),Y.avVerPos!==void 0&&(e.Lb=Y.avVerPos),Y.ccCols!==void 0&&(e.KW=Y.ccCols),Y.rcRows!==void 0&&(e.UH=Y.rcRows),this.K.set(r++,e);if(U.events){r=[];U=g.Q(U.events);for(F=U.next();!F.done;F=U.next()){var K=F.value;Y=(K.tStartMs||0)+l;e=K.dDurationMs||0;if(K.id)d=String(K.id),F=MDC(this,K,Y,e,d),r.push(F),this.X.set(d,F);else{K.wWinId?d=K.wWinId.toString():(d="_"+XK++,F=MDC(this,K,Y,e,d),r.push(F),this.X.set(d,F));F=r;var C=K;e===0&&(e=5E3);
K=this.X.get(d);var v=!!C.aAppend,J=v?6:5,m=C.segs,P=null;C.pPenId&&(P=this.W.get(C.pPenId));for(C=0;C<m.length;C++){var A=m[C],M=A.utf8;if(M){var E=A.tOffsetMs||0,Z=null;A.pPenId&&(Z=this.W.get(A.pPenId));if((K.params.vz!=null?K.params.vz:K.W.length>1?1:0)===2&&v&&M==="\n")continue;A=null;var n=[],h;if(h=Z&&Z.rK===1){h=m;var N=C;if(N+3>=h.length||!h[N+1].pPenId||!h[N+2].pPenId||!h[N+3].pPenId)h=!1;else{var u=h[N+1].pPenId;(u=this.W.get(u))&&u.rK&&u.rK===2?(u=h[N+2].pPenId,u=this.W.get(u),!u||!u.rK||
u.rK<3?h=!1:(u=h[N+3].pPenId,h=(u=this.W.get(u))&&u.rK&&u.rK===2?!0:!1)):h=!1}}if(h)E=m[C+1].utf8,A=m[C+3].utf8,h=m[C+2].utf8,N=this.W.get(m[C+2].pPenId),M=Ce8(M,E,h,A,N),A=new hn(Y,e,J,d,M,v,Z),C+=3;else{if(M.indexOf("<")>-1){var D=void 0;n=Z;h=P;N=Y;u=e;var t=E,z=J,I=v,U4=[],$$=g.o6("<html>"+M+"</html>");if(!$$.getElementsByTagName("parsererror").length&&((D=$$.firstChild)==null?0:D.childNodes.length))for(D=g.Q($$.firstChild.childNodes),$$=D.next();!$$.done;$$=D.next()){$$=$$.value;var Y$=void 0,
L=void 0,Ae=(L=(Y$=$$.textContent)==null?void 0:Y$.replace(/\n/g,""))!=null?L:"";if($$.nodeType!==3||Ae&&Ae.match(/^ *$/)==null){Y$={};Object.assign(Y$,n||h);L=void 0;switch((L=$$)==null?void 0:L.tagName){case "b":Y$.bold=!0;break;case "i":Y$.italic=!0;break;case "u":Y$.underline=!0}U4.push(new hn(N+t,u-t,z,K.id,Ae,I,Y$))}}n=U4}n.length||(n=[new hn(Y+E,e-E,J,K.id,M,v,Z||P)])}if(n.length)for(v=g.Q(n),Z=v.next();!Z.done;Z=v.next())Z=Z.value,F.push(Z),K.W.push(Z);else A&&(F.push(A),K.W.push(A))}v=!0}}}l=
r}else l=[];return l};g.W(BH,g.n5);BH.prototype.Bm=function(r,l,U){EPY(this.videoData.videoId,r.vssId,U.A7)};
BH.prototype.XO=function(r){if(this.audioTrack)for(var l=g.Q(this.audioTrack.captionTracks),U=l.next();!U.done;U=l.next())g.hQ(this.X,U.value);r.by()};g.W(HH,An);HH.prototype.VU=function(r){var l=this.X.W;An.prototype.VU.call(this,r);for(r=r.length;r<l.length;r++){var U=l[r];if(e&&U.W===Y)var F=e;else{F={};Object.assign(F,U.W);Object.assign(F,U5b);var Y=U.W;var e=F}fAr(this,U,F)}};
var U5b={zY:!0};g.W(g9,KW8);g9.prototype.K=function(r,l,U,F,Y){if(U<F){var e="_"+XK++;U=U/1E3-this.D;F=F/1E3-this.D;r=new GO(U,F-U,5,e,{textAlign:0,pK:0,wU:l*2.5,Lb:r*5.33});Y=new hn(U,F-U,5,e,Y);this.X.push(r);this.X.push(Y)}};
g.W(Vo,nE);Vo.prototype.L=function(r){r=new g9(r,r.byteLength,this.X);if(s9Y(r)){for(;r.byteOffset<r.W.byteLength;)for(r.version===0?r.L=DD(r)*(1E3/45):r.version===1&&(r.L=DD(r)*4294967296+DD(r)),r.U=w9(r);r.U>0;r.U--){var l=w9(r),U=w9(r),F=w9(r);l&4&&(l&3)===this.track&&(this.track===0||this.track===1)&&(l=this.W,l.W.push({time:r.L,type:this.track,hc:U,VQ:F,order:l.W.length}))}aAY(this.W,r);return r.X}return[]};
Vo.prototype.reset=function(){this.W.clear()};g.W(fE,An);g.x=fE.prototype;g.x.kX=function(){g.eb(this.Kp)};
g.x.LU=function(){this.element.removeEventListener("transitionend",this.LU,!1);g.M0(this.element,"ytp-rollup-mode");this.j8(this.SN,!0)};
g.x.Xf=function(){return this.L?this.kN:this.V};
g.x.RX=function(){return this.L?this.V:this.kN};
g.x.j8=function(r,l){this.SN=r;if(this.X.params.UH){for(var U=0,F=0;F<this.j.length&&U<r.length;F++)this.j[F]===r[U]&&U++;U>0&&U<r.length&&(r=this.j.concat(r.slice(U)));this.Rg=this.kN;this.V=this.kN=0;An.prototype.j8.call(this,r);Ejb(this,l)}An.prototype.j8.call(this,r)};ZMC.prototype.unload=function(){this.W!=null&&(this.C.removeEventListener("sabrCaptionsDataLoaded",this.W),this.W=null);this.L1=[];this.C.publish("sabrCaptionsBufferedRangesUpdated",this.L1)};
ZMC.prototype.x$=function(r){return{formatId:g.v8(r.info.W.info,this.Yq),xN:r.info.xN+(this.Yq?0:1),startTimeMs:r.info.K*1E3,durationMs:r.info.j*1E3}};g.W(Gkj,g.n5);g.x=Gkj.prototype;g.x.Bm=function(r,l,U){this.Kb();l=r.getId();l=l!=null&&l in this.W.W?this.W.W[l]:null;l||(l=r.languageCode,l=this.W.isManifestless?iMC(this,l,"386"):iMC(this,l));l&&(this.L=r,this.D=l,njG(this.j,U),this.C.publish("sabrCaptionsTrackChanged",g.v8(l.info,this.W.Yq)))};
g.x.XO=function(r){var l=this.W.isManifestless?XDj(this,"386"):XDj(this);l=g.Q(l);for(var U=l.next();!U.done;U=l.next())g.hQ(this.X,U.value);r.by()};
g.x.Kb=function(){this.L&&(this.L=this.D=null,this.j.unload(),this.C.publish("sabrCaptionsTrackChanged",null))};
g.x.T6=function(){return""};
g.x.BS=function(){this.C.MB("captions")};var j9Y="WEBVTT".split("").map(function(r){return r.charCodeAt(0)});
g.W(N08,nE);
N08.prototype.L=function(r,l){r instanceof ArrayBuffer&&(r=g.D0(new Uint8Array(r)));var U=[];r=r.split(FTr);for(var F=1;F<r.length;F++){var Y=r[F],e=l;if(Y!==""&&!YV8.test(Y)){var d=eQC.exec(Y);if(d&&d.length>=4){var K=uAr(d[1]),C=uAr(d[2])-K;K+=e;var v=(d=d[3])?d.split(" "):[];d={};var J=null;var m="";var P=null,A="";v=g.Q(v);for(var M=v.next();!M.done;M=v.next())if(M=M.value.split(":"),M.length===2){var E=M[1];switch(M[0]){case "line":M=E.split(",");M[0].endsWith("%")&&(J=M[0],d.Lb=Number.parseInt(J,
10),M.length===2&&(m=M[1].trim()));break;case "position":M=E.split(",");P=M[0];d.wU=Number.parseInt(P,10);M.length===2&&(A=M[1].trim());break;case "align":switch(E){case "start":d.textAlign=0;break;case "middle":d.textAlign=2;break;case "end":d.textAlign=1}}}J||m||(m="end");if(!P)switch(d.textAlign){case 0:d.wU=0;break;case 1:d.wU=100;break;case 2:d.wU=50}if(d.textAlign!=null){J=0;switch(m){case "center":J+=3;break;case "end":J+=6;break;default:J+=0}switch(A){case "line-left":J+=0;break;case "center":J+=
1;break;case "line-right":J+=2;break;default:switch(d.textAlign){case 0:J+=0;break;case 2:J+=1;break;case 1:J+=2}}m=J<0||J>8?7:J;d.pK=m}Y=Y.substring(eQC.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");A=d;d=Y;Y={};if(d.indexOf("<")<0&&d.indexOf("&")<0)e=y2p(K,C,5,A),C=new hn(K,C,5,e.id,d,!1,g.aY(Y)?void 0:Y),U.push(e),U.push(C),e.W.push(C);else for(m=d.split(d5Y),m.length===1?(d=5,A=y2p(K,C,d,A)):(J=d=6,A=Object.assign({KW:32},A),A=new GO(K,C,J,"_"+XK++,A)),U.push(A),J=K,P=0;P<m.length;P++)v=m[P],
P%2===0?(M=g.o6("<html>"+v+"</html>"),M.getElementsByTagName("parsererror").length?(E=M.createElement("span"),E.appendChild(M.createTextNode(v))):E=M.firstChild,T08(this,J,C-(J-K),d,A,P>0,E,Y,U)):J=uAr(v)+e}eQC.lastIndex=0}}return U};
var YV8=/^NOTE/,FTr=/(?:\r\n|\r|\n){2,}/,eQC=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),d5Y=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.W(Sr,g.H);Sr.prototype.clear=function(){this.W&&this.W.dispose();this.W=null};
Sr.prototype.reset=function(){this.W&&this.W.reset()};
Sr.prototype.Rf=function(){g.H.prototype.Rf.call(this);this.clear()};var os={windowColor:"#080808",windowOpacity:0,textAlign:2,pK:7,wU:50,Lb:100,isDefault:!0,RT:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.W(f8Y,g.Rf);g.x=f8Y.prototype;g.x.Rf=function(){if(this.U||this.rz){var r=this.C.dh();r&&!r.QT()&&r.gx()}else $5R(this,!1);g.Rf.prototype.Rf.call(this)};
g.x.NF=function(){return this.WQ.Y("html5_honor_caption_availabilities_in_audio_track")&&this.K!=="LIVE"&&this.K!=="SABR_LIVE"};
g.x.J7=function(){if(this.Nh)return this.U||this.rz;var r=this.getAudioTrack();if(this.NF()){if(!r.captionTracks.length)return!1;if(!this.X)return!0}r=sq8(r,g.Oi(this.WQ));return r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?zO(this):zLb(this)||zO(this)?!0:pDC(this)};
g.x.load=function(){g.Rf.prototype.load.call(this);this.V=this.getAudioTrack();if(this.X)this.W&&(this.lG.clear(),this.U?LW0(this,!0):this.player.getPresentingPlayerType()!==3&&this.X.Bm(this.W,"json3",this.Kp),this.U||this.rz||LE(this)||this.player.mx("captionschanged",g.XY(this.W)));else{var r;this.K==="OFFLINE"?r=new BH(this.player,this.videoData,this.getAudioTrack()):this.K==="SABR_LIVE"?r=new Gkj(this.videoData.W,this.player):this.K==="LIVE"?r=new PH(this.videoData.W,this.player):this.K==="INNERTUBE"?
r=new g.Gi(this.player,this.videoData,this.getAudioTrack()):r=new g.id(this.player,this.videoData.Wl,this.videoData.videoId,g.BhL(this.videoData),this.videoData.Pq,this.videoData.eventId);this.X=r;g.w(this,this.X);this.X.XO(this.Kp)}};
g.x.unload=function(){this.U&&this.W?LW0(this,!1):(this.OF&&g.dQ(this.OF),this.player.MB("captions"),this.YN=[],this.X&&this.X.Kb(),this.lG.clear(),this.kN&&this.player.sN(this.kN),this.aU());g.Rf.prototype.unload.call(this);this.player.l$();this.player.mx("captionschanged",{})};
g.x.create=function(){this.J7()&&this.load();var r;a:{var l,U,F;if(this.WQ.Y("web_player_nitrate_promo_tooltip")&&((l=this.videoData.getPlayerResponse())==null?0:(U=l.captions)==null?0:(F=U.playerCaptionsTracklistRenderer)==null?0:F.enableTouchCaptionsNitrate)){var Y,e;if(l=(r=this.videoData.getPlayerResponse())==null?void 0:(Y=r.captions)==null?void 0:(e=Y.playerCaptionsTracklistRenderer)==null?void 0:e.captionTracks)for(r=g.Q(l),Y=r.next();!Y.done;Y=r.next())if(Y=Y.value,Y.kind==="asr"&&Y.languageCode===
"en"){r=!0;break a}}r=!1}r&&this.C.publish("showpromotooltip",this.T.element)};
g.x.by=function(){var r=sq8(this.player.getAudioTrack(),g.Oi(this.WQ));var l=r==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?tn(this,this.D):r==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&zO(this)?pE(this):zLb(this)||this.D||pDC(this)?tn(this,this.D):zO(this)?pE(this):null;if(this.U||this.rz){var U=g.Yd(this.X.X,!0);r=[];for(var F=0;F<U.length;F++){var Y=U[F],e=g.I1("TRACK");e.setAttribute("kind","subtitles");e.setAttribute("label",g.GP(Y));e.setAttribute("srclang",g.iE(Y));e.setAttribute("id",Y.toString());
this.rz||e.setAttribute("src",this.X.T6(Y,"vtt"));Y===l&&e.setAttribute("default","1");r.push(e)}l=this.C.dh();l.C5(r);r=l.rR();this.kq&&this.qh.G(r.textTracks,"change",this.KtG)}else!this.W&&l&&kE(this,l),this.player.mx("onCaptionsTrackListChanged"),this.player.aT("onApiChange")};
g.x.KtG=function(){for(var r=this.C.dh().rR().textTracks,l=null,U=0;U<r.length;U++)if(r[U].mode==="showing")a:{l=g.Yd(this.X.X,!0);for(var F=0;F<l.length;F++)if(l[F].toString()===r[U].id){l=l[F];break a}l=null}(this.loaded?this.W:null)!==l&&kE(this,l,!0)};
g.x.TKF=function(){!this.W&&this.U||this.unload()};
g.x.A7=function(r,l,U,F){if(r){var Y;c28(this,(Y=this.W)!=null?Y:void 0);this.WQ.Y("html5_sends_cfs_after_caption_loaded")&&Iy(this,null,this.W,this.D,LE(this));this.X.EY()&&(this.YN=[],this.C.MB("captions"),Jn(this.iG),this.lG.reset());a:{Y=this.lG;F=F||0;U=HMr(Y,r,U||0);r=[];try{for(var e=g.Q(U),d=e.next();!d.done;d=e.next()){var K=d.value,C=K.trackData,v=K.DT,J=Y.WQ.Y("safari_live_drm_captions_fix");if(typeof C!=="string"){U=r;var m=U.concat;if(J&&qD8(C))var P=gjG(Y,C,v);else{var A=Y,M=l,E=C,Z=
v,n=F;if(!xo8(E))throw Error("Invalid binary caption track data");A.W||(A.W=new Vo(n,M));P=A.W.L(E,Z)}var h=m.call(U,P)}else{if(C.substring(0,6)==="WEBVTT")var N=r.concat(gjG(Y,C,v));else{U=r;var u=U.concat;b:{M=A=void 0;E=Y;Z=l;if(C[0]==="{")try{E.W||(E.W=new uv(wDj(Z)));var D=M=E.W.L(C,v);break b}catch(L){g.zz(L);D=[];break b}var t=g.o6(C);if(!t||!t.firstChild){var z=Error("Invalid caption track data");z.params=C;throw z;}if(t.firstChild.tagName==="timedtext"){if(Number(t.firstChild.getAttribute("format"))===
3){E.W||(E.W=new iv(wDj(Z),E.WQ));D=A=E.W.L(t,v);break b}var I=Error("Unsupported subtitles format in web player (Format2)");I.params=C;throw I;}if(t.firstChild.tagName==="transcript"){var U4=Error("Unsupported subtitles format in web player (Format1)");U4.params=C;throw U4;}var $$=Error("Invalid caption track data");$$.params=C;throw $$;}N=u.call(U,D)}h=N}r=h}var Y$=r;break a}catch(L){Y.logger.W(187101178,"Captions parsing failed: "+L.message+". ");Y.clear();Y$=[];break a}Y$=void 0}l=Y$;this.WQ.Y("html5_sends_cfs_after_caption_parsed")&&
!this.WQ.Y("html5_sends_cfs_after_caption_loaded")&&l.length>0&&Iy(this,null,this.W,this.D,LE(this));Y$=!this.WQ.Y("html5_keep_caption_data_after_seek")&&(this.K==="LIVE"||this.K==="SABR_LIVE");this.player.sN(l,void 0,Y$);!this.D||this.rz||LE(this)||g.DC(this.WQ)||g.LA(this.WQ)||g.aL(this.WQ)||this.WQ.qh==="shortspage"||this.player.isInline()||(g.dQ(this.OF),l=J2Y({pK:0,wU:5,Lb:5,UH:2,textAlign:0,TJ:0,lang:"en-GB"}),this.vQ=[l],Y$=["Click "," for settings"],this.If||(e=new g.EI(g.V7()),g.w(this,e),
this.If=e.element),e=l.end-l.start,(d=g.GP(this.W))&&this.vQ.push(new hn(l.start,e,0,l.id,d)),this.vQ.push(new hn(l.start,e,0,l.id,Y$[0]),new hn(l.start,e,0,l.id,this.If,!0),new hn(l.start,e,0,l.id,Y$[1],!0)),this.player.sN(this.vQ),g.Yl(this.OF));!this.D||this.rz||LE(this)||(g.Oi(this.WQ)?cH(this,!0):ay(this,!0),this.V&&(this.V.K=this.W),this.player.l$());this.D=!1}};
g.x.onCueRangeEnter=function(r){this.YN.push(r);Jn(this.iG)};
g.x.onCueRangeExit=function(r){g.sY(this.YN,r);this.X instanceof PH&&this.X.j&&this.player.bl([r]);Jn(this.iG)};
g.x.getCaptionWindowContainerId=function(){return this.T.element.id};
g.x.LUz=function(){ra8(this,this.vQ);this.vQ=null};
g.x.GK=function(){var r=this;if(!this.Rg||!this.U){this.iG.stop();g.T4$(this.yT);this.YN.sort(g.s5);var l=this.YN;if(this.kN){var U=g.wV(l,function(e){return this.kN.indexOf(e)===-1},this);
U.length&&(l=U)}l=g.Q(l);for(U=l.next();!U.done;U=l.next())I8C(this,U.value);l=g.Q(Object.entries(this.KP));var F=l.next();for(U={};!F.done;U={BJ:void 0,A3:void 0},F=l.next()){var Y=g.Q(F.value);F=Y.next().value;Y=Y.next().value;U.BJ=F;U.A3=Y;this.yT[U.BJ]?(U.A3.element.parentNode||(U.A3 instanceof fE||U.A3 instanceof HH||g.VC(this.KP,function(e){return function(d,K){K!==e.BJ&&d.X.params.pK===e.A3.X.params.pK&&d.X.params.wU===e.A3.X.params.wU&&d.X.params.Lb===e.A3.X.params.Lb&&(d.dispose(),delete r.KP[K]);
return K===e.BJ}}(U),this),this.T.element.appendChild(U.A3.element)),U.A3.j8(this.yT[U.BJ])):(U.A3.dispose(),delete this.KP[U.BJ])}}};
g.x.dsT=function(){VD$(this,{},!0);this.player.mx("captionssettingschanged")};
g.x.h1=function(){var r=os.RT;r={background:r.background,backgroundOpacity:r.backgroundOpacity,charEdgeStyle:r.charEdgeStyle,color:r.color,fontFamily:r.fontFamily,fontSizeIncrement:r.fontSizeIncrement,fontStyle:r.bold&&r.italic?3:r.bold?1:r.italic?2:0,textOpacity:r.textOpacity,windowColor:os.windowColor,windowOpacity:os.windowOpacity};var l=GcY()||{};l.background!=null&&(r.background=l.background);l.backgroundOverride!=null&&(r.backgroundOverride=l.backgroundOverride);l.backgroundOpacity!=null&&(r.backgroundOpacity=
l.backgroundOpacity);l.backgroundOpacityOverride!=null&&(r.backgroundOpacityOverride=l.backgroundOpacityOverride);l.charEdgeStyle!=null&&(r.charEdgeStyle=l.charEdgeStyle);l.charEdgeStyleOverride!=null&&(r.charEdgeStyleOverride=l.charEdgeStyleOverride);l.color!=null&&(r.color=l.color);l.colorOverride!=null&&(r.colorOverride=l.colorOverride);l.fontFamily!=null&&(r.fontFamily=l.fontFamily);l.fontFamilyOverride!=null&&(r.fontFamilyOverride=l.fontFamilyOverride);l.fontSizeIncrement!=null&&(r.fontSizeIncrement=
l.fontSizeIncrement);l.fontSizeIncrementOverride!=null&&(r.fontSizeIncrementOverride=l.fontSizeIncrementOverride);l.fontStyle!=null&&(r.fontStyle=l.fontStyle);l.fontStyleOverride!=null&&(r.fontStyleOverride=l.fontStyleOverride);l.textOpacity!=null&&(r.textOpacity=l.textOpacity);l.textOpacityOverride!=null&&(r.textOpacityOverride=l.textOpacityOverride);l.windowColor!=null&&(r.windowColor=l.windowColor);l.windowColorOverride!=null&&(r.windowColorOverride=l.windowColorOverride);l.windowOpacity!=null&&
(r.windowOpacity=l.windowOpacity);l.windowOpacityOverride!=null&&(r.windowOpacityOverride=l.windowOpacityOverride);return r};
g.x.t$=function(r,l){var U={};Object.assign(U,GcY());Object.assign(U,r);VD$(this,U,l);this.player.mx("captionssettingschanged")};
g.x.aU=function(){!this.U&&this.loaded&&(g.gR(this.KP,function(r,l){r.dispose();delete this.KP[l]},this),this.GK())};
g.x.hj=function(r,l){switch(r){case "fontSize":if(isNaN(l))break;r=g.Ge(l,-2,4);this.t$({fontSizeIncrement:r});return r;case "reload":l&&!this.U&&kE(this,this.W,!0);break;case "stickyLoading":l!==void 0&&this.WQ.T&&(g.Oi(this.WQ)?cH(this,!!l):ay(this,!!l));break;case "track":return oY$(this,l);case "tracklist":return this.X?g.aI(g.Yd(this.X.X,!(!l||!l.includeAsr)),function(U){return g.XY(U)}):[];
case "translationLanguages":return this.X?this.X.U.map(function(U){return Object.assign({},U)}):[];
case "sampleSubtitles":this.U||l===void 0||$5R(this,!!l);break;case "sampleSubtitlesCustomized":this.U||$5R(this,!!l,l);break;case "recommendedTranslationLanguages":return g.ek();case "defaultTranslationSourceTrackIndices":return this.X?this.X.T:[]}};
g.x.getOptions=function(){var r="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.WQ.T&&r.push("stickyLoading");return r};
g.x.Mq=function(){var r=this.W;if(this.C.oi("captions")){if(this.WQ.Y("html5_modify_caption_vss_logging")){var l;return(r=(l=this.videoData.Np)!=null?l:null)?{cc:g.lMS(r)}:{}}if(r)return l=r.vssId,r.translationLanguage&&l&&(l="t"+l+"."+g.iE(r)),{cc:l}}return{}};
g.x.eIP=function(){this.isSubtitlesOn()?(g.Oi(this.WQ)?cH(this,!1):ay(this,!1),c28(this),kE(this,null,!0)):this.Ku()};
g.x.Ku=function(){var r=LE(this)||!this.W?tn(this,!0):this.W;r&&this.cZ(r.vssId,"m");this.isSubtitlesOn()||kE(this,LE(this)||!this.W?tn(this,!0):this.W,!0)};
g.x.isSubtitlesOn=function(){return!!this.loaded&&!!this.W&&!LE(this)};
g.x.Mcf=function(){var r=LE(this);zO(this,r)?kE(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.NF()&&(this.D=!1,this.W=null,this.X&&(this.X.dispose(),this.X=null)),this.J7()&&(r?kE(this,tn(this,!1),!1):this.load()))};
g.x.bz=function(r){r&&(this.sF={top:r.top,right:r.right,bottom:r.bottom,left:r.left,width:1-r.left-r.right,height:1-r.top-r.bottom},this.T.element.style.top=this.sF.top*100+"%",this.T.element.style.left=this.sF.left*100+"%",this.T.element.style.width=this.sF.width*100+"%",this.T.element.style.height=this.sF.height*100+"%",this.T.element.style.position="absolute",r=kkY(this))&&(this.T.element.style.width=r.width+"px",this.T.element.style.height=r.height+"px")};
g.x.onVideoDataChange=function(r,l){r==="newdata"&&(this.videoData=l,this.loaded&&this.unload(),this.D=!1,this.W=null,this.X&&(this.X.dispose(),this.X=null,this.player.mx("captionschanged",{})),this.J7()&&this.load())};
g.x.getAudioTrack=function(){return this.player.getAudioTrack()};
g.x.rBz=function(){var r=this.C.dh();r&&!r.QT()&&r.gx();this.C.isFullscreen()?(this.U=this.Nh=!0,this.loaded&&this.by()):(this.Nh=this.WQ.controlsType==="3",this.U=Do0(this));kE(this,this.W)};
g.x.Hp=function(){var r,l,U,F=(r=this.videoData.getPlayerResponse())==null?void 0:(l=r.captions)==null?void 0:(U=l.playerCaptionsTracklistRenderer)==null?void 0:U.openTranscriptCommand;F&&this.player.PQ("innertubeCommand",F)};
g.x.Ec=function(r,l,U){var F=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Y="";r&&(Y=r.vssId,Y=Y.replace(F,""));var e="";r&&r.getId()&&(e=r.getId()||"");r&&r.getXtags()&&(r=r.getXtags(),r=r.replace(F,""),e=e.concat(";"+r));this.C.Ec(l?Y:"",l?e:"",U)};
g.x.cZ=function(r,l){r=(r||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");r.length>0&&this.C.cZ(r,l)};
g.x.BS=function(){this.X&&this.X.BS()};g.ZR("captions",f8Y);})(_yt_player);
