(function(g){var window=this;'use strict';var qVb=function(r){r.publish("autonavvisibility")},TVq=function(r,l){r.PQ("onAutonavCoundownStarted",l)},ueY=function(r){var l,U,F;
return r==null?void 0:(l=r.playerOverlays)==null?void 0:(U=l.playerOverlayRenderer)==null?void 0:(F=U.autoplay)==null?void 0:F.playerOverlayAutoplayRenderer},dt=function(r){var l=r.N(),U=l.K;
g.p.call(this,{Z:"a",S:"ytp-autonav-suggestion-card",J:{href:"{{url}}",target:U?l.V:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},B:[{Z:"div",Dz:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],J:{style:"{{background}}"},B:[{Z:"div",J:{"aria-label":"{{timestamp}}"},Dz:["ytp-autonav-timestamp"],XT:"{{duration}}"},{Z:"div",Dz:["ytp-autonav-live-stamp"],XT:"Live"},{Z:"div",
Dz:["ytp-autonav-upcoming-stamp"],XT:"Upcoming"},{Z:"div",S:"ytp-autonav-list-overlay",B:[{Z:"div",S:"ytp-autonav-mix-text",XT:"Mix"},{Z:"div",S:"ytp-autonav-mix-icon"}]}]},{Z:"div",Dz:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],XT:"{{title}}"},{Z:"div",Dz:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],XT:"{{author}}"},{Z:"div",Dz:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],XT:"{{views_and_publish_time}}"}]});this.C=r;this.suggestion=
null;this.W=U;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},Ov=function(r,l){l=l===void 0?!1:l;
g.p.call(this,{Z:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var U=this;this.j=l;this.cancelCommand=this.D=void 0;this.L=0;this.container=new g.p({Z:"div",S:"ytp-autonav-endscreen-countdown-container"});g.w(this,this.container);this.container.CP(this.element);l=r.N();var F=l.K;this.C=r;this.suggestion=null;this.onVideoDataChange("newdata",this.C.getVideoData());this.G(r,"videodatachange",this.onVideoDataChange);this.W=new g.p({Z:"div",S:"ytp-autonav-endscreen-upnext-container",J:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},B:[{Z:"div",S:"ytp-autonav-endscreen-upnext-header"},{Z:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",XT:"{{autoplayAlternativeHeader}}"},{Z:"a",S:"ytp-autonav-endscreen-link-container",J:{href:"{{url}}",target:F?l.V:""},B:[{Z:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",J:{style:"{{background}}"},B:[{Z:"div",J:{"aria-label":"{{timestamp}}"},Dz:["ytp-autonav-timestamp"],
XT:"{{duration}}"},{Z:"div",Dz:["ytp-autonav-live-stamp"],XT:"Live"},{Z:"div",Dz:["ytp-autonav-upcoming-stamp"],XT:"Upcoming"}]},{Z:"div",S:"ytp-autonav-endscreen-video-info",B:[{Z:"div",S:"ytp-autonav-endscreen-premium-badge"},{Z:"div",S:"ytp-autonav-endscreen-upnext-title",XT:"{{title}}"},{Z:"div",S:"ytp-autonav-endscreen-upnext-author",XT:"{{author}}"},{Z:"div",S:"ytp-autonav-view-and-date",XT:"{{views_and_publish_time}}"},{Z:"div",S:"ytp-autonav-author-and-view",XT:"{{author_and_views}}"}]}]}]});
g.w(this,this.W);this.W.CP(this.container.element);F||this.G(this.W.Zz("ytp-autonav-endscreen-link-container"),"click",this.F3);this.C.createClientVe(this.container.element,this,115127);this.C.createClientVe(this.W.Zz("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.p({Z:"div",S:"ytp-autonav-overlay"});g.w(this,this.overlay);this.overlay.CP(this.container.element);this.X=new g.p({Z:"div",S:"ytp-autonav-endscreen-button-container"});g.w(this,this.X);this.X.CP(this.container.element);
this.cancelButton=new g.p({Z:"button",Dz:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",l.Y("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],J:{"aria-label":"Cancel auto-play"},XT:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.CP(this.X.element);this.cancelButton.listen("click",this.Bt,this);this.C.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.p({Z:"a",Dz:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
l.Y("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],J:{href:"{{url}}",role:"button","aria-label":"Play next video"},XT:"Play now"});g.w(this,this.playButton);this.playButton.CP(this.X.element);this.playButton.listen("click",this.F3,this);this.C.createServerVe(this.playButton.element,this.playButton,!0);(l=this.C.getVideoData())&&yaC(this,l);this.K=new g.F1(function(){BV8(U)},500);
g.w(this,this.K);this.ud();this.G(r,"autonavvisibility",this.ud);this.C.Y("web_autonav_color_transition")&&(this.G(r,"autonavchange",this.IP),this.G(r,"onAutonavCoundownStarted",this.jfF))},K_=function(r){var l=r.C.qt(!0,r.C.isFullscreen());
g.xl(r.container.element,"ytp-autonav-endscreen-small-mode",r.WZ(l));g.xl(r.container.element,"ytp-autonav-endscreen-is-premium",!!r.suggestion&&!!r.suggestion.PhT);g.xl(r.C.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!r.C.eS());g.xl(r.C.getRootNode(),"countdown-running",r.qQ());g.xl(r.container.element,"ytp-player-content",r.C.eS());g.RI(r.overlay.element,{width:l.width+"px"});if(!r.qQ()){r.C.eS()?He8(r,Math.round(gYb(r)/1E3)):He8(r);l=!!r.suggestion&&!!r.suggestion.pW;var U=r.C.eS()||
!l;g.xl(r.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!U&&l);g.xl(r.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",U&&!l);r.X.zf(r.C.eS());g.xl(r.element,"ytp-enable-w2w-color-transitions",wqC(r))}},BV8=function(r){var l=gYb(r),U=Math,F=U.min;
var Y=r.L?Date.now()-r.L:0;U=F.call(U,Y,l);He8(r,Math.ceil((l-U)/1E3));l-U<=500&&r.qQ()?r.select(!0):r.qQ()&&r.K.start()},gYb=function(r){if(r.C.isFullscreen()){var l;
r=(l=r.C.getVideoData())==null?void 0:l.r$;return r===-1||r===void 0?8E3:r}return r.C.UR()>=0?r.C.UR():g.GQ(r.C.N().experiments,"autoplay_time")||1E4},yaC=function(r,l){l=l.getWatchNextResponse();
var U,F;l=(U=ueY(l))==null?void 0:(F=U.nextButton)==null?void 0:F.buttonRenderer;r.D=l==null?void 0:l.navigationEndpoint;U=l==null?void 0:l.trackingParams;r.playButton&&U&&r.C.setTrackingParams(r.playButton.element,U)},wqC=function(r){var l;
return!((l=r.C.getVideoData())==null||!l.watchToWatchTransitionRenderer)},He8=function(r,l){l=l===void 0?-1:l;
r=r.W.Zz("ytp-autonav-endscreen-upnext-header");g.rA(r);if(l>=0){l=String(l);var U="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],F="Up next in $SECONDS".indexOf(U);if(F>=0){r.appendChild(g.kR("Up next in $SECONDS".slice(0,F)));var Y=g.I1("span");g.Jb(Y,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Fk(Y,l);r.appendChild(Y);r.appendChild(g.kR("Up next in $SECONDS".slice(F+U.length)));return}}g.Fk(r,"Up next")},C_=function(r,l){g.p.call(this,{Z:"div",
Dz:["html5-endscreen","ytp-player-content",l||"base-endscreen"]});this.created=!1;this.player=r},vk=function(r){g.p.call(this,{Z:"div",
Dz:["ytp-upnext","ytp-player-content"],J:{"aria-label":"{{aria_label}}"},B:[{Z:"div",S:"ytp-cued-thumbnail-overlay-image",J:{style:"{{background}}"}},{Z:"span",S:"ytp-upnext-top",B:[{Z:"span",S:"ytp-upnext-header",XT:"Up Next"},{Z:"span",S:"ytp-upnext-title",XT:"{{title}}"},{Z:"span",S:"ytp-upnext-author",XT:"{{author}}"}]},{Z:"a",S:"ytp-upnext-autoplay-icon",J:{role:"button",href:"{{url}}","aria-label":"Play next video"},B:[{Z:"svg",J:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
B:[{Z:"circle",S:"ytp-svg-autoplay-circle",J:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{Z:"circle",S:"ytp-svg-autoplay-ring",J:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{Z:"path",S:"ytp-svg-fill",J:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{Z:"span",S:"ytp-upnext-bottom",B:[{Z:"span",S:"ytp-upnext-cancel"},{Z:"span",S:"ytp-upnext-paused",
XT:"Auto-play is paused"}]}]});this.api=r;this.cancelButton=null;this.D=this.Zz("ytp-svg-autoplay-ring");this.L=this.notification=this.W=this.suggestion=null;this.K=new g.F1(this.L3,5E3,this);this.X=0;var l=this.Zz("ytp-upnext-cancel");this.cancelButton=new g.p({Z:"button",Dz:["ytp-upnext-cancel-button","ytp-button"],J:{tabindex:"0","aria-label":"Cancel auto-play"},XT:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.listen("click",this.hP,this);this.cancelButton.CP(l);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.w(this,this.K);this.api.createClientVe(this.element,this,18788);l=this.Zz("ytp-upnext-autoplay-icon");this.G(l,"click",this.Vy);this.api.createClientVe(l,this,115130);this.qa();this.G(r,"autonavvisibility",this.qa);this.G(r,"mdxnowautoplaying",this.C3z);this.G(r,"mdxautoplaycanceled",this.w5u);g.xl(this.element,"ytp-upnext-mobile",this.api.N().X)},D58=function(r,l){if(l)return l;
if(r.api.isFullscreen()){var U;r=(U=r.api.getVideoData())==null?void 0:U.r$;return r===-1||r===void 0?8E3:r}return r.api.UR()>=0?r.api.UR():g.GQ(r.api.N().experiments,"autoplay_time")||1E4},Vxp=function(r,l){l=D58(r,l);
var U=Math,F=U.min;var Y=(0,g.f)()-r.X;U=F.call(U,Y,l);l=l===0?1:Math.min(U/l,1);r.D.setAttribute("stroke-dashoffset",""+-211*(l+1));l>=1&&r.qQ()&&r.api.getPresentingPlayerType()!==3?r.select(!0):r.qQ()&&r.W.start()},Jr=function(r){C_.call(this,r,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.p({Z:"div",S:"ytp-suggestion-panel",B:[{Z:"div",Dz:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],XT:"More videos"}]});this.T=new g.p({Z:"div",S:"ytp-suggestions-container"});this.videos=[];this.L=null;this.D=this.j=!1;this.X=new Ov(this.player);g.w(this,this.X);this.X.CP(this.element);r.getVideoData().LJ?this.W=this.X:(this.W=new vk(r),g.Sg(this.player,this.W.element,4),g.w(this,this.W));this.overlay=new g.p({Z:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.w(this,this.overlay);this.overlay.CP(this.element);this.K=new g.Lg(this);g.w(this,this.K);g.w(this,this.table);this.table.CP(this.element);this.table.show();g.w(this,this.T);this.T.CP(this.table.element);this.hide()},mm=function(r){var l=r.eS();
l!==r.D&&(r.D=l,qVb(r.player),r.D?(r.X!==r.W&&r.X.hide(),r.table.hide()):(r.X!==r.W&&r.X.show(),r.table.show()))},fL$=function(r){C_.call(this,r,"videowall-endscreen");
var l=this;this.C=r;this.stills=[];this.L=this.videoData=null;this.K=this.j=!1;this.T=null;g.Pl(this.element,"modern-videowall-endscreen");this.X=new g.Lg(this);g.w(this,this.X);this.D=new g.F1(function(){g.Pl(l.element,"ytp-show-tiles")},0);
g.w(this,this.D);this.table=new g.EI({Z:"div",S:"ytp-modern-endscreen-content"});g.w(this,this.table);this.table.CP(this.element);r.getVideoData().LJ?this.W=new Ov(r,!0):this.W=new vk(r);g.w(this,this.W);g.Sg(this.player,this.W.element,4);r.createClientVe(this.element,this,158789);this.hide()},Pk=function(r){return g.z5(r.player)&&r.JT()&&!r.L},Ar=function(r){var l=r.eS();
l!==r.j&&(r.j=l,qVb(r.player))},SVG=function(r){C_.call(this,r,"subscribecard-endscreen");
this.W=new g.p({Z:"div",S:"ytp-subscribe-card",B:[{Z:"img",S:"ytp-author-image",J:{src:"{{profilePicture}}"}},{Z:"div",S:"ytp-subscribe-card-right",B:[{Z:"div",S:"ytp-author-name",XT:"{{author}}"},{Z:"div",S:"html5-subscribe-button-container"}]}]});g.w(this,this.W);this.W.CP(this.element);var l=r.getVideoData();this.subscribeButton=new g.lX("Subscribe",null,"Unsubscribe",null,!0,!1,l.Nt,l.subscribed,"trailer-endscreen",null,r,!1);g.w(this,this.subscribeButton);this.subscribeButton.CP(this.W.Zz("html5-subscribe-button-container"));
this.G(r,"videodatachange",this.Sc);this.Sc();this.hide()},MW=function(r){var l=r.N(),U=g.SG||g.gE?{style:"will-change: opacity"}:void 0,F=l.K,Y=["ytp-videowall-still"];
l.X&&Y.push("ytp-videowall-show-text");g.p.call(this,{Z:"a",Dz:Y,J:{href:"{{url}}",target:F?l.V:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},B:[{Z:"div",S:"ytp-videowall-still-image",J:{style:"{{background}}"}},{Z:"span",S:"ytp-videowall-still-info",J:{"aria-hidden":"true"},B:[{Z:"span",S:"ytp-videowall-still-info-bg",B:[{Z:"span",S:"ytp-videowall-still-info-content",J:U,B:[{Z:"span",S:"ytp-videowall-still-info-title",XT:"{{title}}"},
{Z:"span",S:"ytp-videowall-still-info-author",XT:"{{author_and_views}}"},{Z:"span",S:"ytp-videowall-still-info-live",XT:"Live"},{Z:"span",S:"ytp-videowall-still-info-duration",XT:"{{duration}}"}]}]}]},{Z:"span",Dz:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},B:[{Z:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{Z:"span",S:"ytp-videowall-still-listlabel-length",B:[" (",{Z:"span",XT:"{{playlist_length}}"},")"]}]},{Z:"span",Dz:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},B:[{Z:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{Z:"span",S:"ytp-videowall-still-listlabel-length",XT:" (50+)"}]}]});this.suggestion=null;this.X=F;this.api=r;this.W=new g.Lg(this);g.w(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.G(r,"videodatachange",this.onVideoDataChange);r.createServerVe(this.element,this);this.onVideoDataChange()},xG=function(r){C_.call(this,r,"videowall-endscreen");
var l=this;this.C=r;this.L=0;this.stills=[];this.K=this.videoData=null;this.D=this.T=!1;this.V=null;this.X=new g.Lg(this);g.w(this,this.X);this.j=new g.F1(function(){g.Pl(l.element,"ytp-show-tiles")},0);
g.w(this,this.j);var U=new g.p({Z:"button",Dz:["ytp-button","ytp-endscreen-previous"],J:{"aria-label":"Previous"},B:[g.NP()]});g.w(this,U);U.CP(this.element);U.listen("click",this.s2,this);this.table=new g.EI({Z:"div",S:"ytp-endscreen-content"});g.w(this,this.table);this.table.CP(this.element);U=new g.p({Z:"button",Dz:["ytp-button","ytp-endscreen-next"],J:{"aria-label":"Next"},B:[g.jl()]});g.w(this,U);U.CP(this.element);U.listen("click",this.HL,this);r.getVideoData().LJ?this.W=new Ov(r,!0):this.W=
new vk(r);g.w(this,this.W);g.Sg(this.player,this.W.element,4);r.createClientVe(this.element,this,158789);this.hide()},Wk=function(r){return g.z5(r.player)&&r.JT()&&!r.K},Q5=function(r){var l=r.eS();
l!==r.T&&(r.T=l,qVb(r.player))},zQ8=function(r,l){g.p.call(this,{Z:"button",
Dz:["ytp-watch-on-youtube-button","ytp-button"],XT:"{{content}}"});this.C=r;this.buttonType=this.buttonType=l;this.YX();this.buttonType===2&&g.Pl(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.YX);this.zf(!0)},Ev=function(r){C_.call(this,r,"watch-again-on-youtube-endscreen");
this.watchButton=new zQ8(r,1);g.w(this,this.watchButton);this.watchButton.CP(this.element);g.yef(r)&&(this.W=new g.$z(r),g.w(this,this.W),this.X=new g.p({Z:"div",Dz:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],J:{tabIndex:"-1"},B:[this.W]}),g.w(this,this.X),this.W.CP(this.X.element),this.X.CP(this.element));r.createClientVe(this.element,this,156914);this.hide()},car=function(r){g.Rf.call(this,r);
var l=this;this.endScreen=null;this.W=this.X=this.L=!1;this.listeners=new g.Lg(this);g.w(this,this.listeners);var U=r.N();r.isEmbedsShortsMode()?this.endScreen=new Ev(r):pqr(r)?(this.L=!0,txC(this),this.W?this.endScreen=new Jr(r):U.Y("delhi_modern_endscreen")?this.endScreen=new fL$(r):this.endScreen=new xG(r)):U.wK?this.endScreen=new SVG(r):this.endScreen=new C_(r);g.w(this,this.endScreen);g.Sg(r,this.endScreen.element,4);LTp(this);this.listeners.G(r,"videodatachange",this.onVideoDataChange,this);
this.listeners.G(r,g.x1("endscreen"),function(F){l.onCueRangeEnter(F)});
this.listeners.G(r,g.W9("endscreen"),function(F){l.onCueRangeExit(F)})},txC=function(r){var l=r.player.getVideoData();
if(!l||r.W===l.B_&&r.X===l.LJ)return!1;r.W=l.B_;r.X=l.LJ;return!0},pqr=function(r){r=r.N();
return r.f1&&!r.wK&&!r.disableOrganicUi},LTp=function(r){r.player.MB("endscreen");
var l=r.player.getVideoData();l=new g.M2(Math.max((l.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var U=new g.M2(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});r.player.sN([l,U])};
g.yy.prototype.UR=g.FL(6,function(){return this.app.UR()});
g.QP.prototype.UR=g.FL(5,function(){return this.getVideoData().Ds});
g.jg.prototype.Uf=g.FL(4,function(r){this.wG().Uf(r)});
g.cu.prototype.Uf=g.FL(3,function(r){this.Qu!==r&&(this.Qu=r,this.JY())});
g.W(dt,g.p);dt.prototype.select=function(){this.C.zI(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.d5||void 0)&&this.C.logClick(this.element)};
dt.prototype.onClick=function(r){g.AG(r,this.C,this.W,this.suggestion.sessionData||void 0)&&this.select()};
dt.prototype.onKeyPress=function(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}};g.W(Ov,g.p);g.x=Ov.prototype;g.x.Ud=function(r){this.suggestion!==r&&(this.suggestion=r,g.vu(this.W,r),this.playButton.updateValue("url",this.suggestion.eD()),K_(this))};
g.x.qQ=function(){return this.L>0};
g.x.h7=function(){this.qQ()||(this.L=Date.now(),BV8(this),TVq(this.C,gYb(this)),g.xl(this.C.getRootNode(),"countdown-running",this.qQ()))};
g.x.ww=function(){this.H9();BV8(this);var r=this.W.Zz("ytp-autonav-endscreen-upnext-header");r&&g.Fk(r,"Up next")};
g.x.H9=function(){this.qQ()&&(this.K.stop(),this.L=0)};
g.x.select=function(r){this.C.nextVideo(!1,r===void 0?!1:r);this.H9()};
g.x.F3=function(r){g.AG(r,this.C)&&(r.currentTarget===this.playButton.element?this.C.logClick(this.playButton.element):r.currentTarget===this.W.Zz("ytp-autonav-endscreen-link-container")&&(r=this.W.Zz("ytp-autonav-endscreen-link-container"),this.C.logVisibility(r,!0),this.C.logClick(r)),this.D?(this.C.PQ("innertubeCommand",this.D),this.H9()):this.select())};
g.x.Bt=function(){this.C.logClick(this.cancelButton.element);g.HM(this.C,!0);this.cancelCommand&&this.C.PQ("innertubeCommand",this.cancelCommand)};
g.x.onVideoDataChange=function(r,l){yaC(this,l);r=l.getWatchNextResponse();var U,F;r=(U=ueY(r))==null?void 0:(F=U.cancelButton)==null?void 0:F.buttonRenderer;this.cancelCommand=r==null?void 0:r.command};
g.x.jfF=function(r){if(wqC(this)){var l=this.C.getVideoData().watchToWatchTransitionRenderer,U=l==null?void 0:l.fromColorPaletteDark;l=l==null?void 0:l.toColorPaletteDark;if(U&&l){var F=this.element;F.style.setProperty("--w2w-start-background-color",g.IL(U.surgeColor));F.style.setProperty("--w2w-start-primary-text-color",g.IL(U.primaryTitleColor));F.style.setProperty("--w2w-start-secondary-text-color",g.IL(U.secondaryTitleColor));F.style.setProperty("--w2w-end-background-color",g.IL(l.surgeColor));
F.style.setProperty("--w2w-end-primary-text-color",g.IL(l.primaryTitleColor));F.style.setProperty("--w2w-end-secondary-text-color",g.IL(l.secondaryTitleColor));F.style.setProperty("--w2w-animation-duration",r+"ms")}g.xl(this.element,"ytp-w2w-animate",!0)}};
g.x.IP=function(r){this.C.Y("web_autonav_color_transition")&&r!==2&&g.xl(this.element,"ytp-w2w-animate",!1)};
g.x.ud=function(){var r=this.C.eS();this.j&&this.H5!==r&&this.zf(r);K_(this);this.C.logVisibility(this.container.element,r);this.C.logVisibility(this.cancelButton.element,r);this.C.logVisibility(this.W.Zz("ytp-autonav-endscreen-link-container"),r);this.C.logVisibility(this.playButton.element,r)};
g.x.WZ=function(r){return r.width<400||r.height<459};g.W(C_,g.p);g.x=C_.prototype;g.x.create=function(){this.created=!0};
g.x.destroy=function(){this.created=!1};
g.x.JT=function(){return!1};
g.x.eS=function(){return!1};
g.x.BF=function(){return!1};g.W(vk,g.p);g.x=vk.prototype;g.x.L3=function(){this.notification&&(this.K.stop(),this.ev(this.L),this.L=null,this.notification.close(),this.notification=null)};
g.x.Ud=function(r){this.suggestion=r;g.vu(this,r,"hqdefault.jpg")};
g.x.qa=function(){this.zf(this.api.eS());this.api.logVisibility(this.element,this.api.eS());this.api.logVisibility(this.Zz("ytp-upnext-autoplay-icon"),this.api.eS());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.eS())};
g.x.U2h=function(){window.focus();this.L3()};
g.x.h7=function(r){var l=this;this.qQ()||(g.AO("a11y-announce","Up Next "+this.suggestion.title),this.X=(0,g.f)(),this.W=new g.F1(function(){Vxp(l,r)},25),Vxp(this,r),TVq(this.api,D58(this,r)));
g.M0(this.element,"ytp-upnext-autoplay-paused")};
g.x.hide=function(){g.p.prototype.hide.call(this)};
g.x.qQ=function(){return!!this.W};
g.x.ww=function(){this.H9();this.X=(0,g.f)();Vxp(this);g.Pl(this.element,"ytp-upnext-autoplay-paused")};
g.x.H9=function(){this.qQ()&&(this.W.dispose(),this.W=null)};
g.x.select=function(r){r=r===void 0?!1:r;if(this.api.N().Y("autonav_notifications")&&r&&window.Notification&&typeof document.hasFocus==="function"){var l=Notification.permission;l==="default"?Notification.requestPermission():l!=="granted"||document.hasFocus()||(this.L3(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.rY()}),this.L=this.G(this.notification,"click",this.U2h),this.K.start())}this.H9();this.api.nextVideo(!1,r)};
g.x.Vy=function(r){!g.UM(this.cancelButton.element,r.target)&&g.AG(r,this.api)&&(this.api.eS()&&this.api.logClick(this.Zz("ytp-upnext-autoplay-icon")),this.select())};
g.x.hP=function(){this.api.eS()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.HM(this.api,!0)};
g.x.C3z=function(r){this.api.getPresentingPlayerType();this.show();this.h7(r)};
g.x.w5u=function(){this.api.getPresentingPlayerType();this.H9();this.hide()};
g.x.Rf=function(){this.H9();this.L3();g.p.prototype.Rf.call(this)};g.W(Jr,C_);g.x=Jr.prototype;g.x.create=function(){C_.prototype.create.call(this);this.K.G(this.player,"appresize",this.QW);this.K.G(this.player,"onVideoAreaChange",this.QW);this.K.G(this.player,"videodatachange",this.onVideoDataChange);this.K.G(this.player,"autonavchange",this.Ct);this.K.G(this.player,"onAutonavCancelled",this.g9);this.onVideoDataChange()};
g.x.show=function(){C_.prototype.show.call(this);(this.j||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.HM(this.player,!1);g.z5(this.player)&&this.JT()&&!this.L?(mm(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.h7():this.videoData.autonavState===3&&this.W.ww()):(g.HM(this.player,!0),mm(this));this.QW()};
g.x.hide=function(){C_.prototype.hide.call(this);this.W.ww();mm(this)};
g.x.QW=function(){var r=this.player.qt(!0,this.player.isFullscreen());mm(this);K_(this.X);g.xl(this.element,"ytp-autonav-cancelled-small-mode",this.WZ(r));g.xl(this.element,"ytp-autonav-cancelled-tiny-mode",this.tJ(r));g.xl(this.element,"ytp-autonav-cancelled-mini-mode",r.width<=400||r.height<=360);this.overlay&&g.RI(this.overlay.element,{width:r.width+"px"});if(!this.D)for(r=0;r<this.videos.length;r++)g.xl(this.videos[r].element,"ytp-suggestion-card-with-margin",r%2===1)};
g.x.onVideoDataChange=function(){var r=this.player.getVideoData();if(this.videoData!==r&&r){this.videoData=r;if((r=this.videoData.suggestions)&&r.length||this.player.Y("web_player_autonav_empty_suggestions_fix")){var l=g.Ck(this.videoData);l&&(this.W.Ud(l),this.W!==this.X&&this.X.Ud(l))}if(r&&r.length)for(l=0;l<aL8.length;++l){var U=aL8[l];if(r&&r[U]){this.videos[l]=new dt(this.player);var F=this.videos[l];U=r[U];F.suggestion!==U&&(F.suggestion=U,g.vu(F,U));g.w(this,this.videos[l]);this.videos[l].CP(this.T.element)}}this.QW()}};
g.x.Ct=function(r){r===1?(this.j=!1,this.L=this.videoData.clientPlaybackNonce,this.W.H9(),this.H5&&this.QW()):(this.j=!0,this.eS()&&(r===2?this.W.h7():r===3&&this.W.ww()))};
g.x.g9=function(r){r?this.Ct(1):(this.L=null,this.j=!1)};
g.x.JT=function(){return this.videoData.autonavState!==1};
g.x.WZ=function(r){return(r.width<910||r.height<459)&&!this.tJ(r)&&!(r.width<=400||r.height<=360)};
g.x.tJ=function(r){return r.width<800&&!(r.width<=400||r.height<=360)};
g.x.eS=function(){return this.H5&&g.z5(this.player)&&this.JT()&&!this.L};
var aL8=[1,3,2,4];g.W(fL$,C_);g.x=fL$.prototype;g.x.create=function(){C_.prototype.create.call(this);var r=this.player.getVideoData();r&&(this.videoData=r);this.dX();this.X.G(this.player,"appresize",this.dX);this.X.G(this.player,"onVideoAreaChange",this.dX);this.X.G(this.player,"videodatachange",this.onVideoDataChange);this.X.G(this.player,"autonavchange",this.sI);this.X.G(this.player,"onAutonavCancelled",this.nG);r=this.videoData.autonavState;r!==this.T&&this.sI(r);this.X.G(this.element,"transitionend",this.mj)};
g.x.destroy=function(){g.gl(this.X);g.xY(this.stills);this.stills=[];C_.prototype.destroy.call(this);g.M0(this.element,"ytp-show-tiles");this.D.stop();this.T=this.videoData.autonavState};
g.x.JT=function(){return this.videoData.autonavState!==1};
g.x.show=function(){var r=this.H5;C_.prototype.show.call(this);g.M0(this.element,"ytp-show-tiles");this.player.N().X?g.eb(this.D):this.D.start();(this.K||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.HM(this.player,!1);Pk(this)?(Ar(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.h7():this.videoData.autonavState===3&&this.W.ww()):(g.HM(this.player,!0),Ar(this));r!==this.H5&&this.player.logVisibility(this.element,!0)};
g.x.hide=function(){var r=this.H5;C_.prototype.hide.call(this);this.W.ww();Ar(this);r!==this.H5&&this.player.logVisibility(this.element,!1)};
g.x.mj=function(r){r.target===this.element&&this.dX()};
g.x.dX=function(){var r,l,U,F;var Y=((r=this.videoData)==null?0:(l=r.suggestions)==null?0:l.length)?(U=this.videoData)==null?void 0:U.suggestions:[(F=this.videoData)==null?void 0:g.Ck(F)];if(Y.length){l=this.C.qt(!0,this.C.isFullscreen());r=Math.floor((l.width-64+16)/(g.Ge(l.width*.27,250,450)+16));l=Math.min(3,Math.floor((l.height-64)/((l.width-64-(r-1)*16)/r*.5625+70)));g.sS(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Pl(this.element,"ytp-modern-endscreen-limit-rows-"+l);g.xl(this.element,"ytp-modern-endscreen-single-item",r===1);g.xl(this.element,"ytp-modern-endscreen-row-0",l===0);r=this.table.element;r.ariaLive="polite";this.W.Ud(g.Ck(this.videoData));this.W instanceof Ov&&K_(this.W);g.xl(this.element,"ytp-endscreen-takeover",Pk(this));Ar(this);l=0;r.ariaBusy="true";U=Y.length;for(F=0;F<U;F++){var e=F%U,d=this.stills[F];d||(d=new g.JQ(this.player),this.stills[F]=d,r.appendChild(d.element));g.o7L(d,Y[e]);l++}this.stills.length=
l}};
g.x.onVideoDataChange=function(){var r=this.player.getVideoData(1);this.videoData!==r&&(r!=null&&g.Ck(r)?(this.videoData=r,this.dX()):this.player.pP("missg",{vid:(r==null?void 0:r.videoId)||"",cpn:(r==null?void 0:r.clientPlaybackNonce)||""}))};
g.x.BF=function(){return this.W.qQ()};
g.x.sI=function(r){r===1?(this.K=!1,this.L=this.videoData.clientPlaybackNonce,this.W.H9(),this.H5&&this.dX()):(this.K=!0,this.H5&&Pk(this)&&(r===2?this.W.h7():r===3&&this.W.ww()))};
g.x.nG=function(r){if(r){for(r=0;r<this.stills.length;r++)this.C.logVisibility(this.stills[r].element,!0);this.sI(1)}else this.L=null,this.K=!1;this.dX()};
g.x.eS=function(){return this.H5&&Pk(this)};g.W(SVG,C_);SVG.prototype.Sc=function(){var r=this.player.getVideoData();this.W.update({profilePicture:r.profilePicture,author:r.author});this.subscribeButton.channelId=r.Nt;var l=this.subscribeButton;r.subscribed?l.W():l.X()};g.W(MW,g.p);MW.prototype.select=function(){this.api.zI(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.d5||void 0)&&this.api.logClick(this.element)};
MW.prototype.onClick=function(r){if(g.D6(this.api.N())&&this.api.Y("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var l=this.suggestion.eD(),U={};g.Dx(this.api,U);l=g.jD(l,U);g.M7(l,this.api,r)}else g.AG(r,this.api,this.X,this.suggestion.sessionData||void 0)&&this.select()};
MW.prototype.onKeyPress=function(r){switch(r.keyCode){case 13:case 32:r.defaultPrevented||(this.select(),r.preventDefault())}};
MW.prototype.onVideoDataChange=function(){var r=this.api.getVideoData(),l=this.api.N();this.X=r.f0?!1:l.K};g.W(xG,C_);g.x=xG.prototype;g.x.create=function(){C_.prototype.create.call(this);var r=this.player.getVideoData();r&&(this.videoData=r);this.Ro();this.X.G(this.player,"appresize",this.Ro);this.X.G(this.player,"onVideoAreaChange",this.Ro);this.X.G(this.player,"videodatachange",this.onVideoDataChange);this.X.G(this.player,"autonavchange",this.pL);this.X.G(this.player,"onAutonavCancelled",this.WL);r=this.videoData.autonavState;r!==this.V&&this.pL(r);this.X.G(this.element,"transitionend",this.pV)};
g.x.destroy=function(){g.gl(this.X);g.xY(this.stills);this.stills=[];C_.prototype.destroy.call(this);g.M0(this.element,"ytp-show-tiles");this.j.stop();this.V=this.videoData.autonavState};
g.x.JT=function(){return this.videoData.autonavState!==1};
g.x.show=function(){var r=this.H5;C_.prototype.show.call(this);g.M0(this.element,"ytp-show-tiles");this.player.N().X?g.eb(this.j):this.j.start();(this.D||this.K&&this.K!==this.videoData.clientPlaybackNonce)&&g.HM(this.player,!1);Wk(this)?(Q5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.W.select(!0):this.W.h7():this.videoData.autonavState===3&&this.W.ww()):(g.HM(this.player,!0),Q5(this));r!==this.H5&&this.player.logVisibility(this.element,!0)};
g.x.hide=function(){var r=this.H5;C_.prototype.hide.call(this);this.W.ww();Q5(this);r!==this.H5&&this.player.logVisibility(this.element,!1)};
g.x.pV=function(r){r.target===this.element&&this.Ro()};
g.x.Ro=function(){var r,l,U,F;var Y=((r=this.videoData)==null?0:(l=r.suggestions)==null?0:l.length)?(U=this.videoData)==null?void 0:U.suggestions:[(F=this.videoData)==null?void 0:g.Ck(F)];if(Y.length){g.Pl(this.element,"ytp-endscreen-paginate");var e=this.C.qt(!0,this.C.isFullscreen());if(r=g.nF(this.C))r=r.wY()?48:32,e.width-=r*2;var d=e.width/e.height;F=96/54;l=r=2;var K=Math.max(e.width/96,2),C=Math.max(e.height/54,2);U=Y.length;var v=U*4;for(v-=4;v>0&&(r<K||l<C);){var J=r/2,m=l/2,P=r<=K-2&&v>=
m*4,A=l<=C-2&&v>=J*4;if((J+1)/m*F/d>d/(J/(m+1)*F)&&A)v-=J*4,l+=2;else if(P)v-=m*4,r+=2;else if(A)v-=J*4,l+=2;else break}F=!1;v>=12&&U*4-v<=6&&(l>=4||r>=4)&&(F=!0);v=r*96;K=l*54;d=v/K<d?e.height/K:e.width/v;d=Math.min(d,2);v=Math.floor(Math.min(e.width,v*d));K=Math.floor(Math.min(e.height,K*d));e=this.table.element;e.ariaLive="polite";g.TC(e,v,K);g.RI(e,{marginLeft:v/-2+"px",marginTop:K/-2+"px"});this.W.Ud(g.Ck(this.videoData));this.W instanceof Ov&&K_(this.W);g.xl(this.element,"ytp-endscreen-takeover",
Wk(this));Q5(this);v+=4;K+=4;d=0;e.ariaBusy="true";for(C=0;C<r;C++)for(J=0;J<l;J++)if(m=d,A=0,F&&C>=r-2&&J>=l-2?A=1:J%2===0&&C%2===0&&(J<2&&C<2?J===0&&C===0&&(A=2):A=2),m=g.XJ(m+this.L,U),A!==0){P=this.stills[d];P||(P=new MW(this.player),this.stills[d]=P,e.appendChild(P.element));var M=Math.floor(K*J/l),E=Math.floor(v*C/r),Z=Math.floor(K*(J+A)/l)-M-4,n=Math.floor(v*(C+A)/r)-E-4;g.bD(P.element,E,M);g.TC(P.element,n,Z);g.RI(P.element,"transitionDelay",(J+C)/20+"s");g.xl(P.element,"ytp-videowall-still-mini",
A===1);g.xl(P.element,"ytp-videowall-still-large",A>2);A=Math.max(n,Z);g.xl(P.element,"ytp-videowall-still-round-large",A>=256);g.xl(P.element,"ytp-videowall-still-round-medium",A>96&&A<256);g.xl(P.element,"ytp-videowall-still-round-small",A<=96);m=Y[m];P.suggestion!==m&&(P.suggestion=m,A=P.api.N(),M=g.mJ(P.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.vu(P,m,M),g.D6(A)&&!P.api.Y("web_player_log_click_before_generating_ve_conversion_params")&&(A=m.eD(),M={},g.Qy(P.api,"addEmbedsConversionTrackingParams",
[M]),A=g.jD(A,M),P.updateValue("url",A)),(m=(m=m.sessionData)&&m.itct)&&P.api.setTrackingParams(P.element,m));d++}e.ariaBusy="false";g.xl(this.element,"ytp-endscreen-paginate",d<U);for(Y=this.stills.length-1;Y>=d;Y--)r=this.stills[Y],g.lD(r.element),g.sV(r);this.stills.length=d}};
g.x.onVideoDataChange=function(){var r=this.player.getVideoData(1);this.videoData!==r&&(r!=null&&g.Ck(r)?(this.L=0,this.videoData=r,this.Ro()):this.player.pP("missg",{vid:(r==null?void 0:r.videoId)||"",cpn:(r==null?void 0:r.clientPlaybackNonce)||""}))};
g.x.HL=function(){this.L+=this.stills.length;this.Ro()};
g.x.s2=function(){this.L-=this.stills.length;this.Ro()};
g.x.BF=function(){return this.W.qQ()};
g.x.pL=function(r){r===1?(this.D=!1,this.K=this.videoData.clientPlaybackNonce,this.W.H9(),this.H5&&this.Ro()):(this.D=!0,this.H5&&Wk(this)&&(r===2?this.W.h7():r===3&&this.W.ww()))};
g.x.WL=function(r){if(r){for(r=0;r<this.stills.length;r++)this.C.logVisibility(this.stills[r].element,!0);this.pL(1)}else this.K=null,this.D=!1;this.Ro()};
g.x.eS=function(){return this.H5&&Wk(this)};g.W(zQ8,g.p);g.x=zQ8.prototype;g.x.YX=function(){switch(this.buttonType){case 1:var r="Watch again on YouTube";var l=156915;break;case 2:r="Continue watching on YouTube";l=156942;break;default:r="Continue watching on YouTube",l=156942}this.update({content:r});this.C.hasVe(this.element)&&this.C.destroyVe(this.element);this.C.createClientVe(this.element,this,l)};
g.x.onClick=function(r){this.C.Y("web_player_log_click_before_generating_ve_conversion_params")&&this.C.logClick(this.element);g.M7(this.getVideoUrl(),this.C,r);this.C.Y("web_player_log_click_before_generating_ve_conversion_params")||this.C.logClick(this.element)};
g.x.getVideoUrl=function(){var r=!0;switch(this.buttonType){case 1:r=!0;break;case 2:r=!1}r=this.C.getVideoUrl(r,!1,!1,!0);var l=this.C.N();if(g.D6(l)){var U={};g.D6(l)&&g.Qy(this.C,"addEmbedsConversionTrackingParams",[U]);r=g.jD(r,U)}return r};
g.x.logVisibility=function(){this.C.logVisibility(this.element,this.H5&&this.U)};
g.x.show=function(){g.p.prototype.show.call(this);this.logVisibility()};
g.x.hide=function(){g.p.prototype.hide.call(this);this.logVisibility()};
g.x.fp=function(r){g.p.prototype.fp.call(this,r);this.logVisibility()};g.W(Ev,C_);Ev.prototype.hasSuggestions=function(){var r;return(r=this.W)==null?void 0:r.hasSuggestions()};
Ev.prototype.show=function(){if(this.player.getPlayerState()!==3){C_.prototype.show.call(this);var r=this.X;if(r){var l=this.W.hasSuggestions();g.xl(this.element,"ytp-shorts-branded-ui",l);l?r.show():r.hide()}var U;(U=g.nF(this.player))==null||U.Uf(!0);this.player.logVisibility(this.element,!0);this.watchButton.fp(!0)}};
Ev.prototype.hide=function(){C_.prototype.hide.call(this);var r;(r=g.nF(this.player))==null||r.Uf(!1);this.player.logVisibility(this.element,!1);this.watchButton.fp(!1)};g.W(car,g.Rf);g.x=car.prototype;g.x.J7=function(){var r=this.player.getVideoData(),l=r.mutedAutoplay&&(r.limitedPlaybackDurationInSeconds>0||r.endSeconds>0||r.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!l)return!0;var U;var F=!!((r==null?0:g.Ck(r))||(r==null?0:(U=r.suggestions)==null?0:U.length));F=!pqr(this.player)||F;r=r.yj;U=this.player.uM();return F&&!r&&!U&&!l};
g.x.eS=function(){return this.endScreen.eS()};
g.x.XN=function(){return this.eS()?this.endScreen.BF():!1};
g.x.Rf=function(){this.player.MB("endscreen");g.Rf.prototype.Rf.call(this)};
g.x.load=function(){var r=this.player.getVideoData();var l=r.transitionEndpointAtEndOfStream;if(l&&l.videoId){var U=this.player.FL().nJ.get("heartbeat"),F=g.Ck(r);!F||l.videoId!==F.videoId||r.n_?(this.player.zI(l.videoId,void 0,void 0,!0,!0,l),U&&U.W2("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),r=!0):r=!1}else r=!1;r||(g.Rf.prototype.load.call(this),this.endScreen.show())};
g.x.unload=function(){g.Rf.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.x.onCueRangeEnter=function(r){this.J7()&&(this.endScreen.created||this.endScreen.create(),r.getId()==="load"&&this.load())};
g.x.onCueRangeExit=function(r){r.getId()==="load"&&this.loaded&&this.unload()};
g.x.onVideoDataChange=function(){LTp(this);this.L&&txC(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.W?this.endScreen=new Jr(this.player):this.endScreen=new xG(this.player),g.w(this,this.endScreen),g.Sg(this.player,this.endScreen.element,4))};g.ZR("endscreen",car);})(_yt_player);
